src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js
src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.less

fixed bugs

---

.gitignore
Dockerfile
docker-compose.yml
package.json
src/server/index.js
webpack/configUtils.js

add docker build

---

src/client/wallet/TransfersCards/ConvertHbdCompleted.js
src/client/wallet/TransfersCards/ConvertHbdRequest.js
src/client/wallet/TransfersCards/ConvertHiveCompleted.js
src/client/wallet/TransfersCards/ConvertHiveRequest.js
src/client/wallet/TransfersCards/PowerDownTransaction.js

fixed some minor bugs related to conversions and added comas to strings

fixed some minor bugs

---

src/client/wallet/TransfersCards/TokenBoughtCard.js/TokenActionInMarketCard.js
src/client/wallet/WAIVwallet/components/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js
src/server/index.js

added avatars, and from/to actions

---

src/client/locales/default.json
src/client/wallet/WalletHelper.js

changed history notification

---

src/client/wallet/TransfersCards/UndelegateStart.js

3500 fixed unedligated card in transaction list

---

src/client/websites/WebsiteTools/Configuration/WebsitesConfigurations.less
src/client/widgets/MapControllers/MapControllers.less

Add cursor pointer for map controls

---

src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.less

fixed bug with location mark on the restaurant card

---

src/client/object/ObjectOfTypePage/ObjectOfTypePage.js

Remove empty text v.2

---

src/client/websites/WebsiteTools/Configuration/WebsitesConfigurations.less
src/client/widgets/MapControllers/MapControllers.less

Add cursor

---

src/client/components/Story/Story.less
src/client/user/UserHeader/UserHeader.less

Fix text overflow

---

src/client/components/Comments/CommentForm.js

Format hashtags

---

src/client/wallet/UserWalletTransactions/UserWalletTransactions.less

changed red color for the whole account history

---

src/client/components/Sidebar/PostRecommendation.less
src/client/components/Story/StoryFull.less

fixed bug with long post title out of scope

---

src/client/components/Comments/Comment.js

Format hashtags in quick comment

---

src/client/components/Story/Story.less
src/client/user/UserHeader/UserHeader.less

Text overflow fix

---

src/client/components/Story/Body.js
src/client/components/Story/StoryFull.js

Replace http links with https

---

src/client/components/Comments/Comment.js
src/client/components/Comments/CommentForm.js

Fixes #
В предудыщем решении не учла, что у тегов немного другой url. Обсудили с Дианой, что будем разделять хэштеги пробелом, такой проблемы не будет

Fix hashtags

---

src/client/wallet/TransfersCards/SwapTokenCard/SwapTokenCard.less
src/client/wallet/UserWalletTransactions/UserWalletTransactions-nightmode.less
src/client/wallet/UserWalletTransactions/UserWalletTransactions.less

changes red color for nightmode

---

src/client/wallet/TransfersCards/DelegatedTo.js
src/client/wallet/TransfersCards/UndelegateStart.js
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js

changed symbol in account history for other tokens

---

src/client/wallet/Withdraw/Withdraw.less

changed layout of accept button in qr code scanner

---

src/client/components/Sidebar/WalletSidebar/WalletSidebar.js

deleted exchange button in user wallet

---

src/client/components/Story/StoryPreview.js

Fix broken video preview

---

src/client/post/EditPost/EditPost.js
src/store/editorStore/editorSelectors.js

Fixes #
Селектор, который был, возвращал undefined, переписала селектор
Как я изучила, что reselect, не оптимизировано работает с пропсами

Fix edit post content

---

src/client/components/Sidebar/WalletSidebar/WalletSidebar.js
src/client/wallet/WAIVwallet/WAIVwallet.less
src/store/editorStore/editorSelectors.js

placed the checkbox in the center

---

src/client/components/Sidebar/ObjectCard.js
src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js
src/client/components/Sidebar/ObjectsRelated/ObjectsRelatedContent/ObjectsRelatedContent.js
src/client/components/Sidebar/ObjectsRelated/ObjectsRelatedContent/index.js
src/client/components/Sidebar/ObjectsRelated/index.js

Fix avatar

---

src/client/rewards/QiuckRewardsModal/components/SecondScreen/SecondScreen-nightmode.less

Fix textarea style

---

src/client/components/Sidebar/ObjectCard.js
src/client/wallet/TransfersCards/HiveDelegatedCard.js

changes delegated card color

---

src/client/components/ImageSetter/ImageSetter-nightmode.less
src/client/rewards/QiuckRewardsModal/QuickRewardsModal-nightmode.less
src/client/rewards/QiuckRewardsModal/components/FirstScreen/FirstScreen-nightmode.less
src/client/rewards/QiuckRewardsModal/components/SecondScreen/SecondScreen-nightmode.less
src/client/websites/WebsiteLayoutComponents/MainPage/components/CarouselSection/CarouselSection.less
src/client/widgets/CircleSteps/CircleSteps-nightmode.less

Fix styles

---

src/client/vendor/ReduxInfiniteScroll.js

Fix loader

---

src/client/wallet/DelegateModals/ManageDelegate/ManageDelegate.js
src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.js
src/client/wallet/UserWalletSummary/UserWalletSummary.js
src/client/wallet/WAIVwallet/WAIVWalletSummaryInfo.js
src/client/wallet/WalletSummaryInfo/components/WalletAction/WalletActions.js
src/common/constants/delegationModalTypes.js
src/common/locales/default.json
src/store/walletStore/walletActions.js
src/store/walletStore/walletReducer.js
src/store/walletStore/walletSelectors.js

WAIV-3622 add delegation for wp and hp

---

src/common/helpers/swapTokenHelpers.js

fixed amount and removed zeros

---

src/client/wallet/WalletHelper.js
src/common/locales/default.json

changes description of a card

---

src/client/wallet/UserWalletTransactions/UserWalletTransactions-nightmode.less

changed color to green

---

src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/styles/modules/popover-layout.less

created separate class and changes style for facebook and twitter

---

src/client/wallet/SwapTokens/SwapTokens.js

added dots for swap tokens

---

src/common/locales/af-ZA.json
src/common/locales/ar-SA.json
src/common/locales/ca-ES.json
src/common/locales/cs-CZ.json
src/common/locales/da-DK.json
src/common/locales/de-DE.json
src/common/locales/es-ES.json
src/common/locales/et-EE.json
src/common/locales/fil-PH.json
src/common/locales/fr-FR.json
src/common/locales/hi-IN.json
src/common/locales/hr-HR.json
src/common/locales/hu-HU.json
src/common/locales/id-ID.json
src/common/locales/it-IT.json
src/common/locales/ja-JP.json
src/common/locales/ko-KR.json
src/common/locales/ms-MY.json
src/common/locales/pl-PL.json
src/common/locales/pt-BR.json
src/common/locales/ru-RU.json
src/common/locales/uk-UA.json
src/common/locales/zh-CN.json

add translation button names

---

src/client/wallet/UserWalletTransactions/UserWalletTransactions-nightmode.less
src/client/wallet/UserWalletTransactions/UserWalletTransactions.js
src/client/wallet/UserWalletTransactions/UserWalletTransactions.less

changed text color

---

src/client/post/EditPost/EditPost.js
src/store/editorStore/editorActions.js

review add correctly

---

src/client/components/EditorExtended/util/videoHelper.js
src/client/components/Story/Body.js
src/client/components/Story/StoryHelper.js
src/client/vendor/SanitizeConfig.js
src/client/vendor/embedMedia.js

fix video preview

---

src/client/app/Sidebar/UserInfo/HIVEtokenInfo.js

added space before number

---

src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js
src/routes/switchRoutes.js

replace waiv token to correct

---

src/client/wallet/Deposit/components/DepositInfo.js
src/client/wallet/WithdrawModal/WithdrawModal.js
src/common/locales/default.json
src/routes/switchRoutes.js

added spaces and withdraw button translation

---

src/common/locales/default.json

Added uppercase letters

---

src/client/wallet/TransfersCards/PowerUpTransactionFrom.js
src/client/wallet/UserWalletTransactions/UserWalletTransactions-nightmode.less
src/client/wallet/UserWalletTransactions/UserWalletTransactions.less
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js

fixed card with received to

---

src/client/app/Sidebar/UserInfo/HIVEtokenInfo.js
src/client/wallet/WithdrawModal/WithdrawModal.js

fixed issues with spaces

---

src/client/components/Story/Body.js
src/client/vendor/embedMedia.js

fix iframe

---

src/client/wallet/TransfersCards/MarketExpireCard.js
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js
src/common/locales/default.json

created a new card MarketExpireCard

---

src/client/styles/custom.less
src/client/websites/WebsiteLayoutComponents/MainPage/WebsiteMainPage-nightmode.less

changed title color and withdraw section background

---

src/client/wallet/DelegateModals/DelegateModal/DelegateModal.js
src/client/wallet/DelegateModals/ManageDelegate/components/TokenManage/TokenManage.js
src/client/wallet/UserWalletSummary/UserWalletSummary.js
src/common/locales/default.json

added some keys

---

src/client/activity/UserActivitySearch.less

places chackbox in the center

---

src/client/search/SearchAllResult/SearchAllList-nightmode.less
src/client/search/SearchAllResult/SearchAllResult.less
src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader-nightmode.less
src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.less

added some styles for map nightmode

---

src/client/notifications/Notifications.js

changed the link

---

src/client/wallet/TransfersCards/TokenBoughtCard.js/TokenActionInMarketCard.js
src/client/wallet/TransfersCards/TokenBoughtCard.js/TokenBoughtCard.less
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js

fixed buy and sell card added quantityHIVE

---

src/client/wallet/TransfersCards/TokenBoughtCard.js/TokenActionInMarketCard.js

added space between amount and point

---

src/client/search/SearchAllResult/SearchAllList-nightmode.less
src/client/styles/custom.less
src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader-nightmode.less

fixed nightmode for map

---

src/client/components/Navigation/Notifications/Notifications.js

changed link for notification reply

---

src/client/search/SearchAllResult/SearchAllList-nightmode.less
src/client/styles/custom.less

added styles for nightmode

---

src/common/helpers/regexHelpers.js

fix preview 3speak.tv in feed

---

src/common/locales/af-ZA.json
src/common/locales/ar-SA.json
src/common/locales/ca-ES.json
src/common/locales/cs-CZ.json
src/common/locales/da-DK.json
src/common/locales/de-DE.json
src/common/locales/es-ES.json
src/common/locales/et-EE.json
src/common/locales/fil-PH.json
src/common/locales/fr-FR.json
src/common/locales/hi-IN.json
src/common/locales/hr-HR.json
src/common/locales/hu-HU.json
src/common/locales/id-ID.json
src/common/locales/it-IT.json
src/common/locales/ja-JP.json
src/common/locales/ko-KR.json
src/common/locales/ms-MY.json
src/common/locales/pl-PL.json
src/common/locales/pt-BR.json
src/common/locales/ru-RU.json
src/common/locales/uk-UA.json
src/common/locales/zh-CN.json

add translation for delegations messages

---

src/waivioApi/ApiClient.js

remove follower field in user blog request when follower is empty

---

src/client/components/EditorExtended/util/videoHelper.js
src/client/vendor/embedMedia.js
src/common/helpers/regexHelpers.js

added support for shorts YouTube video in posts

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js
src/client/wallet/TransfersCards/SetWithdrawVestingRoute.js
src/client/wallet/UserWalletTransactions/UserWalletTransactions.less
src/common/locales/default.json

Bugfix/waiv 3055 withdraw notifications + task 3057

---

src/client/wallet/HiveEngineWallet/HiveEngineSummaryInfo.js
src/client/wallet/HiveEngineWallet/HiveEngineSummaryInfo.less
src/common/locales/default.json

centered status bar

---

src/client/wallet/ListTable/ListTable.js
src/client/wallet/ListTable/ListTable.less
src/waivioApi/ApiClient.js

fixed show more button, added symbol and fixed styles

---

src/client/components/EditorExtended/components/toolbar.js

remove extra-button

---

src/client/wallet/Wallets.js

changed hive wallet title

---

src/client/components/EditorExtended/components/blocktoolbar.js
src/client/components/EditorExtended/components/toolbar.js
src/client/components/EditorExtended/util/editorStateToMarkdown.js
src/client/components/EditorExtended/util/markdownToEditorState.js
src/client/components/Sidebar/WalletSidebar/WalletSidebar.js
src/client/wallet/ListTable/ListTable.js

fixed show more button

---

src/client/components/EditorExtended/components/blocktoolbar.js
src/client/components/EditorExtended/components/toolbar.js
src/client/components/EditorExtended/util/editorStateToMarkdown.js
src/client/components/EditorExtended/util/markdownToEditorState.js
src/client/wallet/TransfersCards/SetWithdrawVestingRoute/SetWithdrawVestingRoute-nightmode.less
src/client/wallet/TransfersCards/SetWithdrawVestingRoute/SetWithdrawVestingRoute.js

deleted space and fixed nightmode for withdraw vesting route card

---

src/client/components/EditorExtended/components/blocktoolbar.js
src/client/components/EditorExtended/components/toolbar.js
src/client/components/EditorExtended/util/editorStateToMarkdown.js
src/client/components/EditorExtended/util/markdownToEditorState.js
src/client/widgets/SelectUserForAutocomplete.js

fixed delete button

---

src/client/components/EditorObject/SearchObjectsAutocomplete.less

fixed z-index

---

src/client/components/EditorExtended/components/blocktoolbar.js
src/client/components/EditorExtended/components/toolbar.js
src/client/components/EditorExtended/util/editorStateToMarkdown.js
src/client/components/EditorExtended/util/markdownToEditorState.js
src/client/wallet/TransfersCards/HiveDelegatedCard.js
src/common/locales/default.json

added keys for hive wallet undelegated and delegated cards

---

src/client/components/EditorExtended/components/codebuttonbar.js
src/client/components/EditorExtended/components/toolbar.js
src/client/wallet/TransfersCards/MarketBuyCard/MarketBuyCard.js
src/client/wallet/TransfersCards/MarketBuyCard/MarketBuyCard.less

changed min fraction digits

---

src/client/components/Story/Body.js
src/client/components/Story/PostFeedEmbed.less
src/client/vendor/asyncVideo.js
src/client/vendor/embedMedia.js

fixed odysee preview

---

src/client/components/EditorExtended/components/addbutton.js
src/client/components/EditorExtended/components/addbutton.less

changed plus button color

---

src/client/wallet/Transfer/Transfer.js

fixed transfer modal

---

src/common/helpers/regexHelpers.js

fixed preview 3speak video

---

src/client/wallet/TransfersCards/DelegateInstructionCard/DelegateInstructionCard.js
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js
src/common/locales/default.json

changed deposit card

---

src/client/components/EditorExtended/components/addbutton.less

changed buttons style

---

src/client/styles/common.less
src/common/helpers/regexHelpers.js

fixed video-preview and scroll in BitChute videos

---

src/client/wallet/Transfer/Transfer.js

fixed issues with max button and border

---

src/client/components/EditorExtended/components/toolbar.js

added h4 in toolbar

---

src/client/components/EditorExtended/components/toolbar.js

fix position of toolbar on small screen

---

src/client/components/Story/PostFeedEmbed.less

fixed height of bitchcute video

---

src/client/wallet/Transfer/Transfer.less

removed border right in input

---

src/client/components/EditorExtended/components/addbutton.less

changed styles for buttons on small screen

---

src/client/components/EditorExtended/components/toolbar.less

fixed size icons of toolbar

---

src/client/wallet/Transfer/Transfer.js
src/client/wallet/Transfer/Transfer.less

changed inputs in transfer modal

---

src/client/components/EditorExtended/components/toolbar.less

fix position of code icon

---

src/client/components/EditorExtended/components/toolbar.js
src/client/components/EditorExtended/components/toolbar.less

fixed toolbar buttons hover

---

src/client/wallet/ListTable/ListTable.less

fixed style for show more button

---

src/client/components/EditorExtended/components/toolbar.js

deleted space in the link icon in toolbar

---

src/client/components/EditorExtended/util/markdownToEditorState.js
src/client/components/Story/Body.js
src/client/object/AppendModal/AppendForm.js
src/common/helpers/editorHelper.js

added indents preservation for editor

---

src/client/wallet/Transfer/Transfer.js

disabled max button in rewards payables

---

src/client/objectCard/ObjectCardView-nightmode.less

fixed nightmode hover for restaurant drink and dish cards

---

public/images/icons/arrow-toolbar.svg
src/client/components/EditorExtended/components/toolbar.js
src/client/components/EditorExtended/components/toolbar.less

toolbar pagination

---

src/client/components/Reactions/ReactionsList.js

sorted upvotes list

---

src/client/objectCard/RatingsWrap/RatingsWrap-nightmode.less

changed rate title color

---

src/client/widgets/MapControllers/MapControllers.less

centered my colaction icon

---

src/client/components/EditorExtended/util/videoHelper.js
src/client/vendor/embedMedia.js
src/common/helpers/regexHelpers.js

video-platform fixes

---

src/client/components/StoryFooter/Buttons.js

added sort for pop-up upvotes

---

src/common/helpers/editorHelper.js

fix spaces

---

src/client/wallet/TransfersCards/MarketBuyCard/MarketBuyCard.js

fixed limit order color

---

src/client/components/Story/PostFeedEmbed.js

fixed error when opening posts

---

src/client/rewards/Proposition/Proposition-nightmode.less

fixed preposition hover in nightmode

---

src/client/widgets/MapControllers/MapControllers.less

changed my location picture position

---

src/client/components/Story/Body.js

fixed embeded link 3speak

---

src/client/components/Reactions/ReactionsList.js
src/client/components/StoryFooter/Buttons.js

fixed sort for upvotes

---

src/client/components/EditorExtended/util/videoHelper.js
src/client/components/Story/Body.js
src/client/vendor/embedMedia.js
src/common/helpers/regexHelpers.js

fixed fb video

---

src/client/wallet/OrdersTable/BuyOrdersTableHive.js
src/client/wallet/OrdersTable/SellOrdersTableHive.js

fixed bug where the 1st element wasn't shown for the first time

---

src/client/components/EditorExtended/components/toolbar.less

centered icons for link and next/back buttons, fixed borders

---

src/client/components/EditorExtended/components/addbutton-nightmode.less

added nightmode styles for insert menu

---

src/client/post/PostPreviewModal/PostPreviewModal-nightmode.less

fixed style for publish button in nightmode

---

src/client/wallet/TransfersCards/MarketBuyCard/MarketBuyCard.js

fixed color

---

src/client/wallet/TransfersCards/SwapTokenCard/SwapTokenCard.js
src/client/wallet/TransfersCards/SwapTokenCard/SwapTokenCard.less

changed style for swap card

---

src/client/wallet/Transfer/Transfer.js

fixed max button for deposit modal

---

src/client/post/PostPreviewModal/PostPreviewModal.js

added publish button styles for nightmode

---

src/client/wallet/Transfer/Transfer.js

fixed token field

---

src/client/websites/WebsiteLayoutComponents/MainPage/WebsiteMainPage.less

added border top radius for steps headers

---

src/client/wallet/WalletHelper.js
src/client/wallet/WalletTable/common/helpers.js
src/common/constants/accountHistory.js

added cancel limit order

---

src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.js
src/client/wallet/Transfer/Transfer.js
src/common/locales/default.json

fixed validation for modals

---

src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.js
src/common/locales/default.json

added validation for hive and hbd currency

---

src/client/components/EditorExtended/editorSlate.js
src/client/components/EditorExtended/index.less
src/client/components/EditorExtended/util/SlateEditor/utils/paragraph.js
src/client/components/HeaderButton/HeaderButton.js
src/client/components/Story/Body.less
src/client/components/Story/BodyShort.js
src/store/slateEditorStore/editorActions.js

fixed display of table in body short

---

src/client/wallet/TransfersCards/PowerUpTransactionFrom.js

fixed power up cards

---

src/client/components/EditorExtended/util/SlateEditor/plugins/withEmbeds.js
src/client/components/EditorExtended/util/SlateEditor/toolbar/toolbar.js
src/client/components/EditorExtended/util/SlateEditor/toolbar/toolbarGroups.js

fixed order of toolbar, returned the quote button

---

src/client/wallet/WalletTable/WAIVwalletTable.js

fixed backend task to display more than 500 transactions

---

src/client/components/EditorExtended/components/addbuttonSlate.js
src/client/components/EditorExtended/components/sides/EmojiButton.js
src/client/components/EditorExtended/components/sides/VideoButtonSlate.js
src/client/components/EditorExtended/components/toolbar.less
src/client/components/EditorExtended/editorSlate.js
src/client/components/EditorExtended/model/content.js
src/client/components/EditorExtended/util/SlateEditor/Editor.js
src/client/components/EditorExtended/util/SlateEditor/toolbar/codebutton.js
src/client/components/EditorExtended/util/SlateEditor/toolbar/toolbarGroups.js
src/client/components/EditorExtended/util/SlateEditor/utils/SlateUtilityFunctions.js
src/client/components/EditorExtended/util/SlateEditor/utils/constants.js
src/client/components/EditorExtended/util/SlateEditor/utils/parse.js

fixed focus after smile insertion

---

src/client/wallet/PowerUpOrDown/PowerUpOrDown.js

fixed continue button

---

src/client/components/EditorExtended/util/constants.js

fixed pasting in edge

---

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js
src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.js
src/client/components/EditorExtended/util/SlateEditor/plugins/withEmbeds.js
src/client/components/EditorExtended/util/constants.js
src/common/helpers/editorHelper.js

fixed paste html

---

src/common/helpers/editorHelper.js

fixed double word hashtag

---

src/client/wallet/WalletTable/WAIVwalletTable.js

fixed checkboxes

---

src/client/wallet/WalletHelper.js
src/client/wallet/WalletTable/common/helpers.js
src/common/constants/accountHistory.js

added fill order operation to hive advanced report

---

src/client/components/EditorExtended/editorSlate.js
src/client/components/EditorExtended/util/SlateEditor/utils/common.js

fixed vertical space after insert object

---

package.json
src/client/components/EditorExtended/editorSlate.js
src/client/components/EditorExtended/util/SlateEditor/elements/link/link.js
src/client/components/EditorExtended/util/SlateEditor/elements/link/styles.less
src/store/slateEditorStore/editorSelectors.js

fixed editor re-return object card after remove

---

src/client/components/EditorExtended/components/toolbar.less
src/client/components/EditorExtended/util/SlateEditor/utils/link.js

added link normalizing

---

src/client/components/EditorExtended/util/SlateEditor/toolbar/toolbar.js

fixed clear link-input

---

src/client/wallet/WalletTable/WAIVwalletTable.js

checkboxes fixes

---

src/client/wallet/WalletTable/TableFilter.js
src/client/wallet/WalletTable/WalletTable.js

fixed error message

---

src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferList.js

fixed loading while opening transactions list in waiv wallet

---

src/client/post/CreateObjectModal/CreateObject.js
src/client/wallet/SwapTokens/components/TokenSelect.less

added new Aa button

---

src/client/components/EditorExtended/editorSlate.js
src/client/components/EditorExtended/util/SlateEditor/plugins/withEmbeds.js

fixed pasting objects and links

---

src/client/components/EditorExtended/components/entities/objectlink.js
src/client/components/EditorExtended/util/SlateEditor/utils/common.js

fixed space after hashtag

---

src/client/components/Editor/Editor.less

added space between button and input area

---

src/client/wallet/PowerUpOrDown/PowerUpOrDown.js
src/client/wallet/WithdrawModal/WithdrawModal.js

fixed round amounts

---

src/client/components/EditorExtended/components/sides/ObjectSideButton.js
src/client/newRewards/Rebalancing/Rebalancing.js

added one more request

---

src/client/wallet/WalletTable/WAIVwalletTable.js
src/client/wallet/WalletTable/WalletTable.js
src/client/wallet/WalletTable/common/helpers.js

fixed transferred to transactin and disabled link

---

src/client/wallet/DelegateModals/DelegateModal/DelegateModal.js

fixed amount in delegate modal

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/client/wallet/SwapTokens/SwapTokens.js
src/client/wallet/SwapTokens/components/TokensSelect.js
src/store/swapStore/swapActions.js

fixed rebalancing swap

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/client/wallet/SwapTokens/SwapTokens.js
src/store/rewardsStore/rewardsActions.js

fixed socket connections and balance in swap-rebalancing

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/newRewards/Rebalancing/Rebalancing.js
src/client/newRewards/Rebalancing/Rebalancing.less
src/client/notifications/Notifications.js
src/client/wallet/SwapTokens/SwapTokens.js
src/client/wallet/SwapTokens/components/TokenSelect.less
src/client/wallet/SwapTokens/components/TokensSelect.js

fixed rebalancing text/markup

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/store/rewardsStore/rewardsActions.js

added ws request

---

src/client/components/Comments/CommentForm.js

fixed loading editor

---

src/client/newRewards/Rebalancing/Rebalancing.js

fixed remove round for earn in rebalancing

---

src/client/components/Comments/CommentForm.js
src/client/components/EditorExtended/components/sides/ImageButtonSlate.js

fixed editor bug in comments

---

src/client/wallet/SwapTokens/components/TokenSelect.less
src/client/wallet/WalletTable/common/helpers.js

fixed power down description

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/client/newRewards/Rebalancing/configRebalancingTable.js

changed rebalancing table

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/client/newRewards/Rebalancing/configRebalancingTable.js
src/common/helpers/apiHelpers.js

added hide extra columns on mobile

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/client/rewards/Rewards.js

fixed rebalancing routes

---

src/common/constants/notifications.js

fixed new notifications and bell count

---

src/client/components/Navigation/TopNavigation.js

fixed routing of rewards

---

src/client/wallet/SwapTokens/components/TokensSelect.js

fixed max btn

---

src/client/object/AppendModal/AppendForm.js

fixed new lines in links

---

src/client/styles/common.less

removed second scroll bar

---

src/client/components/Navigation/TopNavigation.js

merge staging

---

src/client/rewards/FilteredRewardsList.js
src/client/rewards/Rewards.js

fixed error with null of field

---

src/client/newRewards/Rebalancing/Rebalancing.js

fixed difference column on mobile

---

src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js

added error

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js
src/client/rewards/Rewards.js

fixed spaces between slashes

---

src/client/rewards/Rewards.js
src/client/wallet/Wallets.js
src/client/wallet/Wallets.less

fixed wallets scroll and removed arrows

---

src/common/locales/default.json

rename Rewards to Earn in menu near the triangle button

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ProductId/ProductId.js
src/client/app/Sidebar/ProductId/index.js
src/client/components/ImageSetter/ImageSetter.js
src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js
src/common/constants/listOfFields.js
src/common/locales/default.json

sdded product id for objects

---

src/client/wallet/Wallets.js
src/client/wallet/Wallets.less

fixed comments for scroll in wallets

---

src/client/wallet/WalletTable/WAIVwalletTable.js
src/client/wallet/WalletTable/WalletTable.js

csv export to excel fixes

---

src/client/newRewards/Rebalancing/Rebalancing.js
src/client/newRewards/Rebalancing/Rebalancing.less
src/client/newRewards/Rebalancing/TableProfit/TableProfit.js
src/client/newRewards/Rebalancing/TableProfit/TableProfit.less
src/client/wallet/AddToken/AddToken.js
src/client/wallet/AddToken/AddToken.less
src/client/wallet/EditToken/EditToken.js
src/client/wallet/EditToken/EditToken.less
src/client/wallet/SwapTokens/components/TokensSelect.js

fixes with profit report

---

src/client/components/UserMenu.js
src/client/components/UserMenu.less

fixed user menu position

---

src/client/wallet/WalletTable/WAIVwalletTable.js
src/client/wallet/WalletTable/WalletTable.js
src/client/wallet/WalletTable/WalletTable.less

fixed csv button

---

src/client/components/EditorExtended/editorSlate.js

fixed editor of page initial text

---

src/client/wallet/EditToken/EditToken.js
src/client/wallet/EditToken/EditToken.less

fixed size of token select in edit modal

---

src/client/styles/common.less

fixed content overflow

---

src/client/newRewards/Rebalancing/Rebalancing.js

changed info text in rebalancing

---

src/client/app/Sidebar/CompanyId/CompanyId.less
src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ProductId/ProductId.js
src/client/components/Story/StoryPreview.js
src/client/object/AppendModal/AppendForm.js

added image to product id card

---

src/client/components/UserMenu.js
src/client/components/UserMenu.less

restored previous styles

---

src/client/object/AppendModal/AppendForm.js

changed order

---

src/client/wallet/SwapTokens/SwapToken-nightmode.less
src/client/wallet/SwapTokens/SwapTokens.less

rebalancing disabled fields styles

---

src/client/object/ObjectOfTypePage/ObjectOfTypePage.js
src/waivioApi/ApiClient.js
src/waivioApi/config.json

added draft for page

---

src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js
src/client/rewards/QiuckRewardsModal/QuickRewardsModal.less

added warning if no reward is found

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js
src/common/locales/default.json

fixed notifications message

---

src/client/wallet/SwapTokens/SwapTokens.less

fixed font size

---

src/client/components/EditorExtended/components/addbuttonSlate.js
src/client/object/ObjectOfTypePage/ObjectOfTypePage.js

fixed loading

---

src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js
src/client/rewards/QiuckRewardsModal/QuickRewardsModal.less

warning styles fixes

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js

fixed links to accounts and icons

---

src/client/wallet/SwapTokens/components/TokenSelect.less

fixed inputs padding

---

src/client/rewards/QiuckRewardsModal/components/FirstScreen/FirstScreen.js

fixed lots af requests

---

src/client/wallet/Deposit/Deposit-nightmode.less

fixed styles for delegate and deposit modals

---

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js
src/client/components/EditorExtended/components/addbuttonSlate.js
src/client/object/ObjectOfTypePage/ObjectOfTypePage.js

added draft for nested object, optimization of editor

---

src/client/object/ObjectOfTypePage/ObjectOfTypePage.js

fixed removed nested object draft when save post

---

src/client/components/EditorExtended/util/SlateEditor/utils/parse.js

fixed remove html from images in editor

---

src/store/appendStore/appendActions.js
src/store/appendStore/appendReducer.js

fixed endless loading in page editor

---

src/common/constants/listOfObjectTypes.js

added book type of object types

---

src/client/Wrapper.js
src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js
src/client/widgets/CircleSteps/CircleSteps.less
src/client/widgets/CircleSteps/StepsItems.js

fixed number of pages shown if there is no reward for a dish

---

src/client/components/EditorExtended/EditorExtendedComponent/index.js
src/client/components/EditorExtended/editorSlate.js
src/client/components/EditorExtended/util/SlateEditor/plugins/withEmbeds.js
src/store/slateEditorStore/editorReducer.js

fixed paste html with links

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js
src/common/constants/listOfFields.js
src/common/locales/default.json

added language field for book object

---

src/client/components/Comments/QuickCommentEditor.less
src/client/components/EditorExtended/index.less

fixed size of text in comment editor

---

src/client/components/EditorExtended/util/SlateEditor/elements/link/link.js

fixed copy paste link

---

src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js

fixed steps for post creation

---

src/client/components/Comments/CommentForm.js
src/client/components/Comments/QuickCommentEditor.js
src/client/components/EditorExtended/components/addbuttonSlate.js
src/client/components/EditorExtended/editorSlate.js

fixed bug with scroll in feed on firefox

---

src/client/object/AppendModal/AppendForm.js
src/common/constants/listOfFields.js

added error submit button disable

---

src/client/components/EditorExtended/util/SlateEditor/elements/link/link.js

fixed display url in link

---

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js
src/common/helpers/editorHelper.js

fixed vertical spaces in editor

---

public/images/icons/calendar-icon.svg
src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ObjectInfo.less
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/AppendForm.less

fixed datePicker position and some comments

---

webpack/client.js

turn on source map for debug

---

src/client/components/EditorExtended/util/SlateEditor/plugins/withEmbeds.js

fixed pasting images in ios

---

src/common/helpers/image.js

fixed pasting images on mobile

---

webpack/client.js

removed source map

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js
src/common/constants/listOfFields.js
src/common/locales/default.json

added print length field

---

src/client/components/EditorExtended/util/SlateEditor/toolbar/toolbar.js
src/common/helpers.js

lifted up the toolbar on ios

---

src/client/components/EditorExtended/util/SlateEditor/toolbar/toolbar.js
src/common/helpers.js

fixed toolbar on ios

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/common/constants/listOfFields.js
src/common/helpers.js
src/common/locales/default.json

fixed input validation

---

src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js
src/client/rewards/QiuckRewardsModal/QuickRewardsModal.less
src/client/rewards/QiuckRewardsModal/components/FirstScreen/FirstScreen.js

fixed search dish or drink input style for mobile

---

src/client/notifications/Notifications.js
src/common/locales/default.json

fixed spelling in rebalancing notification

---

src/client/wallet/Wallets.js

changed submenu

---

src/client/post/PostPreviewModal/PostPreviewModal.less

fixed editor title margin

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js

fixed rebalancing notifications on close

---

src/client/components/UserMenu.js
src/client/user/UserDynamicList.js
src/client/user/UserFollowers.js
src/client/user/UserFollowing.js
src/client/user/UserFollowing.less

added new submenu to followers section

---

src/client/components/Navigation/TopNavigation.js

changed defauld discover object to restaurant

---

src/client/user/UserFollowers.js

fixed following number

---

src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/AppendModal.js
src/client/object/WobjHistory/WobjHistory.js

fixed current field setting

---

src/client/components/UserMenu.js

returned followers number

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js

added notification window close

---

src/client/object/AppendModal/AppendForm.js

fixed weight and dimensions order

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js
src/common/constants/listOfFields.js

fixed required fields, styles

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js
src/common/constants/listOfFields.js

fixed publisher field

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ObjectInfo.less
src/client/object/AppendModal/AppendForm.js

publisher name and style fixes

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js

fixed styles and adding fields using add button

---

src/client/components/UserMenu.js
src/client/components/UserMenu.less
src/client/user/UserProfile.js
src/routes/configs/routes.js
src/routes/configs/websitesRoutes.js

added second level menu for Posts / Comments / Activity

---

src/client/components/UserMenu.less
src/client/user/UserProfile.js

fixed style for userMenu and right sidebar

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js

fixed groupid text and product id styles

---

src/client/components/ObjectMenu.less
src/routes/configs/websitesRoutes.js

fixed menu bugs and added routes

---

src/client/app/Sidebar/ObjectInfo.js
src/common/constants/listOfFields.js

fixed submit button

---

src/client/app/Sidebar/ObjectInfo.js

fixed fields layout

---

src/client/app/Sidebar/ObjectInfo.js

fixed gallery and price layout

---

src/client/components/Navigation/ModlaSignIn/ModalSignIn.js
src/client/user/PostsCommentsActivity.js
src/routes/components.js
src/routes/configs/routes.js
src/routes/configs/websitesRoutes.js

fixed issue when Posts menu displays in Blog feed on object feed

---

src/client/components/Navigation/ModlaSignIn/ModalSignIn.js
src/client/components/Story/StoryPreview.js

fixed post updates cards view

---

src/client/object/PicturesCarousel.js
src/client/object/PicturesCarousel.less

fixed options comments

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/PicturesCarousel.js

fixed on gallery picture click

---

src/client/components/Story/StoryPreview.js

changed text and image position for updates

---

src/client/wallet/TransfersCards/ReceiveTransaction.js

fixed received card color

---

src/client/user/PostsCommentsActivity.js
src/client/user/UserFollowers.js

fixed translation keys

---

src/common/locales/default.json

renamed widget

---

src/client/newRewards/PropositionLists/ReservedProposition.js
src/client/newRewards/RewardLists/EligibleRewards.js
src/client/newRewards/RewardLists/RewardsAll.js
src/client/objectCard/ObjectCardView.js
src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js
src/client/rewards/QiuckRewardsModal/components/SecondScreen/SecondScreen.js
src/client/user/PostsCommentsActivity.js
src/client/widgets/CircleSteps/StepsItems.js

fixed activity tab

---

src/client/newRewards/PropositionLists/ReservedProposition.js
src/client/newRewards/RewardLists/EligibleRewards.js
src/client/newRewards/RewardLists/RewardsAll.js
src/client/object/AppendModal/AppendForm.js
src/client/objectCard/ObjectCardView.js
src/client/rewards/QiuckRewardsModal/QuickRewardsModal.js
src/client/rewards/QiuckRewardsModal/components/SecondScreen/SecondScreen.js
src/client/widgets/CircleSteps/StepsItems.js

fixed adding pictures to default album

---

src/client/object/AppendModal/AppendForm.js
src/client/post/CreateObjectModal/CreateObject.js

some fixes to append object timeout, fixed avatar adding

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/ObjectMenu.js
src/client/object/const/objectTypes.js
src/common/locales/default.json

restyled widget and newsfeed

---

src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js
src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.less

some fixs to header avatar, padding, partners-> legal, name

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/WidgetPage/WidgetPage.js

removed back button and added listItem to widget and newsfeed

---

src/client/components/ObjectHeader.less

centered title for mobile

---

src/client/object/Department/Department.js

removed empty departments title

---

src/client/object/AppendModal/AppendForm.js

some fixes to gallery

---

src/client/rewards/MatchBots/MatchBotsModals/common/ModalBodySlider/ModalBodySlider.js
src/common/helpers/matchBotsHelpers.js

chnged default currency to WAIV

---

src/client/object/Department/Department.js
src/client/object/Department/Department.less

departments prefix fixes

---

src/client/rewards/MatchBots/MatchBotsTable/MatchBotsTableRow/MatchBotsTableRow.js
src/common/helpers/matchBotsHelpers.js

added default minVotingPowerCurrency to curator bot modal

---

src/client/components/HeaderButton/HeaderButton.js
src/client/components/Navigation/Topnav.less
src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js

added menu for not auth user

---

src/client/object/AppendModal/FormComponents/ExtendedNewsFilterForm.js

changed conjunction

---

src/client/object/ObjectFeed/ObjectFeed.js

fixed reviews feed

---

src/client/object/AppendModal/FormComponents/ExtendedNewsFilterForm.js

added or layout

---

src/client/post/CreateObjectModal/CreateObject.js

fixed obj title register

---

src/client/components/HeaderButton/HeaderButton.js
src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js

fixed link to legal and removed menu for desktop

---

src/client/components/Sidebar/FilterPosts/FilterPosts.js
src/store/feedStore/feedActions.js
src/store/feedStore/feedReducer.js
src/store/feedStore/feedSelectors.js
src/waivioApi/ApiClient.js
src/waivioApi/config.json

refactored tags request

---

src/client/components/HeaderButton/HeaderButton.js

added about legal and reviews to auth user menu

---

src/client/components/HeaderButton/HeaderButton.js
src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js

changed legal link

---

src/client/app/Sidebar/ObjectInfo.less

added spaces

---

src/client/post/CreateObjectModal/CreateObject.js

fixed error on object creation

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/PicturesCarousel.js

if a picture doesn't belong to album, the gallery opens

---

src/client/components/HeaderButton/HeaderButton.js
src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js

legal link fixes

---

src/client/object/PicturesCarousel.js

fixed error and added one more condition

---

src/client/components/HeaderButton/HeaderButton.js

removed about from desktop version

---

src/client/object/AppendModal/AppendForm.js
src/client/object/Options/Options.js

fixed object options permlink

---

src/client/app/Sidebar/ObjectInfo.js

fixed photos carousel condition, gallery fixes

---

src/client/app/Sidebar/ObjectInfo.js

added hover picture when there is no avatar or gallery

---

src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/AppendForm.less
src/client/object/const/appendFormConstants.js
src/client/post/CreateObjectModal/CreateObject.js

made obj name and description longer + style fixes

---

src/client/object/WobjHistory/WobjHistory.js
src/common/helpers/wObjectHelper.js

sorted updates filters alphabetically A..Z

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ProductId/ProductId.js
src/client/object/Department/Department.js
src/client/object/ObjectFeatures/ObjectFeatures.js

fixed styles for object fields

---

src/client/object/const/appendFormConstants.js

increased name number to 200

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ProductId/ProductId.js
src/client/object/Options/Options.js

removed extra spaces

---

src/client/object/WobjHistory/WobjHistory.js

rewrote sorting for filter updates

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/waivioApi/ApiClient.js
src/waivioApi/config.json

added publisher avatar

---

src/client/object/AppendModal/AppendForm.js
src/client/object/const/appendFormConstants.js
src/common/constants/listOfFields.js

fixed obj name

---

src/client/object/WobjHistory/WobjHistory.js

fixed sorting

---

src/client/object/AppendModal/AppendForm.js
src/common/constants/listOfFields.js

added button disable for name field

---

src/client/object/AppendModal/AppendForm.js

fixed name request

---

src/client/object/ObjectFeed/ObjectFeed.js
src/waivioApi/ApiClient.js
src/waivioApi/config.json

fixed neswfeed posts in myfeed

---

src/client/post/CreateObjectModal/CreateObject.js

fixed changing register even if there are spaces after the last word

---

src/client/app/Sidebar/DescriptionInfo.js
src/client/app/Sidebar/ObjectInfo.less

added saving description breaks

---

src/client/object/ObjectFeed/ObjectFeed.js

fixed show mode feed posts

---

src/client/object/DepartmentsPage/DepartmentsPage.js

fixed scroll to top

---

src/client/app/Sidebar/ObjectInfo.js

removed gallery is option doesn't have picture

---

src/client/app/Sidebar/ObjectInfo.js

removed gallery if there is no avatar but options have pictures

---

src/client/websites/WebsiteLayoutComponents/MainPage/WebsiteMainPage.less
src/client/websites/WebsiteSignIn/WebsiteSignIn.less
src/client/websites/WebsiteSignIn/styles.js

small fixes for DG

---

src/client/websites/WebsiteLayoutComponents/MainPage/WebsiteMainPage.less

fixed font size for desktop

---

src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.less
src/client/wallet/Transfer/Transfer.less

max button fixes

---

src/client/websites/WebsiteSignIn/styles.js

fixed social button width

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ObjectInfo.less
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/AuthorForm.js
src/client/object/AppendModal/FormComponents/BrandForm.js
src/client/object/AppendModal/FormComponents/ManufacturerForm.js
src/client/object/AppendModal/FormComponents/MerchantForm.js
src/client/object/AppendModal/FormComponents/PublisherForm.js
src/client/object/wObjectHelper.js
src/client/post/CreateObjectModal/CreateObject.js
src/common/constants/listOfFields.js
src/common/locales/default.json

started adding new fields

---

src/client/websites/WebsiteSignIn/SocialButton.js
src/client/websites/WebsiteSignIn/styles.js

sign in modal buttons style fixes

---

src/client/wallet/PowerUpOrDown/PowerUpOrDown.less

fixed max button on power up/down modals

---

src/client/object/Description/DescriptionPage.js

fixes a lot of requests + style for description page

---

src/client/app/Sidebar/ObjectInfo.js

fixed description field padding

---

src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.less

max button fixes ondelegate modal

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Description/DescriptionInfo.js
src/client/object/Description/DescriptionPage.js

femoved unnecessary request

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js

changed obj fields names

---

src/client/app/Sidebar/ObjectInfo.js

added update fields condition

---

src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.js
src/client/wallet/PowerUpOrDown/PowerSwitcher/PowerSwitcher.less
src/client/wallet/PowerUpOrDown/PowerUpOrDown.js

fixed amout styles for power up/down modals and delegate

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/SearchDepartmentAutocomplete/DepartmentSearchCard.js
src/client/components/SearchDepartmentAutocomplete/SearchDepartmentAutocomplete.js
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/AppendForm.less
src/client/object/Options/OptionsPage.js
src/waivioApi/ApiClient.js

added department search, fixes fo options request

---

src/client/components/SearchDepartmentAutocomplete/SearchDepartmentAutocomplete.js
src/waivioApi/ApiClient.js

fixed departments request, departments input fixes

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Options/Options.js

fixed front crash

---

src/client/object/Options/OptionItem/OptionItemEdit.js

fixes for font crash

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Options/OptionItem/OptionItemEdit.js
src/client/object/Options/OptionsPage.js

fixed options

---

src/client/app/Sidebar/ObjectInfo.js

added one more condition for request

---

src/client/components/Story/Body-nightmode.less
src/client/objectCard/ObjectCardView-nightmode.less

fixes for description and options pages  nightmode

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/SearchDepartmentAutocomplete/SearchDepartmentAutocomplete.js
src/client/object/AppendModal/AppendForm.less

fixes for obj updates

---

src/client/object/Options/Options.less

fixed long options hover and select

---

src/client/widgets/HeartButton.js

fixed vote  request

---

src/client/wallet/TransfersCards/PowerUpTransactionFrom.js
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js

Fix currency message about power up to in waiv

---

src/client/object/WobjHeader.js
src/client/objectCard/ObjectCardView.js

removed heart for not auth user

---

src/client/wallet/TransfersCards/UndelegateCompleted.js
src/client/wallet/TransfersCards/UndelegateStart.js
src/client/wallet/WAIVwallet/WAIVWalletTransferList/WAIVWalletTransferItemsSwitcher.js

changed airdrop cards and undeledated cards

---

src/client/components/Comments/CommentForm-nightmode.less
src/client/components/Comments/CommentForm.less
src/client/components/Comments/Comments-nightmode.less
src/client/components/Comments/Comments.less
src/client/components/Sidebar/SidebarContentBlock-nightmode.less
src/client/components/Story/Body-nightmode.less

fixed posts nightmode

---

src/client/wallet/TransfersCards/PowerUpTransactionFrom.js

removed amount duplicate

---

src/client/object/AppendModal/AppendForm.js
src/client/widgets/HeartButton.js

heart button fixes

---

src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/object/AppendModal/AppendForm.js

added pin remove for own user post

---

src/client/components/PostPopoverMenu/PostPopoverMenu.js

changed remove post icon

---

src/store/appendStore/appendActions.js

added post reload for pinned obj

---

src/client/components/PopoverMenu/PopoverMenuItem.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/object/WobjHistory/UpdateHistory.js

added condition for pin updates

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/DepartmentsPage/DepartmentsPage.js
src/waivioApi/ApiClient.js

fixed departments in left sidebar, hearts on departments fixes

---

src/client/wallet/TransfersCards/PowerUpTransactionFrom.js

power up card fixes

---

src/client/object/Options/OptionsPage.js
src/waivioApi/ApiClient.js

heart on options page fixes

---

src/store/appendStore/appendActions.js

fixed loader for updates pin and remove

---

src/client/widgets/HeartButton.js

fixed heart on different pages

---

src/client/wallet/TransfersCards/DelegatedTo.js

changed point for delegated cards

---

src/client/object/Options/Options.less

fixed long options

---

src/client/object/Options/Options.less
src/store/appendStore/appendActions.js

remove updates do not update the page

---

src/client/wallet/TransfersCards/DelegatedTo.js
src/client/wallet/TransfersCards/TransactionCardContainer.js
src/client/wallet/TransfersCards/UndelegateStart.js
src/common/locales/default.json

delegations cards fixes

---

src/client/app/Sidebar/ObjectInfo.js

pin remove fixes

---

src/client/Shop/ShopDepartments/ShopDepartmentsList.js
src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js
src/client/object/ObjectTypeShop/ObjectDepartmentsWobjList.js
src/client/object/ObjectTypeShop/WobjectShoppingList.js
src/client/object/wObjectHelper.js

shop object type fixes

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/components/StoryFooter/Buttons.js
src/store/postsStore/postActions.js
src/store/postsStore/postsReducer.js

disabled remove button

---

src/client/Shop/ShopDepartments/ShopDepartmentsList.js
src/client/Shop/ShopList/ShopList.js
src/client/app/Sidebar/ObjectInfo.js
src/client/object/ObjectTypeShop/DepartmentsWobject.js

shop filter fixes

---

src/client/components/Navigation/TopNavigation.js
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/ShopFilterForm.js

fixed shop filter form

---

src/client/object/AppendModal/FormComponents/ShopFilterForm.js

removed focus from authorities search

---

src/client/Shop/ShopDepartments/ShopDepartmentsList.js

fixes departments after adding shopFilter

---

src/client/object/Options/OptionItem/OptionItemView.js

renamed function

---

src/client/object/Options/OptionItem/OptionItemView.js

options colors fixes

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Options/OptionItem/OptionItemView.js

fixed onject group id change

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js
src/client/app/Sidebar/MenuItemButtons/MenuItemButtons.js
src/client/app/Sidebar/MenuItemButtons/MinuItemButtons.less
src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ObjectInfo.less
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/MenuItemForm.js
src/client/object/wObjectHelper.js
src/common/constants/listOfFields.js
src/common/locales/default.json

added menu legacy part

---

src/client/components/Sidebar/User.less
src/client/newRewards/ManageCampaingsTab/ManageCampaingsTab.less
src/client/object/ObjectGallery/GalleryAlbum.less
src/client/websites/WebsiteTools/Manage/ManageWebsite.less

fixed styles

---

src/client/object/AppendModal/AppendForm.js

fixed validation for menu item field

---

src/client/object/Options/OptionItem/OptionItemView.js
src/client/object/Options/Options.js
src/common/helpers/wObjectHelper.js

options fixes

---

src/client/object/AppendModal/AppendForm.js

trimmed all input values for object  fields

---

src/client/object/AppendModal/AppendForm.js

fixed remove fields validation

---

src/client/app/Sidebar/ObjectInfo.less
src/client/object/AppendModal/AppendForm.js

fixed trim errors + MENU ITEM

---

src/client/object/Options/Options-nightmode.less
src/client/object/Options/Options.less

options nightmode fixes

---

src/client/app/Sidebar/ObjectInfo.less

fixes for mobile buttons

---

src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/object/AppendModal/AppendForm.js
src/store/appendStore/appendActions.js

fixed pin updates

---

src/client/object/AppendModal/AppendForm.js

fixed page reload for pin update

---

src/client/components/Sidebar/ObjectsAddOn/ObjectsAddOn.js
src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js
src/client/components/Sidebar/ObjectsSimilar/ObjectsSimilar.js
src/common/helpers/wObjectHelper.js

added sorting for fields

---

src/client/app/Sidebar/ObjectInfo.js

authors sorting fixes, other authors fixes

---

src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/AuthorForm.js

removed added authors from search

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Description/DescriptionInfo.js

fields padding fixes

---

src/client/object/PicturesCarousel.less

added cursor pointer for pictures carousel

---

src/client/app/Sidebar/ObjectInfo.js

renamed feed section

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ProductId/GroupIdContent.js
src/client/app/Sidebar/ProductId/ProductId.js
src/client/object/GroupId/GroupIdPage.js
src/routes/components.js
src/routes/configs/routes.js
src/routes/configs/websitesRoutes.js
src/waivioApi/ApiClient.js
src/waivioApi/config.json

added group id search

---

src/client/app/Sidebar/ProductId/GroupIdContent.js
src/client/objectCard/ObjectCardView.less

group id fixes

---

src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js
src/client/object/RightSidebarPages/RelatedPage.js

fixed new fields related objects

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/WobjSearchPage/WobjSearchPage.js
src/routes/components.js
src/routes/configs/routes.js
src/routes/configs/websitesRoutes.js

added object search for merchant, brand, manufacturer

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/WobjSearchPage/WobjSearchPage.js
src/waivioApi/ApiClient.js

search fixes

---

src/client/object/RightSidebarPages/RelatedPage.js

reload related page fixes

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Description/DescriptionInfo.js

description button fixes

---

src/client/components/Navigation/GuestSignUpForm/GuestSignUpForm.less

fixed formatting of the registration screen of a new social account

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/ImageSetter/ImageSetter.js
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/ObjectFeaturesForm.js

some modal fixes

---

src/client/components/Navigation/GuestSignUpForm/GuestSignUpForm.less
src/client/components/Navigation/GuestSignUpForm/GuestSignUpFormContent.js

centered submit button for sign in guest account

---

src/client/object/Description/DescriptionInfo.js
src/client/object/Options/OptionItem/OptionItemView.js

mobile description and options show more buttons fixes

---

src/client/Shop/DepartmentsWobjList/DepartmentsWobjList.js
src/client/newRewards/DetailsModal/DetailsModal.js
src/client/rewards/Proposition/PropositionList/PropositionList.js
src/client/social-gifts/ShopObjectCard/ObjCardViewSwitcherForShop.js

fixed proposition cards

---

src/client/components/Story/StoryFull.js

fixed proposition card in post

---

src/client/app/Sidebar/ObjectInfo.js
src/client/app/Sidebar/ObjectInfo.less
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/MenuItemForm.js

modal fixes, author fixes

---

src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js

fixed related duplicates

---

src/client/object/AppendModal/FormComponents/MenuItemForm.js

added autoFocus for menuItem

---

src/client/object/Description/DescriptionPage.js

added  pictures lightbox for description page

---

src/client/object/Description/DescriptionPage.less

added cursor pointer for description page pictures

---

src/client/object/AppendModal/AppendForm.js

added autofocus for price

---

src/client/object/RightSidebarPages/WobjReferencePage.js
src/waivioApi/ApiClient.js

fixed reference type request

---

src/client/app/Sidebar/ObjectInfoExperts/ObjectInfoExperts.js
src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js
src/client/components/Sidebar/ObjectsSimilar/ObjectsSimilar.js
src/client/object/RightSidebarPages/RelatedPage.js

related similar fixes

---

src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js

fixed related objects permlink change

---

src/client/components/PostPopoverMenu/PostPopoverMenu.js

removed Pin and Remove from menu, in full post mode

---

src/client/components/ImageSetter/ImageSetter.js
src/client/components/ImageSetter/ImageSetter.less

added zoomout

---

src/client/components/Sidebar/ObjectCard.js
src/client/components/Sidebar/ObjectCard.less

removed expertise for objects

---

src/client/components/Sidebar/ObjectCard.less

long objects names fixes

---

src/client/components/Sidebar/ObjectCard.js
src/client/components/Sidebar/ObjectCard.less

Object card style fixes

---

src/client/components/Sidebar/ObjectCard.less

long object name fixes

---

src/client/notifications/Notifications.js

changed notification bot name and link

---

src/client/components/Sidebar/InterestingObjects.js
src/client/components/Sidebar/ObjectExpertise/ObjectExpertise.js

added expertise for user

---

src/client/settings/NotificationSettings.js

changed notification bot name and link in tools

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButtons-nightmode.less
src/client/app/Sidebar/MenuItemButtons/MenuItemButtons.js
src/client/app/Sidebar/MenuItemButtons/MenuItemButtons.less
src/client/app/Sidebar/ObjectInfoExperts/ObjectInfoExperts.js
src/client/components/Sidebar/ObjectCard.js
src/client/components/Sidebar/ObjectCard.less

returned full obj names for mobile

---

src/client/object/AppendModal/AppendForm.js

fixed gallery item validation

---

src/client/notifications/Notifications.js
src/client/settings/NotificationSettings.js

changed bot name

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/Story/StoryFull.js
src/client/components/StoryFooter/AppendObjButtons.js
src/client/components/StoryFooter/Buttons.less
src/client/object/AppendCard/ApprovingCard.js
src/client/object/ObjectGallery/Album.js
src/client/object/ObjectGallery/ObjectGalleryAlbum.js
src/client/object/PicturesCarousel.js
src/client/object/Wobj/WobjectContainer.js
src/client/widgets/LightboxTools/LightboxFooter.js
src/client/widgets/LightboxTools/LightboxHeader.js
src/client/widgets/LightboxTools/LightboxTools.less
src/common/locales/default.json

lightbox extension

---

src/client/components/ImageSetter/ImageSetter-nightmode.less
src/client/components/ImageSetter/ImageSetter.js

added avatar editor for clickboard picture

---

src/client/components/DataImport/ImportModal/ImportModal.js
src/common/locales/default.json

added new modal confirm

---

src/client/components/ImageSetter/ImageSetter.js

fixed rerender of editor

---

src/client/components/DataImport/ProductExtension/ProductExtension.js

product extension page fixes

---

src/client/components/DataImport/ProductExtension/ProductExtension.js
src/client/components/Navigation/MobileNavigation/MobileNavigation.js
src/common/locales/default.json

added breadcrumbs for product extension page

---

src/client/app/Sidebar/ObjectInfo.js
src/client/widgets/LightboxTools/LightboxTools.less

added all photos to gallery

---

src/client/components/DataImport/ProductExtension/ProductExtension.js

fixes Datafiniti's

---

src/client/social-gifts/Wrapper.js

fixed sites header

---

src/client/websites/WebsiteTools/Configuration/ConfigPages/WebsitesConfigurations.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/WebsitesConfigurations.less

fixed avatar preview for site configuration

---

src/client/social-gifts/Header/Header.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/ShopWebsiteConfigurations.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/WebsitesConfigurations.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/WebsitesConfigurations.less

added editor for websites configuration, fixed avatar config style

---

src/client/app/Sidebar/ObjectInfo.js
src/client/object/Wobj/WobjectContainer.js

fixed avatar lightbox and gallery preview

---

src/client/components/DataImport/ImportModal/ImportModal.js
src/waivioApi/importApi.js

fixed force import modal

---

src/client/components/ImageSetter/ImageSetter.js
src/client/social-gifts/Header/Header.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/ShopWebsiteConfigurations.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/WebsitesConfigurations.js

avatar fixes for sites config

---

src/client/components/DataImport/ImportModal/ImportModal.js

fixed empty error field

---

src/client/components/DataImport/ChromeExtension/ChromeExtension.js

fix features name, remove line with date (Chrome extension page)

---

src/client/wallet/TransfersCards/PowerUpTransactionFrom.js

fixed hive wallet power up card

---

src/client/object/Catalog/CatalogWrap.js

fixed hearts for list

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js
src/client/object/AppendModal/AppendForm.js
src/client/object/ObjectFeed/ObjectFeed.js
src/client/object/WidgetPage/WidgetPage.js
src/client/social-gifts/routes.js
src/routes/configs/routes.js

menu item link fixes

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js
src/client/object/ObjectFeed/ObjectFeed.js
src/routes/configs/routes.js

refactored code

---

src/client/components/DataImport/ChromeExtension/ChromeExtension.js
src/routes/switchRoutes.js
src/waivioApi/ApiClient.js

added version and paragraph for extension page

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/ObjectLightbox.js

added all pictures to avatar lightbox,added avatar to pictures carousel

---

src/client/app/Sidebar/ProductId/ProductId.js
src/client/components/HeaderButton/HeaderButton.js
src/client/object/PicturesCarousel.less
src/client/social-gifts/SocialProduct/SocialProduct.js
src/client/social-gifts/Wrapper.js
src/routes/switchRoutes.js

added tag categories

---

src/client/object/Description/DescriptionPage.js
src/client/object/PicturesCarousel.less

added cursor pointer, added header and footer to lightbox

---

src/client/object/Wobj/WobjectContainer.js

show description if there are no posts

---

src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/FormComponents/MenuItemForm.js
src/client/object/const/appendFormConstants.js

fixed menu item modal

---

src/client/components/Sidebar/ObjectCard.js
src/client/object/Options/OptionItem/OptionItemView.js
src/client/object/Wobj/WobjectContainer.js

added description page links to options and right sidebar items

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js
src/client/app/Sidebar/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js

added changed title for menu items

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js
src/client/app/Sidebar/ObjectInfo.js

fixed menuItems buttons

---

src/common/helpers/wObjectHelper.js

show description page fixes

---

src/client/widgets/LightboxTools/LightboxFooter.js
src/client/widgets/LightboxTools/LightboxTools.less

added white background for lightbox

---

src/client/social-gifts/SocialProduct/PicturesSlider/PicturesSlider.js
src/client/social-gifts/SocialProduct/SocialProduct.js
src/client/social-gifts/SocialProduct/SocialProduct.less
src/routes/switchRoutes.js

fixed price space

---

src/client/object/Wobj/WobjectContainer.js
src/client/object/WobjHero.js
src/routes/configs/routes.js

fixed reviews redirect

---

src/client/components/ObjectLightbox.js
src/client/styles/styles-shortcodes.less

avatar arrow fixes

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/components/Sidebar/ObjectsAddOn/ObjectsAddOn.js
src/client/newRewards/DetailsModal/DetailsModal.js
src/client/social-gifts/Breadcrumbs/Breadcrumbs.js
src/client/social-gifts/SocialProduct/SocialProduct.js
src/waivioApi/ApiClient.js

fixed getObjectInfo request, added locale

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js
src/client/object/ObjectFeed/ObjectFeed.js
src/client/object/Wobj/Wobj.js
src/routes/configs/routes.js

newsfeed and page fixes

---

src/client/app/Sidebar/ObjectInfo.js

fixed locale for wobj

---

src/client/social-gifts/routes.js
src/routes/configs/websitesRoutes.js

added /reviews page  for DG and SG

---

src/client/object/Description/DescriptionPage.js

mixed description paragraphs with pictures

---

src/client/object/Description/DescriptionPage.js

fixed front crash on description page

---

src/client/social-gifts/SocialProduct/SocialProduct.less

fixed aff links margin

---

src/client/components/ObjectLightbox.js
src/client/object/Description/DescriptionPage.js
src/client/object/PicturesCarousel.js
src/client/social-gifts/SocialProduct/SocialProduct.js

fixed avatar arrows

---

src/client/object/Description/DescriptionPage.js

description page fixes

---

src/client/social-gifts/ShopObjectCard/ShopObjectCard.less

affiliate links mobile fixes

---

src/client/newRewards/ManageCampaingsTab/Manage.js
src/common/locales/de-DE.json
src/common/locales/default.json
src/common/locales/ru-RU.json

add translation shop note in settings, and for campaign manage tab

---

src/client/newRewards/ManageCampaingsTab/Manage.js
src/common/locales/de-DE.json
src/common/locales/default.json
src/common/locales/ru-RU.json

add translation for earn manage tab

---

src/client/components/AvatarLightbox.js

lightbox background fixes for user avatar

---

src/client/components/DataImport/ChromeExtension/ChromeExtension.js
src/common/locales/default.json

correct chatgpt word for chrome extension

---

src/client/components/EditorExtended/components/sides/ImageButtonSlate.js
src/client/components/EditorExtended/components/sides/ImageSideButton.js
src/client/components/ImageSetter/ImageSetter.js
src/client/components/ImageSetter/ImageSetterEditor.js
src/client/components/ImageSetter/ImageSetterSlate.js

added image crop for editor photos

---

src/client/app/Sidebar/ObjectInfo.js
src/client/components/Proposition/Proposition.js
src/client/object/AppendModal/AppendForm.js
src/client/object/WobjHistory/UpdateHistory.js
src/client/object/WobjHistory/WobjHistory.js
src/common/helpers/wObjectHelper.js
src/common/locales/default.json

fixes list updates

---

src/client/components/EditorExtended/components/sides/ImageButtonSlate.js
src/client/components/ImageSetter/ImageSetterSlate.js

fixes for editor image crop

---

src/client/social-gifts/Breadcrumbs/Breadcrumbs.js

shortened social product breadcrumbs

---

src/client/components/EditorExtended/components/sides/ImageButtonSlate.js
src/client/components/ImageSetter/ImageSetterSlate.js

fixed ok button disable

---

src/client/components/ImageSetter/ImageSetterSlate.js

added autofocus

---

src/client/object/AppendCard/AppendCard.js
src/client/object/WobjHistory/WobjHistory.js

fixes list

---

src/client/object/WobjHistory/WobjHistory.js

list updates modals fixes

---

src/client/social-gifts/Header/TopNavigation/WebsiteTopNavigation.js

add translation for word more in site header

---

src/client/object/WobjHistory/WobjHistory.js

fixed current field change

---

src/client/components/ObjectLightbox.js

The wrong image is opened, if you click on the avatar

---

src/client/components/EditorExtended/components/sides/ImageButtonSlate.js
src/client/components/ImageSetter/ImageSetterSlate.js

removed editor picture crop

---

src/client/social-gifts/SocialProduct/PicturesSlider/PicturesSlider.js
src/client/social-gifts/SocialProduct/SocialBookAuthors/SocialBookAuthors.js
src/client/social-gifts/SocialProduct/SocialProductDescription/SocialProductDescription.js
src/client/social-gifts/SocialProduct/SocialProductDescription/SocialProductDescription.less
src/client/social-gifts/SocialProduct/SocialProductReviews/SocialProductReviews.less

carousel fixes, styles fixes, mobile reviews fixes, lightbox

---

src/client/object/Description/DescriptionPage.js
src/client/object/Wobj/WobjectContainer.js

fixed duplicated description pictures

---

src/client/app/Sidebar/ObjectInfo/ObjectInfo.js
src/client/app/Sidebar/ObjectInfo/ObjectInfoComponents/AffiliateSection.js
src/client/object/AppendModal/FormComponents/AffiliateCodeForm.js
src/client/social-gifts/Checklist/Checklist.js
src/client/social-gifts/SocialProduct/SocialProduct.js
src/routes/switchRoutes.js

sg helmet fixes, aff links fixes

---

src/client/widgets/AffiliatLinks/AffiliatLink.js
src/client/widgets/AffiliatLinks/AffiliatLink.less

added new aff icons

---

src/client/Shop/ShopList/ShopList.js
src/client/social-gifts/Checklist/Checklist.js
src/client/social-gifts/FeedMasonry/FeedMasonry.js
src/client/social-gifts/FeedMasonry/ObjectNewsFeed.js
src/client/social-gifts/SocialProduct/SocialProduct.js
src/client/social-gifts/SocialProduct/SocialProductReviews/SocialProductReviews.js
src/routes/switchRoutes.js

helmet fixes

---

src/client/app/Sidebar/ObjectInfo/ObjectInfoComponents/AffiliateSection.js
src/client/app/Sidebar/ObjectInfo/ObjectInfoComponents/AffiliateSection.less
src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/AppendModalData/affiliateData.js
src/client/object/AppendModal/FormComponents/AffiliateGeoAreaForm.js
src/routes/switchRoutes.js

affiliate icon fixes, geo area fixes

---

src/client/components/DnDList/DnDList.js
src/client/object/AppendModal/AppendForm.js

fixed menu items title for sorting

---

src/client/app/Sidebar/ObjectInfo/ObjectInfo.less
src/client/objectCard/ObjectCardView.less

aff links border color change

---

src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.less

affiliate codes for websites fixes

---

src/client/components/Navigation/SettingsSidenav/constants.js
src/client/components/Navigation/TopNavigation.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.js
src/routes/configs/routes.js
src/routes/constants.js

aff codes for sites fixes

---

src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.js

space fixes

---

src/client/components/Navigation/SettingsSidenav/constants.js
src/client/settings/WebsiteSettings.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodesModal.js
src/client/websites/WebsiteTools/AffiliateCodes/UserAffiliateCodes.js
src/client/websites/WebsiteTools/AffiliateCodes/affiliateCodesHelper.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/ShopWebsiteConfigurations.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/WebsitesConfigurations.js
src/client/websites/WebsiteTools/Settings/WebsitesSettings.js

user affiliate codes fixes

---

src/client/app/Sidebar/ObjectInfo/ObjectInfoComponents/AffiliateSection.less
src/client/widgets/AffiliatLinks/AffiliatLink.less

affiliate icons fixes

---

src/client/components/Tools/DynamicTable/DynamicTable.js

added links to websites in manage table

---

src/client/app/Sidebar/ProductId/ProductId.js
src/client/social-gifts/DepatmentsSearch/DepatmentsSearch.js
src/routes/switchRoutes.js

departments search fixes

---

src/client/components/Tools/DynamicTable/DynamicTable.js
src/client/websites/constants/tableConfig.js

added type for head config (manage websites)

---

src/client/app/Sidebar/ObjectInfo/ObjectInfo.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/social-gifts/SocialProduct/ProductDetails/ProductDetails.js
src/client/social-gifts/SocialProduct/SocialBookAuthors/SocialBookAuthors.js
src/client/social-gifts/SocialProduct/SocialListItem/SocialListItem.js
src/client/social-gifts/SocialProduct/SocialProduct.js
src/routes/switchRoutes.js

authors and publisher search fixes, added website field for product page

---

src/client/components/Tools/DynamicTable/DynamicTable.js

added condition for active sites

---

src/client/objectCard/RatingsWrap/RatingsWrap.js
src/client/social-gifts/SocialProduct/SocialProduct.less

ratings on social product cards fixes

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js

notifications translations fixes

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js
src/common/locales/default.json

notifications text fixes

---

src/client/components/ClaimAthorityBot/ClaimAthorityBot.js
src/client/components/DataImport/DataImport.js
src/waivioApi/importApi.js

added skip limit for authority bot and data import

---

src/client/post/CreateObjectModal/CreateObject.js
src/common/locales/default.json

create new object modal fixes

---

src/common/constants/ssrData.js
src/server/handlers/cachePageHandler.js
src/server/handlers/createSsrHandler.js
src/server/redis/operations.js
src/server/redis/redis.js

cache for seo3

---

src/client/post/CreateObjectModal/CreateObject.js
src/client/post/CreateObjectModal/CreateObject.less

labels fixes

---

src/client/post/CreateObjectModal/CreateObject.js
src/client/post/CreateObjectModal/CreateObject.less

labes fixes

---

src/common/locales/default.json

changed label text

---

src/client/styles/common.less

fixed disabled checkbox style

---

src/client/websites/WebsiteLayoutComponents/Header/GeneralSearch/GeneralSearch.js
src/routes/switchRoutes.js

hide search values fix

---

src/client/social-gifts/SocialProduct/SocialProduct.js
src/routes/switchRoutes.js

social product name, product details fixes

---

src/client/social-gifts/DepatmentsSearch/DepartmentsSearch.less
src/client/social-gifts/DepatmentsSearch/DepatmentsSearch.js
src/routes/switchRoutes.js

increased size of tags in departments search

---

src/common/helpers/postHelpers.js
src/common/helpers/regexHelpers.js

fixed original post page

---

src/client/post/CreateObjectModal/CreateObject.js
src/client/post/CreateObjectModal/CreateObject.less

errors text fixes

---

src/waivioApi/importApi.js

added error for authority bot if there is not enough vote power

---

src/client/social-gifts/NewDiscover/NewDiscover.less

increased size of tags in discover search

---

src/server/handlers/createSsrHandler.js

cache commented

---

src/client/social-gifts/NewDiscover/NewDiscover.js

fixed heart button active when reload search page

---

src/client/object/GroupId/GroupIdPage.js
src/server/handlers/createSsrHandler.js

fixes loadMore request if hasMore false for groupId

---

src/client/social-gifts/DepatmentsSearch/DepartmentsSearch.less
src/client/social-gifts/NewDiscover/NewDiscover.less

increased tag size for search

---

src/client/components/UserMenu.js
src/client/object/GroupId/GroupIdPage.js
src/client/social-gifts/routes.js
src/routes/switchRoutes.js

added shop for user menu for social websites

---

src/client/social-gifts/routes.js

added affiliate codes for user setting social websites

---

src/client/social-gifts/DepatmentsSearch/DepartmentsSearch.less
src/client/social-gifts/NewDiscover/NewDiscover.less
src/routes/switchRoutes.js

added font weight

---

src/client/object/Department/DepartmentList.js
src/client/object/Wobj/WobjectContainer.js

fixed updates page reload

---

src/client/wallet/Withdraw/WithDraw.js

HIVE withdrawal fixes

---

src/client/components/EditorObject/SearchObjectsAutocomplete.js
src/client/components/Navigation/MobileNavigation/MobileNavigation.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodesAutoComplete.js
src/common/locales/default.json
src/store/searchStore/searchActions.js
src/waivioApi/ApiClient.js
src/waivioApi/config.json

added search objects default request for affiliate codes pages

---

src/client/social-gifts/Header/TopNavigation/BurgerMenu/BurgerMenu.js
src/client/social-gifts/Header/TopNavigation/BurgerMenu/BurgerMenu.less
src/client/social-gifts/Header/TopNavigation/WebsiteTopNavigation.js
src/routes/switchRoutes.js

added burger menu for website top navigation

---

src/client/components/DataImport/VoteInfoBlock.js
src/client/components/DataImport/tableConfig.js
src/client/components/DepartmentsBot/DepartmentsBot.js
src/common/locales/default.json

departments bot objects number fixes

---

src/client/components/DataImport/DataImport.less
src/client/newRewards/reuseble/Proposition/Proposition-nightmode.less
src/client/social-gifts/Header/TopNavigation/BurgerMenu/BurgerMenu.js
src/client/social-gifts/Header/TopNavigation/BurgerMenu/BurgerMenu.less

burger menu fixes

---

public/images/icons/twitter-x.svg
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/components/PostPopoverMenu/PostPopoverMenu.less

changed twitter icon

---

src/client/search/SearchItems/UserSearchItem.js
src/client/websites/WebsiteTools/Configuration/BaseObjSettings/BaseObjSettings.js
src/client/websites/WebsiteTools/Configuration/ConfigPages/ShopWebsiteConfigurations.js

removed following status for search base object

---

src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/components/PostPopoverMenu/PostPopoverMenu.less
src/client/post/PostModal.js
src/client/post/PostModal.less

fixes for twitter icon

---

src/client/components/ClaimAthorityBot/ClaimAthorityBot.js
src/client/components/DataImport/DataImport.js
src/common/locales/default.json

fixed disclaimer text for data import and claim authority bots

---

src/client/websites/WebsiteTools/Settings/WebsitesSettings.js

added semicolon for h3 text

---

src/client/components/ClaimAthorityBot/ClaimAthorityBot.js
src/client/components/Navigation/SettingsSidenav/constants.js
src/common/locales/default.json

claim authority fix

---

src/client/websites/WebsiteTools/AdSenseAds/AdSenseAds.js

adsense setting page fixes

---

src/client/websites/WebsiteTools/AdSenseAds/AdSenseAds.js

enabled save button if adsense is empty

---

src/client/components/Comments/CommentForm.js
src/client/components/EditorExtended/components/addbutton.less

comments editor video and code fix

---

src/client/components/EditorExtended/components/sides/VideoButtonSlate.js

added autofocus for video

---

src/client/social-gifts/SocialProduct/SocialProduct.js
src/store/shopStore/shopReducer.js

product page scroll fix

---

src/client/user/UserBlog/UserBlog.js

fixed filter change scroll

---

src/common/helpers/image.js

fixed proxy img url

---

src/client/websites/WebsiteTools/AdSenseAds/AdSenseAds.js

fixed level change

---

src/client/components/EditorExtended/components/addbutton.less

enter button fix on mobile

---

src/client/websites/WebsiteSignIn/SocialSingInModalContent/SocialSignInModalContent.js
src/client/websites/WebsiteSignIn/WebsiteSignIn.js
src/routes/switchRoutes.js

fixes for sign in modal

---

src/client/websites/WebsiteTools/AdSenseAds/AdSenseAds.js
src/client/websites/WebsiteTools/AdSenseAds/AdSenseAds.less

added adsense validation

---

src/client/websites/WebsiteSignIn/WebsiteSignIn.js

changed site name for link

---

src/client/websites/WebsiteSignIn/SocialSingInModalContent/SocialSignInModalContent.js

fixed sign in links

---

src/client/object/Wobj/WobjectContainer.js

description page fix

---

src/client/social-gifts/Header/Header.js
src/client/styles/common.less
src/client/user/UserHeader/UserHeader.less
src/client/wallet/Transfer/Transfer.less
src/client/websites/WebsiteLayoutComponents/Header/GeneralSearch/GeneralSearch.less

selection style fix

---

src/client/components/PolicyConfirmation/PolicyConfirmation.less
src/client/post/PostPreviewModal/PostPreviewModal.less
src/client/styles/common.less

buttons style and checkbox style fixes

---

src/client/rewards/Proposition/WebsiteReservedButtons/ReservedButtons.js
src/client/social-gifts/FeedMasonry/FeedItem.js
src/client/websites/WebsiteLayoutComponents/Header/GeneralSearch/GeneralSearch.js
src/routes/switchRoutes.js

added new events for google analytics

---

src/client/components/Story/Story.js

added new event for post view

---

src/client/social-gifts/Checklist/CheckListView.js
src/client/social-gifts/ListDescription/ListDescription.less
src/routes/switchRoutes.js

added transition for description list element

---

src/client/social-gifts/ListDescription/ListDescription.less

fixed style for mobile list description

---

src/client/app/Sidebar/MenuItemButtons/MenuItemButton.js

added menu item webpage as nested wobj

---

src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.less

 webpage menu item fix, style fixes

---

src/client/social-gifts/Checklist/CheckListView.js
src/client/social-gifts/ListDescription/ListDescription.js
src/client/social-gifts/ListDescription/ListDescription.less
src/routes/switchRoutes.js

title and description fix for social website lists

---

src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.less

ready to publish button fix

---

src/client/object/AppendModal/AppendForm.js
src/client/object/AppendModal/AppendModal.js
src/client/object/ObjectOfTypeWebpage/AppendWebpageModal.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.js

fixed edit for nested obj of type webpage

---

src/client/wallet/SwapTokens/SwapTokens.less
src/client/wallet/WithdrawModal/WithdrawModal.less

fixed focused inputs styles for withdraw and swap modals

---

src/client/social-gifts/ListDescription/ListDescription.js
src/client/social-gifts/ListDescription/ListDescription.less

changed style for title and description for lists

---

src/client/social-gifts/ListDescription/ListDescription.less

changed title color

---

src/client/object/ObjectOfTypeWebpage/AppendWebpageModal.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.js
src/common/helpers/postHelpers.js
src/common/locales/default.json

fixed locale for webpage update

---

src/client/social-gifts/ListDescription/ListDescription.less

fixed title for mobile

---

src/common/helpers/postHelpers.js

fixed update card for webpage with no image

---

src/client/components/Comments/CommentForm.js
src/server/app.js
src/server/seo-service/seoServiceApi.js

5593 sitemap

---

src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodesModal.js
src/client/websites/WebsiteTools/AffiliateCodes/UserAffiliateCodes.js

fixed affiliate weight percent

---

src/store/searchStore/searchActions.js

increased affiliate code search limit

---

src/client/Shop/ShopDepartments/DepartmentsUser.js
src/client/Shop/ShopFilters/UserFilters.js
src/client/Shop/ShopList/UserShoppingList.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.js
src/client/object/ObjectTypeShop/DepartmentsWobject.js
src/client/object/ObjectTypeShop/WobjectShopFilter.js
src/client/object/ObjectTypeShop/WobjectShoppingList.js
src/client/object/Wobj/Wobj.js
src/client/object/Wobj/WobjectContainer.js
src/client/social-gifts/Checklist/CheckListView.js
src/client/social-gifts/Header/TopNavigation/LinkItem.js
src/client/social-gifts/Header/TopNavigation/WebsiteTopNavigation.js
src/client/social-gifts/ShopMainForWobject/ShopMainForWobject.js
src/client/social-gifts/ShopSwitcher/ShopSwitcher.js
src/client/social-gifts/Wrapper.js

show main page without redirect

---

src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodesModal.js
src/store/searchStore/searchActions.js

changed upvote power

---

src/client/components/ObjectLightbox.js
src/client/components/Story/StoryFull.js
src/client/object/ObjectGallery/ObjectGalleryAlbum.js
src/client/widgets/LightboxTools/LightboxHeader.js
src/client/widgets/LightboxTools/LightboxTools.less
src/client/widgets/LightboxTools/LightboxWithAppendForm.js

gallery fixes

---

src/client/social-gifts/ListDescription/ListDescription.js
src/client/social-gifts/ListDescription/ListDescription.less

fixed long list description

---

src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodes.js
src/client/websites/WebsiteTools/AffiliateCodes/AffiliateCodesModal.js
src/client/websites/WebsiteTools/AffiliateCodes/UserAffiliateCodes.js
src/client/websites/WebsiteTools/Manage/ManageWebsite.js
src/store/appendStore/appendActions.js

fixed user and site aff codes

---

src/client/object/AppendModal/AppendForm.js

status field change for relisted status

---

src/client/components/SearchDepartmentAutocomplete/SearchDepartmentAutocomplete.js
src/client/post/PostPreviewModal/BeneficiariesFindUsers.js
src/client/websites/WebsiteTools/Configuration/BaseObjSettings/BaseObjSettings.js

search limit fix

---

src/client/components/Avatar.js
src/client/components/AvatarLightbox.js

avatar picture fix for users with no avatar

---

src/client/websites/WebsiteTools/WebsitePricing/WebsitePricing.less

website pricing mobile style fix

---

src/client/components/ImageSetter/ImageSetter.js
src/client/components/ImageSetter/ImageSetterSlate.js
src/common/constants/validation.js

added heic image types

---

src/client/object/Catalog/CatalogBreadcrumb/CatalogBreadcrumb.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.js
src/client/object/ObjectOfTypeWebpage/ObjectOfTypeWebpage.less
src/client/object/WidgetPage/WidgetPage.js

added breadcrumbs for webpage and widget

---

src/client/object/ObjectFeed/index.js

newsfeed breadcrumbs fix for nested objects

---

src/client/components/DataImport/DuplicateList/DuplicateList.js
src/client/components/DataImport/DuplicateList/FindListModal.js
src/client/components/Navigation/SettingsSidenav/constants.js

fix text from duplicator to duplication

---

src/client/discover/Discover.js
src/client/discover/DiscoverContent.js
src/client/object/ObjectDynamicList.js
src/client/user/UserDynamicList.js
src/client/user/UserFollowers.js
src/client/user/UserFollowing.js

fixed users lists

---

src/common/constants/listOfObjectTypes.js

list of object types fix

---

package.json
src/server/app.js
src/server/handlers/createSsrHandler.js
src/server/seo-service/seoServiceApi.js

seo service

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js
src/common/constants/notifications.js
src/common/locales/default.json

added threads notifications for object

---

src/client/Threads/Threads.js
src/client/Threads/ThreadsEditor/ThreadsEditor.js
src/client/components/EditorExtended/ThreadsEditorSlate.js
src/client/components/EditorExtended/util/SlateEditor/utils/parse.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/components/Story/Story.js
src/client/components/StoryFooter/Buttons.js
src/client/components/StoryFooter/StoryFooter.js
src/client/feed/StoryContainer.js
src/client/user/PostsCommentsActivity/PostsCommentsActivity.js
src/store/feedStore/feedActions.js
src/waivioApi/ApiClient.js

threads fixes

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js

threads notifications fix

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js
src/common/helpers/notificationsHelper.js
src/store/commentsStore/commentsActions.js

mention notifications fix

---

src/client/Threads/Threads.js
src/client/Threads/ThreadsEditor/ThreadsEditor.js
src/client/components/Story/PostedFrom.js
src/client/components/Story/Story.js
src/client/object/ObjectReviewsAndThreads/ObjectReviewsAndThreads.js
src/client/post/PostModalContainer.js
src/client/user/PostsCommentsActivity/PostsCommentsActivity.js
src/store/commentsStore/commentsActions.js
src/store/postsStore/postActions.js

threads fixes for modal and like

---

src/client/components/Navigation/Notifications/Notifications.js
src/client/notifications/Notifications.js

notidications reply fix

---

src/client/components/Sidebar/ObjectWeightBlock.js
src/client/object/ObjectDynamicList.js
src/client/user/UserExpertise.js
src/waivioApi/ApiClient.js

fixed hashtags expertise

---

src/client/Threads/ThreadsEditor/ThreadsEditor.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/components/StoryFooter/Buttons.js
src/common/locales/default.json
src/store/commentsStore/commentsActions.js

threads fix

---

src/client/object/Wobj/WobjectContainer.js
src/client/social-gifts/SocialProduct/SocialMenuItems/SocialMenuItems.js
src/routes/switchRoutes.js

menu items sorting fix

---

src/client/app/Sidebar/ObjectInfo/ObjectInfo.js
src/client/object/AppendModal/AppendForm.js

publication date test fix

---

src/client/components/DataImport/DuplicateList/DuplicateList.js
src/common/locales/default.json

fix list duplication pause key

---

src/client/object/Catalog/CatalogWrap.js

fixed list loader

---

src/client/components/Icon/Loading.less
src/client/social-gifts/Wrapper.js

social sites loader test fix

---

src/store/authStore/authActions.js

auth error fix

---

src/client/vendor/SanitizeConfig.js

page links fix

---

package.json
src/server/handlers/cachePageHandler.js

add s3 client

---

src/client/social-gifts/Header/Header.js

add space for alt logo image on social site

---

src/client/websites/WebsiteTools/Settings/WebsitesSettings.js
src/common/locales/default.json

fix text for config text in settings

---

src/client/components/Story/Body.less
src/client/vendor/steemitHtmlReady.js

fixed modal text for threads

---

src/client/Shop/DepartmentsWobjList/DepartmentsWobjList.js
src/client/WebsiteWrapper.js
src/client/Wrapper.js
src/client/components/Comments/Comment.js
src/client/components/EditorExtended/components/LinkEditComponent.js
src/client/components/EditorExtended/components/toolbar.js
src/client/components/Maps/Map.js
src/client/components/Maps/MapObjectInfo.js
src/client/components/Sidebar/PostRecommendation.js
src/client/components/Story/Body.js
src/client/components/Story/StoryFull.js
src/client/components/Utils/Affix.js
src/client/index.js
src/client/object/Description/DescriptionPage.js
src/client/object/Options/Options.js
src/client/post/Post.js
src/client/post/PostContent.js
src/client/post/PostModal.js
src/client/post/PostPreviewModal/PostPreviewModal.js
src/client/rewards/QiuckRewardsModal/components/FirstScreen/FirstScreen.js
src/client/rewards/ReferralProgram/ReferralHelper.js
src/client/social-gifts/Wrapper.js
src/client/vendor/ReduxInfiniteScroll.js
src/client/vendor/steemitHtmlReady.js
src/client/websites/WebsiteLayoutComponents/Header/GeneralSearch/GeneralSearch.js
src/client/websites/WebsiteSignIn/WebsiteSignIn.js

fixed type of document

---

package.json
src/server/handlers/createSsrHandler.js
src/server/middleware/botRateLimit.js
src/server/redis/redisClient.js

google-whitelist

---

src/server/middleware/botRateLimit.js

production rate-limit

---

src/client/Shop/DepartmentsWobjList/DepartmentsWobjList.js
src/client/auth/withAuthActions.js
src/client/components/PostPopoverMenu/PostPopoverMenu.js
src/client/index.js
src/client/object/Wobj/Wobj.js
src/client/post/PostContent.js
src/client/post/PostModal.js
src/client/post/PostPreviewModal/PostPreviewModal.js
src/client/routes.js
src/client/social-gifts/Checklist/Checklist.js
src/client/social-gifts/FeedMasonry/ObjectNewsFeed.js
src/client/social-gifts/PageContent/PageContent.js
src/client/social-gifts/SocialProduct/SocialProduct.js
src/client/social-gifts/WidgetContent/WidgetContent.js
src/client/websites/WebsiteLayoutComponents/Header/GeneralSearch/GeneralSearch.js
src/store/appendStore/appendActions.js
src/store/authStore/authActions.js
src/store/commentsStore/commentsActions.js
src/store/editorStore/editorActions.js
src/store/postsStore/postActions.js
src/store/reblogStore/reblogActions.js
src/store/slateEditorStore/editorActions.js

window type fix

---

src/client/AppHost.js
src/client/HiveAuth/hive-auth-wrapper.js
src/client/WebsiteWrapper.js
src/client/Wrapper.js
src/client/object/Wobj/Wobj.js
src/client/object/Wobj/WobjectContainer.js
src/client/social-gifts/BusinessObject/BusinessObject.js
src/client/social-gifts/Wrapper.js
src/client/vendor/SanitizeConfig.js

fixed issues

---

src/client/components/DataImport/VoteInfoBlock.js
src/client/rewards/MatchBots/MatchBotsService/MatchBotsService.js
src/store/authStore/authActions.js
src/waivioApi/importApi.js

guest bots fix

---

src/client/components/Navigation/redirectedSignIn/RedirectedSignIn.js
src/client/websites/WebsiteSignIn/SocialSingInModalContent/SocialSignInModalContent.js
src/client/websites/WebsiteSignIn/WebsiteSignIn.js
src/client/websites/WebsiteSignIn/styles.js

Bugfix sign in

---

src/client/components/Navigation/SettingsSidenav/SettingsSidenav.js
src/client/settings/SettingsMain.js
src/client/steemConnectAPI.js
src/client/wallet/Transfer/Transfer.js
src/client/websites/WebsiteTools/Manage/ManageWebsite.js
src/client/websites/WebsiteTools/Restrictions/WebsiteRestrictions.js
src/store/websiteStore/websiteActions.js
src/waivioApi/ApiClient.js

added website creation for guests

---

src/common/helpers/redirectHelper.js

6363_redirect

---

src/client/social-gifts/ShopObjectCard/ShopObjectCard.js
src/common/locales/es-ES.json

add space and es translation

---

src/client/components/Maps/Overlays/ObjectOverlayCard/ObjectOverlayCard.js
src/client/object/ObjectOfTypeMap/ObjectOfTypeMap.js

requests number fix

---

src/client/object/Options/OptionItem/OptionItemView.js
src/client/object/Wobj/Wobj.js
src/client/social-gifts/ShopObjectCard/ShopObjectCard.js
src/client/social-gifts/Wrapper.js
src/client/websites/WebsiteLayoutComponents/Header/GeneralSearch/GeneralSearch.js
src/client/websites/WebsiteTools/Configuration/BaseObjSettings/BaseObjSettings.js
src/common/constants/listOfObjectTypes.js

added link view for social sites

---

src/client/app/Sidebar/WalletAddress/WalletAddressItem.js
src/client/object/AppendModal/FormComponents/WalletAddressForm.js

fixed wallet address symbol

---

src/client/object/ObjectOfTypeMap/ObjectOfTypeMap.js

fixed nested map selected obj

---

src/client/components/UserMenu.js
src/client/social-gifts/routes.js
src/client/user/User.js
src/client/websites/MainMap/MainMap.js
src/client/websites/MainMap/MainMapView.js
src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js
src/common/constants/listOfObjectTypes.js
src/routes/configs/routes.js
src/routes/constants.js
src/routes/switchRoutes.js
src/waivioApi/ApiClient.js

fixed map load and refactored map

---

src/client/post/PostContent.js

seo fix for recipe post

---

src/client/social-gifts/BusinessObject/BusinessMenuItems/BusinessMenuItem.js

fixed menu items links page not found

---

src/client/components/Maps/mapHelpers.js

add one more place type
