src/client/adaptors.js, src/client/components/Editor/Editor.js, src/client/components/EditorObject/EditorObject.js, src/client/components/EditorObject/EditorObject.less, src/client/components/EditorObject/SearchObjectsAutocomplete.js, src/client/locales/default.json, src/client/reducers.js, src/client/search/searchActions.js, src/client/search/searchReducer.js, webpack/configUtils.js
possibility to attach objects to post
=> Linked objects for create-post

src/client/components/ObjectHeader.less, src/client/object/WobjHeader.js
=> edited object page header on mobile

src/client/rewards/Create/CreateRewardForm.js, src/client/rewards/Create/TargetDaysTable/TargetDaysTable.js
=> added sending target days on api

src/client/feed/feedActions.js, src/waivioApi/ApiClient.js
=> Added user_name to getMoreContentbyObjects request to localize feed

src/client/components/EditorObject/FormattedLink.js, src/client/locales/default.json
=> Object comment validation fix

src/client/components/ObjectHeader.less
=> edited styles on object header

src/client/locales/default.json, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js
=> Rewards prevalidation

src/client/adapters.js, src/client/app/Sidebar/ObjectInfo.js, src/client/object/Wobj.js, src/client/object/WobjHeader.js, src/client/object/__tests__/wObjectHelper.js, src/client/object/const/defaultValues.js, src/client/object/wObjectHelper.js, src/client/object/wobjectReducer.js, src/client/object/wobjectsActions.js, src/common/constants/listOfFields.js
=> Fields with locales

src/client/components/Sidebar/SidebarMenu/SidebarMenu.js, src/client/feed/feedActions.js, src/client/helpers/apiHelpers.js
=> Feed requests changing

src/client/components/EditorObject/FormattedLink.js, src/client/locales/default.json, src/client/rewards/Create/TargetDaysTable/TargetDaysTable.js, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTable.js, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTableBodyRow.js, src/client/rewards/Manage/Manage.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js, src/client/user/userActions.js, src/waivioApi/ApiClient.js, src/waivioApi/config.json
=> Deactivate campaign

src/client/app/Sidebar/ObjectInfo.js, src/client/object/AppendForm.js, src/client/object/wObjectHelper.js, src/client/object/wobjectReducer.js
=> Object menu/list - adding items

src/client/rewards/Proposition/Proposition.js
=> edited getting comments by user

src/client/components/Sidebar/ObjectExpertiseByType/ObjectExpertiseByType.js, src/client/components/Sidebar/__tests__/ObjectExpertiseByType.test.js
=> Fixed tests

src/client/components/ObjectLightbox.js, src/client/components/Proposition/Proposition.js, src/client/object/AppendForm.js, src/client/object/AppendModal.js, src/client/object/Catalog/AddItemModal/AddItemModal.js, src/client/object/Catalog/CatalogWrap-nightmode.less, src/client/object/Catalog/CatalogWrap.less, src/client/object/WobjHistory.js, src/client/post/CreateObjectModal/CreateObject.js, src/client/reducers.js
=> Object list issue

src/client/locales/default.json, src/client/locales/ru-RU.json
=> edited translate

src/client/rewards/Rewards.js
=> Big fix campaign reservation button

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTable.less, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTableBodyRow.js, src/client/rewards/Manage/CampaignRewardsTable/CampaingRewardsTable-nigthmode.less, src/client/rewards/Payment/PaymentTable/PaymentTable-nightmode.less, src/client/rewards/Payment/PaymentTable/PaymentTable.less, src/client/rewards/PaymentCard/PaymentCard-nightmode.less, src/client/rewards/PaymentCard/PaymentCard.less, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js
=> Fix payables nigthmode

src/client/object/AppendForm.js
=> Finished newsFilter

src/client/object/AppendForm.js, src/waivioApi/routes.js
=> Fixed link to object in rule

src/client/Wrapper.js, src/client/components/EntryModal/EntryModal.js, src/client/components/EntryModal/EntryModal.less, src/client/styles/styles-shortcodes.less, src/investarena/components/CreatePostForecast/CreatePostForecast.js, src/investarena/components/CreatePostForecast/helpers.js
=> Modal notification invest arena

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Sidebar/ObjectCard.js, src/client/object/AppendForm.js, src/client/object/NewsFilter/newsFilterHelper.js, src/client/object/wObjectHelper.js
restore max weighted filter on append news filter field
=> NewsFilter - restore active filter on append news filter field

src/client/user/UserStatistics/UserAccuracyChart/UserAccuracyChart.js
=> User statistic requests

src/client/object/AppendForm.js
=> Fixed bug in adding ignoreList

src/client/activity/Activity.js, src/client/feed/Feed.js, src/client/feed/Feed.less, src/client/feed/SubFeed.js, src/client/helpers/stateHelpers.js, src/client/invite/Invite.js, src/client/post/Write/Drafts.js, src/client/replies/Replies.js, src/client/search/Search.js, src/client/settings/ProfileSettings.js, src/client/statics/EmptyFeed.js, src/client/statics/Error404.js, src/client/user/UserStatistics/UserStatistics.js
=> Empty feed message bug fix

src/client/app/Sidebar/ObjectInfo.js, src/client/components/ObjectMenu.js, src/client/object/WobjHistory.js, src/common/constants/listOfFields.js, src/common/routes.js
=> Hidden gallery

src/client/components/Navigation/TopNavigation-nightmode.less, src/client/components/Navigation/Topnav-nightmode.less, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/post/PostPreviewModal/PostPreviewModal-nightmode.less, src/client/post/PostPreviewModal/PostPreviewModal.js
=> Topnav investarena fix

src/client/components/Navigation/Topnav.less
=> Topnav broker icon edit

src/investarena/components/Header/Balance/Balance.less
=> fixed braking row

src/client/app/Sidebar/RightSidebar.js, src/client/components/Navigation/Topnav.js, src/client/components/PopoverMenu/PopoverMenu-nightmode.less, src/client/components/PopoverMenu/PopoverMenuItem-nightmode.less, src/client/user/UserStatistics/UserAccuracyChart/UserAccuracyChart.js, src/client/user/UserStatistics/UserAccuracyChart/UserAccuracyChart.less, src/client/user/UserStatistics/UserStatistics.js
=> chart and value rendering at the same time

src/client/feed/Page.js, src/client/feed/SubFeed.js, src/waivioApi/ApiClient.js
=> Added separate value and logik for myFeed switcher status management

src/investarena/components/InstrumentsPage/Instrument/InstrumentCardView/InstrumentCardView.js, src/investarena/components/Modals/ModalBroker/ModalBroker.js, src/investarena/components/Modals/ModalBroker/ModalBroker.less
=> Fixed opening in a new tab

src/client/components/Navigation/Topnav.js, src/client/components/PopoverMenu/PopoverMenuItem.js, src/client/components/PopoverMenu/PopoverMenuItem.less, src/client/feed/Page.js, yarn.lock
=> Topnav burger

src/client/components/Story/StoryFull.js, src/client/user/UserStatistics/UserAccuracyChart/UserAccuracyChart.js, src/client/user/userActions.js
=> Fixed bug in Popover

src/client/post/postActions.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/CampaignFooter/CampainFooterContainer.js
=> Waiv 699 rewards likes 

src/client/components/Navigation/Topnav.js, src/client/discoverObjects/DiscoverFiltersSidebar/DiscoverFiltersSidebar.js, src/client/discoverObjects/DiscoverObjects.js, src/client/notifications/Notifications.js, src/client/objectTypes/objectTypeActions.js, src/client/objectTypes/objectTypeReducer.js, src/client/reducers.js
Exclude objects from list (and map) if status is 'unavailable' or 'relisted'
=> Waiv 622 hide obj by status

src/client/components/ObjectHeader.less, src/client/object/WobjHeader.js
=> Fixed edit button in WobjHeader

src/client/objects/Objects.less, src/client/objects/ObjectsContainer.js
=> Added change button to all objects, fixed bug with layout

src/client/components/Navigation/Topnav.js, src/client/rewards/Payment/Payment.js, src/client/rewards/PaymentCard/PaymentCard.js
=> Remove paymentcard form receivables

src/client/components/Navigation/Topnav.js, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTableBodyRow.js
=> edited checkbox visibility

src/client/components/Navigation/Topnav.js, src/client/rewards/Create-Edit/CreateFormRenderer.js
=> edited autofocus in create page

src/client/components/Navigation/Topnav-nightmode.less, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/styles/common.less
=> Mobile menu update

src/client/userCardView/UserCardView-nightmode.less, src/client/userCardView/UserCardView.less
=> Create page night mode fix

src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/CreateReward.less
=> added asterisk symbol near required fields and styles

src/client/rewards/Create-Edit/CreateReward-nightmode.less
=> Create page date picker edit

src/client/components/Comments/QuickCommentEditor.js, src/client/components/EntryModal/EntryModal.js, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/components/QuickPostEditor/QuickPostEditor.js, src/client/feed/Page.js, src/client/feed/SubFeed.js, src/client/object/AppendForm.js, src/client/settings/ProfileSettings.js, src/client/wallet/Transfer.js, src/investarena/components/CreatePostForecast/CreatePostForecast.js
=> Waiv 804 nav sidebar scroll

src/client/components/Navigation/Topnav.js, src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/CampaignFooter/CampainFooterContainer.js
=> changed permlink on follow

src/client/feed/feedActions.js, src/client/user/UserProfile.js, src/waivioApi/ApiClient.js
=> edited request to get users feed

src/client/rewards/Payment/Payment.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js
=> Addid links to payment history, fixed bug in payment component

src/client/components/Maps/Map.less
=> fixed displaying up-button

src/client/components/Navigation/Topnav.less
=> fixed topnav styles [WAIV - 768]

src/client/rewards/Rewards.js
=> edited sending request on close map filters

src/client/components/Slider/RawSlider.js, src/client/rewards/PaymentCard/PaymentCard.less
=> Slider edit

src/client/activity/UserActivity.js, src/client/components/Navigation/Topnav.js, src/client/object/Tags/TagsHelper.js, src/client/user/User.js, src/client/wallet/walletReducer.js
=> Fixed bug with activities loading

src/client/components/Navigation/MobileNavigation/MobileNavigation.less, src/client/discoverObjects/DiscoverObjectsContent.js
=> Discover page filters mobile fix [WAIV-826]

src/client/object/ObjectGallery/ObjectGallery.js
=> Gallery fix [WAIV-830]

src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/styles/modules/feed-layout.less
=> Fixed bug in write post icon displaying

src/client/activity/Activity.js, src/client/app/Sidebar/LeftSidebar.js, src/client/components/Navigation/MobileNavigation/MobileNavigation.js, src/client/components/Navigation/SidenavUser.js
=> Tools tag edit [WAIV-736]

src/client/components/Story/Story.js, src/client/locales/default.json
=> Fixed bug in reblogged signature

src/client/Wrapper.js, src/client/components/Chat/chatActions.js, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/steemConnectAPI.js
=> Chat investarena

src/investarena/components/CreatePostForecast/CreatePostForecast.js, src/investarena/components/CreatePostForecast/CreatePostForecast.less
=> Forecast create mobile [WAIV-829]

src/client/Wrapper.js, src/client/components/BBackTop.less, src/client/components/ChatButton/ChatButton.less
=> Support chat button [WAIV-876, 877]

src/client/components/Navigation/LanguageSettings.less
=> Languages popover mobile [WAIV-767]

src/client/components/ObjectMenu.js, src/client/components/UserHeader.js, src/client/components/UserMenu.js, src/client/components/UserMenu.less, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/Wobj.js, src/client/object/WobjHeader.js, src/client/object/WobjHero.js, src/client/user/UserHero.js
=> Implemented show mor button in UserHeader and ObjectHeader

src/client/components/Sidebar/WalletSidebar.js, src/client/components/Story/Story.js, src/client/locales/default.json, src/client/locales/ru-RU.json
=> Added exchange button to WalletSidebar WAIV-885

src/client/object/WobjHeader.js
=> View button in list type objects

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/WobjHeader.js, src/client/object/const/appendFormConstants.js
=> Append form status validation [WAIV-636]

src/client/components/Navigation/MobileNavigation/MobileNavigation.less, src/client/helpers/wObjInfluenceHelper.js, src/client/object/WobjHeader.js, src/client/post/EditPost/EditPost.js, src/client/post/Write/Drafts.js, src/client/rewards/CampaignFooter/CampainFooterContainer.js, src/client/rewards/Debts/Debts.less, src/client/rewards/Payment/Payment.js, src/client/rewards/PaymentCard/PaymentCard.js, src/client/wallet/Transfer.js, src/client/wallet/Transfer.less
=> Fixed mobile layout in transfer modal

src/client/components/Chat/Chat.js
=> Chat some fix [WAIV-865]

src/client/object/ObjectProfile.js
=> Get posts with current locale fix [WAIV-759]

src/client/app/Sidebar/ObjectInfo.js, src/client/helpers/wObjInfluenceHelper.js, src/client/object/Catalog/CatalogWrap.js, src/client/post/EditPost/EditPost.js, src/client/post/Write/Drafts.js, src/client/rewards/CampaignFooter/CampainFooterContainer.js, src/client/rewards/Payment/Payment.js, src/client/rewards/PaymentCard/PaymentCard.js, src/client/rewards/Rewards.less
=> Rewards card [WAIV-870]

src/client/app/Sidebar/ObjectInfo.js, src/client/helpers/wObjInfluenceHelper.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/TagCategory/CreateTag.js, src/client/post/EditPost/EditPost.js, src/client/post/Write/Drafts.js, src/client/rewards/CampaignFooter/CampainFooterContainer.js, src/client/rewards/Payment/Payment.js, src/client/rewards/PaymentCard/PaymentCard.js
=> Object updates crash fix [WAIV-915]

src/client/rewards/rewardsHelper.js, src/waivioApi/ApiClient.js
=> Get rewards campaign (log out)

src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Create-Edit/fieldsData.js
=> Create campaign fix

src/client/rewards/Manage/BalanceTable/BalanceTable.js, src/client/rewards/Payment/Payment.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js
=> Payment and manage few fix [WAIV-923]

src/client/rewards/Proposition/Proposition.js
=> Fixed reject prevalidation [WAIV-926]

src/client/components/Chat/Chat.js, src/investarena/components/LeftSidebar/LongTermStatistics/InstrumentLongTermStatistics.js, src/investarena/components/LeftSidebar/LongTermStatistics/UserLongTermStatistics.js, src/investarena/helpers/diffDateTime.js
=> Instrument performance block language

src/client/components/Navigation/TopNavigation.js
=> Topnavigation hide [WAIV-935]

src/client/rewards/Payment/Payment-nightmode.less, src/client/rewards/Payment/Payment.js, src/client/rewards/Payment/Payment.less, src/client/rewards/PaymentCard/PaymentCard-nightmode.less, src/client/rewards/Rewards-nightmode.less, src/client/styles/custom.less, yarn.lock
=> Fixed rewards nightmode [WAIV-933]

src/client/rewards/Manage/Manage.js, src/client/rewards/MatchBot/MatchBot.js, src/client/rewards/MatchBot/MatchBot.less
=> Match bot auth [WAIV-937]

src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js
=> Rewards edit propositions [WAIV-925]

src/client/rewards/MatchBot/CreateRule/CreateRule.js, src/client/rewards/MatchBot/MatchBot.js, src/client/rewards/MatchBot/MatchBotTable/MatchBotTableRow.js, src/client/rewards/rewardsActions.js, src/client/steemConnectAPI.js
=> MatchBot edit

src/client/rewards/Payment/Payment.js
=> Payment edit

src/client/components/Editor/EditorInput.js, src/client/components/Story/Story.js, src/client/components/Story/StoryFull.js, src/client/helpers/forecastHelper.js, src/client/helpers/wObjInfluenceHelper.js, src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/styles/styles-shortcodes.less, src/common/routes.js, src/investarena/components/PostChart/PostChart.js, src/investarena/components/PostChart/TabSelect/TabSelect.js, src/investarena/components/PostSellBuy/PostSellBuy.js
=> Adding images into comment [IA]

src/client/rewards/MatchBot/MatchBot.js
=> MatchBot auth/revoke edit [WAIV-1025]

src/client/components/Story/Story.js, src/client/components/Story/StoryFull.js, src/client/feed/Page.js, src/client/feed/SubFeed.js, src/client/helpers/forecastHelper.js, src/client/helpers/wObjInfluenceHelper.js, src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/styles/styles-shortcodes.less, src/common/routes.js, src/investarena/components/PostChart/PostChart.js, src/investarena/components/PostChart/TabSelect/TabSelect.js, src/investarena/components/PostSellBuy/PostSellBuy.js
=> Feed switcher edit [WAIV-990]

src/client/rewards/MatchBot/MatchBot.less, src/client/rewards/Rewards.js
=> Rewards left sidebar edit styles [WAIV-896]

src/client/rewards/Details/Details.js, src/client/rewards/Details/Details.less, yarn.lock
=> Rewards details modal edit

src/client/comments/commentsActions.js, src/client/components/Navigation/ModalSignUp/ModalSignUp.js, src/client/components/Sidebar/WalletSidebar.js, src/client/components/Story/Story.js, src/client/helpers/stateHelpers.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/rewards/MatchBot/MatchBot.js, src/client/user/UserWallet.js, src/client/wallet/UserWalletSummary.js
=> Fixed bugs with likes and posts. Edited wallet.

src/client/user/User.js
=> chat few fix

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/rewards/Campaign/Campaign.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/CampaignFooter/CampaignFooter.less, src/client/rewards/Details/Details.js, src/client/rewards/Details/detailsMessagesData.js, yarn.lock
=> Rewards card edit [WAIV-1039]

src/client/feed/LetsGetStarted.js, src/client/object/WobjFollowers.js, src/client/user/UserDynamicList.js
=> Fixed bug with object followers

src/client/components/EditorExtended/components/sides/ImageSideButton.js, src/client/components/ImageSetter/ImageSetter.less, src/client/object/ObjectGallery/CreateImage.js, src/client/settings/ProfileSettings.js, src/client/settings/Settings.less, yarn.lock
=> Adding images [WAIV-1047]

src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Rewards.js, src/client/user/userActions.js, yarn.lock
=> Create/reserve campaign edit [WAIV-947]

src/client/components/EditorExtended/components/sides/ImageSideButton.js, src/client/components/ImageSetter/ImageSetter.js, src/client/components/ImageSetter/ImageSetter.less, src/client/object/AppendForm.js, src/client/settings/ProfileSettings.js, src/client/settings/Settings.less, src/client/styles/custom.less, yarn.lock
=> Adding images IA [WAIV - 1110]

src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Details/Details.js
=> Rewards few fix [WAIV-1122]

src/client/components/Navigation/MobileNavigation/MobileNavigation.js, src/client/rewards/Campaign/Campaign.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.less, src/client/rewards/FilteredRewardsList.js, src/client/rewards/Rewards.js, src/client/rewards/Rewards.less
=> Campaign card fix [WAIV-1063]

src/investarena/components/QuickForecastPage/QuickForecastCard/QuickForecastCard.less, src/investarena/components/QuickForecastPage/QuickForecastPage.js, src/investarena/components/QuickForecastPage/TopPredictions/TopPredictions.less
=> Dev invest arena fix style

src/client/components/ImageSetter/ImageSetter-nightmode.less, src/client/components/ImageSetter/ImageSetter.less
=> Image setter night [WAIV-1140]

src/client/components/Navigation/Sidenav.less, src/client/components/Navigation/SidenavUser.js, src/client/discoverObjects/SidenavDiscoverObjects.js
=> Left side bar edit all [WAIV-932]

src/client/rewards/FilteredRewardsList.js, src/client/rewards/Rewards.js
https://maxiproject.atlassian.net/browse/WAIV-1125
=> Campaigns on logout [WAIV-1125]

src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/rewards/Create-Edit/CreateReward-nightmode.less, src/client/styles/fonts.less
=> Fix clear button in main search 

src/client/rewards/Debts/Debts.less, src/client/rewards/Manage/Manage.less, src/client/rewards/MatchBot/MatchBot.less, src/client/rewards/Payment/Payment.less, src/client/rewards/RewardsBreadcrumb/RewardBreadcrumb.js
https://maxiproject.atlassian.net/browse/WAIV-901
=> Rewards edit styles [WAIV-901]

src/client/auth/authActions.js, src/client/comments/commentsActions.js, src/client/components/Navigation/GuestSignUpForm/GuestSignUpForm.js, src/client/components/Navigation/ModlaSignIn/ModalSignIn.js, src/client/components/Story/Story.js, src/client/components/Story/StoryFull.js, src/client/helpers/getToken.js, src/client/helpers/postHelpers.js, src/client/helpers/regexHelpers.js, src/client/helpers/stateHelpers.js, src/client/post/PostContent.js, src/client/post/PostModal.js, src/waivioApi/ApiClient.js
=> Guest users upd

src/client/components/CommentFooter/Buttons.js, src/client/components/CommentFooter/CommentFooter.js, src/client/components/Navigation/GuestSignUpForm/GuestSignUpForm.js, src/client/components/Navigation/ModalSignIn/ModalSignIn.js, src/client/components/Navigation/ModalSignUp/ModalSignUp.js
=> Fixed comment footer for fake comments, fixed guest registration

src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/styles/modules/topnav-layout.less
https://maxiproject.atlassian.net/browse/WAIV-1164
=> Changed main logo [WAIV-1164]

src/client/components/ImageSetter/ImageSetter.js
=> edited target values

src/waivioApi/ApiClient.js
=> changed chat link

src/client/Wrapper.js, src/client/components/WelcomeModal/WelcomeModal.js, src/client/locales/ru-RU.json
=> welcome modal fix

src/client/rewards/Rewards.js
https://maxiproject.atlassian.net/browse/WAIV-1169
=> Rewards link share [WAIV-1169]

src/client/components/Navigation/Topnav.less, src/client/components/Sidebar/ObjectCard.less, src/client/discoverObjects/DiscoverObjectsContent.js
=> fix 904, 766, 825

src/client/components/Navigation/Sidenav-nightmode.less, src/client/components/Navigation/Topnav-nightmode.less, src/client/components/Navigation/Topnav.less
https://maxiproject.atlassian.net/browse/WAIV-1186
=> Fixed topnav styles [WAIV-1186]

src/client/auth/authActions.js, src/client/auth/authReducer.js, src/client/components/Avatar.js, src/client/reducers.js, src/client/rewards/MatchBot/MatchBot.js, src/client/settings/ProfileSettings.js
=> Fixed cashing ava image

src/client/object/Catalog/AddItemModal/AddItemModal.js, src/client/object/Catalog/CatalogWrap.js
enable object menu items (nested lists) editing
=> nested lists editing [waiv-1131]

src/client/components/Avatar.js
=> Discover object cards [WAIV-1159]

src/client/app/Reblog/reblogActions.js, src/client/comments/commentsActions.js, src/client/comments/commentsReducer.js, src/client/components/CommentFooter/Buttons.js, src/client/components/Navigation/GuestSignUpForm/GuestSignUpForm.js, src/client/components/Navigation/GuestSignUpForm/GuestSignUpFormContent.js, src/client/components/Navigation/ModalSignIn/ModalSignIn.js, src/client/components/Navigation/ModalSignUp/ModalSignUp.js, src/client/components/Navigation/SignUpButton/SignUpButton.js, src/client/components/Navigation/SignUpInfo/SignUpInfo.js, src/client/components/Navigation/SocialButtons/SocialButtons.js, src/client/components/Navigation/SteemSignUpCard/SteemSignUpCard.js, src/client/components/Sidebar/ObjectExpertise.js, src/client/components/Story/Story.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/wObjectHelper.js, src/client/post/Write/editorActions.js, src/client/post/postActions.js, src/client/post/postsReducer.js, src/waivioApi/ApiClient.js, yarn.lock
=> fixed guests bugs

src/client/app/Sidebar/LeftSidebar.js, src/client/components/Navigation/ModalSignUp/ModalSignUp.js, src/client/components/Navigation/SignUpInfo/SignUpInfo.js, src/client/components/Sidebar/SignUp.js, src/client/styles/styles-shortcodes.less, src/investarena/redux/selectors/quotesSelectors.js, src/investarena/redux/selectors/quotesSettingsSelectors.js
=> fixed bug with leftSidebar rerendering, fixed signup button

src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/styles/mixins.less
=> Invest arena waiv 904

src/client/app/Sidebar/RightObjectSidebar.js, src/client/components/ImageSetter/ImageSetter-nightmode.less, src/client/components/ImageSetter/ImageSetter.less, src/client/components/Navigation/Notifications/Notification-nightmode.less, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/components/UserCard-nightmode.less
=> WAIV-1102, 1165, 1275, 899

src/client/components/Editor/EditorToolbar.less, src/client/components/Navigation/Notifications/Notification-nightmode.less, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/components/Sidebar/ObjectCard.js, src/client/components/Sidebar/ObjectCard.less, src/client/objects/Objects.less, src/client/objects/ObjectsContainer.js, src/client/styles/common.less
=> Bug fix waivio

src/client/components/ImageSetter/ImageSetter.less, src/client/components/Navigation/GuestSignUpForm/GuestSignUpForm.js, src/client/components/Navigation/GuestSignUpForm/GuestSignUpFormContent.js, src/client/components/UserHeader.js, src/client/user/User.js, src/client/user/UserHero.js, src/client/user/UserProfile.js, src/waivioApi/ApiClient.js
=> Invest arena guests

src/client/Wrapper.js, src/client/components/WelcomeModal/WelcomeModal.js, src/client/user/userActions.js, src/client/user/userReducer.js, src/waivioApi/ApiClient.js
=> Fix welcome modal

src/client/components/ImageSetter/ImageSetter.less, src/client/components/Sidebar/ObjectCard-nightmode.less, src/client/components/Sidebar/ObjectsRelated/ObjectsRelated-nightmode.less, src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js, src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.less, src/client/components/Sidebar/mostProfitableUsers/mostProfitableUsers.js, src/client/components/Story/Story.js, src/client/components/UserCard.less, src/client/object/Wobj.js, src/investarena/api/Performers.js, src/investarena/components/PostSellBuy/PostSellBuy.less
=> Invest arena waiv 1196

src/client/components/Chat/Chat.js, src/waivioApi/ApiClient.js
=> chat staging fix

src/investarena/components/QuickForecastPage/QuickForecastPage.js, src/investarena/components/QuickForecastPage/QuickForecastPage.less, src/investarena/components/QuickForecastPage/TopPredictions/TopPredictors.js, src/investarena/redux/reducers/forecastReducer.js
=> InvesArena [WAIV-1044]

src/client/components/Chat/Chat.js, src/client/components/Navigation/Topnav.js, src/client/components/Sidebar/SignUp.js, src/client/object/Wobj.js, src/client/settings/ProfileSettings.js, src/waivioApi/ApiClient.js
=> Chat fix master

src/client/components/ImageSetter/ImageSetter.js, src/client/components/Navigation/Topnav.js, src/client/object/Wobj.js, src/client/settings/ProfileSettings.js, yarn.lock
https://maxiproject.atlassian.net/browse/WAIV-1204
=> Image url validaiton IA [WAIV-1204]

src/client/components/ImageSetter/ImageSetter.js
https://maxiproject.atlassian.net/browse/WAIV-1203
=> Edited images validation by link [WAIV-1203]

src/client/user/UserProfile.js, src/investarena/components/QuickForecastPage/QuickForecastPage.js, src/investarena/components/QuickForecastPage/TopPredictions/TopPredictors.js
https://maxiproject.atlassian.net/browse/WAIV-990
=> fixed toggle [WAIV-990]

src/client/components/PopoverMenu/PopoverMenu.js, src/client/components/Story/StoryFull.js, src/client/components/StoryFooter/Buttons.js, src/investarena/components/Common.less, src/investarena/components/InstrumentsPage/TradeButtons/TradeButtons.less, src/investarena/components/InstrumentsPage/TradeButtonsAssets/TradeButtonsAssets.less
=> WAIV-1220, WAIV-1221

src/client/components/Chat/Chat.js, src/client/components/ChatButton/ChatButton.less, src/client/components/PopoverMenu/PopoverMenu.js, src/client/components/Story/StoryFull.js, src/client/components/StoryFooter/Buttons.js, src/investarena/components/InstrumentsPage/TradeButtons/TradeButtons.less
https://maxiproject.atlassian.net/browse/WAIV-971
=> Chat fixes [WAIV-971]

src/client/wallet/Transfer.js
=> Waivio [WAIV-1219] add balance in Transfer modal for guest user

src/client/Wrapper.js, src/client/auth/withAuthActions.js, src/client/components/Chat/Chat.js, src/client/components/LoginModal.js, src/investarena/components/QuickForecastPage/QuickForecastPage.js
=> Invest arena login facebook

src/client/components/Editor/Editor.less, src/client/components/Editor/EditorInput.js, src/client/components/Editor/EditorInput.less, src/client/components/EditorObject/SearchObjectsAutocomplete.js, src/client/components/EditorUser/SearchUsersAutocomplete.js, src/client/components/LoginModal.js, src/client/components/Navigation/SocialButtons/SocialButtons.js, src/client/components/Sidebar/ObjectCard.less, src/client/wallet/Transfer.js
=> Waivio bug fix [WAIV-848, WAIV-1240] try fix facebook authorization

src/client/components/LoginModal.js, src/client/components/Navigation/ModlaSignIn/ModalSignIn.js, src/client/components/StoryFooter/Buttons.js
=> move  authorization / registration fix via Google from IA

src/client/components/LoginModal.js, src/client/components/Navigation/SocialButtons/SocialButtons.js
=> Arena fix auth facebook

src/client/helpers/mapProvider.js
=> fixed map address

src/client/components/Navigation/TopNavigation.js
https://maxiproject.atlassian.net/browse/WAIV-1225
=> Hide tools [WAIV-1225]

src/client/object/LikeSection.js
=> Waivio 1246

src/client/components/EditorObject/SearchObjectsAutocomplete.js, src/client/components/Navigation/Topnav.js, src/client/discoverObjects/SidenavDiscoverObjects.js, src/client/objects/Objects.less
=> WAIV-[815, 867]

src/client/object/AppendForm.js, src/client/object/AppendForm.less, src/client/objects/Objects.less, src/client/objects/ObjectsContainer.js, src/client/styles/common.less
=> fix z-index in autocomplete

src/client/Wrapper.js, src/client/auth/authActions.js, src/client/components/Chat/Chat.js, src/client/components/ForecastItem/ForecastItem-nigthtmode.less, src/client/components/ForecastItem/ForecastItem.js, src/client/components/ForecastItem/ForecastItem.less, src/client/components/LoginModal.js, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/object/LikeSection.js, src/client/settings/ProfileSettings.js, src/client/wallet/Transfer.js, src/investarena/components/QuickForecastPage/QuickForecastPage.js
=> WAIV-[978, 1239, 1252, 1259]

package.json, src/client/settings/ProfileSettings.js
https://maxiproject.atlassian.net/browse/WAIV-1256
=> Edited init images on profile settings [WAIV-1256]

src/client/comments/Comments.js, src/client/components/CommentFooter/CommentFooter.js, src/client/components/Story/Story.js, src/client/components/StoryFooter/StoryFooter.js, src/client/post/PostContent.js
https://maxiproject.atlassian.net/browse/WAIV-962
=> Unlike edit [WAIV-962]

src/client/components/Editor/withEditor.js, src/client/components/Navigation/Notifications/Notification.less, src/client/components/Navigation/Topnav.js, src/client/components/StoryFooter/AppendObjButtons.js, src/client/components/StoryFooter/Buttons.js, src/client/helpers/voteHelpers.js, src/client/post/Write/editorActions.js, src/client/rewards/Campaign/Campaign.less, src/client/rewards/CampaignCardHeader/CamapaignCardHeader-nightmode.less, src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/Details/Details.js, src/client/rewards/Details/Details.less
=> WAIV-[1167, 1261, 1247, 1271, 1274, 1212]

src/client/components/Navigation/Topnav.js, src/client/components/Reactions/ReactionsList.js, src/client/components/StoryFooter/AppendObjButtons.js, src/client/components/StoryFooter/Buttons.js, src/client/helpers/voteHelpers.js, src/client/post/Write/editorActions.js, src/client/settings/ProfileSettings.js, src/client/user/UserStatistics/UserInstrumentsTable/UserInstrumentsTable.js, src/client/wallet/ClaimRewardsBlock.js, src/client/wallet/Transfer-nightmode.less, src/client/wallet/Transfer.less, src/investarena/components/CreatePostForecast/CreatePostForecast-nightmode.less, src/investarena/components/CreatePostForecast/CreatePostForecast.js
=> WAIV - [1277, 1238, 1258, 1275, 977, 1289]

src/client/components/Navigation/Topnav.js, src/client/components/Reactions/ReactionsList.js, src/client/wallet/ClaimRewardsBlock.js
=> Fix claim rewards

src/client/components/Avatar.js, src/client/components/Navigation/SidenavRewards.js, src/client/components/Navigation/SidenavUser.js, src/client/settings/ProfileSettings.js
https://maxiproject.atlassian.net/browse/WAIV-1306
=> Cashing profile avatar on WV, navbar styles [WAIV-1306, 1286]

src/client/auth/authActions.js, src/client/components/LoginModal.js, src/client/feed/Page.js, src/client/helpers/getToken.js, src/client/index.js, src/client/steemConnectAPI.js, src/client/user/UserStatistics/UserInstrumentsTable/UserInstrumentsTable.js, src/common/constants/waivio.js, src/server/handlers/createSsrHandler.js, src/waivioApi/ApiClient.js
support ssr auth for guest users
=> ssr guest auth [waiv-1304]

src/client/user/usersHelper.js
https://maxiproject.atlassian.net/browse/WAIV-1270
=> User statistics fix [WAIV-1270]

src/client/components/Reactions/ReactionsList.js, src/client/components/StoryFooter/Buttons.js
https://maxiproject.atlassian.net/browse/WAIV-1311
=> Like fix IA [WAIV-1311]

src/client/auth/authActions.js, src/client/user/userActions.js, src/common/services/createBusyAPI.js
=> Notifications on IA

src/client/components/Chat/Chat.js
=> Chat guest fix

src/client/components/Sidebar/WalletSidebar.js
https://maxiproject.atlassian.net/browse/WAIV-965
=> Displaying exchange button [WAIV-965]

src/client/components/WelcomeModal/WelcomeModal.js, src/client/feed/feedActions.js, src/client/feed/feedReducer.js, src/client/object/AppendForm.js, src/client/object/const/appendFormConstants.js
=> WAIV - [866, 1296, 844, 942]

src/client/components/Navigation/Topnav.js, src/client/object/AppendForm.js, src/client/post/Write/editorActions.js, src/waivioApi/ApiClient.js
=> WAIV - [844, 1167, 866]

src/client/object/AppendForm.js, src/client/object/WobjHistory.js
=> done reopen task WAIV-[844, 1284, 866]

src/client/components/Navigation/ModalSignUp/ModalSignUp.js, src/client/components/Navigation/Topnav.js, src/client/components/Story/Story.js, src/client/helpers/parser.js, src/client/locales/default.json, src/client/objectCard/ObjectCardView.js, src/client/search/searchActions.js, src/client/search/searchReducer.js, src/waivioApi/ApiClient.js
=> WAIV - [1253, 1214]

src/client/components/Sidebar/LastDrafts.less, src/client/components/Sidebar/ObjectCard.js, src/client/components/Sidebar/ObjectCard.less, src/client/components/Sidebar/ObjectExpertiseByType/ObjectExpertiseByType.less, src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.less, src/client/components/UserCard-nightmode.less, src/client/components/UserCard.js, src/client/components/UserCard.less, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/ObjectGallery/CreateAlbum.js, src/client/rewards/Details/Details.less
=> WAIV - [968, 1090, 1342]

src/client/components/WeightTag.js, src/client/discover/DiscoverUser.js
https://maxiproject.atlassian.net/browse/WAIV-1278
=> Reblog object weight displaying [WAIV-1278]

src/client/objectTypes/objectTypeActions.js
=> Map changes

src/client/discoverObjects/SidenavDiscoverObjects.js
=> cut_sidebar

src/client/app/Sidebar/TopPerformers/TopPerformers.js
Fixed "NaN" in block top-performers
=> arena-fix-nan

src/client/post/Write/editorActions.js
=> 1456-fix-bug-in-notification

src/client/Wrapper.js, templates/index.hbs
=> Remove chat

src/client/components/Navigation/BrokerBalance/BrokerBalance.js, src/client/components/Navigation/BrokerBalance/BrokerBalance.less, src/client/components/Navigation/Topnav.less, src/client/locales/default.json, src/client/locales/ru-RU.json
=> Beaxy balance fix [WAIV-1440, 1459]

src/client/auth/authActions.js, src/client/components/Navigation/BrokerBalance/BrokerBalance.js, src/investarena/redux/actions/brokersActions.js
=> fixed displaying broker modal

src/client/components/Navigation/TopNavigation.js, src/client/components/Navigation/TopNavigation.less, src/client/components/ObjectMenu.js, src/client/components/UserMenu.js, src/client/components/UserMenu.less
=> updated fix tabbar bug

src/client/components/Navigation/TopNavigation.less
=> 1477 fixed topNavigation active link

src/client/components/Navigation/BrokerBalance/BrokerBalance.less, src/investarena/redux/actions/brokersActions.js, src/investarena/redux/reducers/platformReducer.js
https://maxiproject.atlassian.net/browse/WAIV-1497
https://maxiproject.atlassian.net/browse/WAIV-1488
=> Crashind front fix [WAIV-1497], displaying drop down fix [WAIV-1488]

src/client/styles/styles-shortcodes.less, src/client/user/UserWallet.js, src/client/wallet/UserWalletSummary.js, src/client/wallet/UserWalletSummary.less
https://maxiproject.atlassian.net/browse/WAIV-1491
=> Displaying show more btn [WAIV-1491]

src/client/wallet/PowerUpOrDown.js
=> 1474 power up power down validation

src/client/objectCard/ObjectCardView.js
if server send 0 of weight - not render 0 instead it empty
=> Fixed: if server send 0 of weight - not render 0 instead it empty

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Navigation/BrokerBalance/BrokerBalance-nightmode.less, src/client/components/Navigation/BrokerBalance/BrokerBalance.less, src/client/styles/common-nightmode.less, src/client/wallet/ClaimRewardsBlock.less, src/client/wallet/CurrencyItem/CurrencyItem-nightmode.less, src/client/wallet/CurrencyItem/CurrencyItem.less
=> 1496-fix-nightmode

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Navigation/BrokerBalance/BrokerBalance.js, src/client/components/Navigation/BrokerBalance/BrokerBalance.less, src/client/components/Story/Story.js, src/client/helpers/forecastHelper.js, src/client/user/UserWallet.js, src/client/wallet/UserWalletSummary.js, src/investarena/redux/reducers/platformReducer.js
=> Forecast post [WAIV-1502], dropdown fix [WAIV-1478], crashing wallet fix [WAIV-1488]

src/client/app/Sidebar/ObjectInfo.js, src/client/auth/authActions.js, src/client/components/Navigation/BrokerBalance/BrokerBalance.js, src/client/user/usersHelper.js
https://maxiproject.atlassian.net/browse/WAIV-1498
=> Disconnect broker fix [WAIV-1498]

src/client/components/Navigation/BrokerBalance/BrokerBalance-nightmode.less
Fix element color when wallet is one
=> Fix night mode

src/client/object/AppendForm.js
Fixed bug when instead array get string
=> Fixed bug with string instead array

src/client/components/UserCard-nightmode.less
=> 1475 add delimiter - fixed nightmode

src/client/components/Maps/Map.js, src/client/components/Maps/Map.less, src/client/components/Maps/MapWrap/MapWrap.js, src/client/components/Navigation/TopNavigation.js, src/client/discoverObjects/DiscoverFiltersSidebar/DiscoverFiltersSidebar.js, src/client/objectCard/ObjectCardView.js, src/client/objectTypes/objectTypeActions.js, src/client/rewards/Campaign/Campaign.js, src/client/rewards/Rewards.js
=> Waiv 1215,1266,1489

src/client/activity/UserActionMessage.js, src/client/components/LoginModal.js, src/client/components/Navigation/SignUpInfo/SignUpInfo.js, src/client/components/Navigation/SteemSignUpCard/SteemSignUpCard.js, src/client/components/StoryFooter/Buttons.js, src/client/helpers/__tests__/errorMiddleware.js, src/client/helpers/voteHelpers.js, src/client/styles/modules/popover-layout.less, src/client/wallet/Transfer.js
Fix language bar in mobile view
=> 1226-fix-language-bar

src/client/components/Navigation/Notifications/Notifications.less
=> 1518 fixed double scroll in notification dropdown

src/client/objectCard/ObjectCardView.js, src/client/rewards/Proposition/Proposition.js
=> fixed 1268

src/client/components/Story/Story.js, src/client/components/Story/StoryFull.js, src/client/post/Post.js, src/client/post/PostContent.js, src/common/routes.js
=> window display fixed

src/client/Wrapper.js, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/components/UserHeader.js
=> Hide chat [WAIV-1517]

src/client/rewards/rewardsHelper.js
=> fix hive price in revards

src/client/auth/authActions.js
=> 1536 1357 fixed logout action

src/client/auth/withAuthActions.js, src/client/components/Navigation/ModlaSignIn/ModalSignIn.js, src/client/components/Reactions/ReactionsList.js, src/client/object/Catalog/CatalogWrap.js
=> Waiv 1535 login dilog

src/client/post/Write/editorActions.js
=> Changed: Redirect on post

src/client/post/PostPreviewModal/AdvanceSettings.js
Changed: if guest - like post is disabled
=> 1594-checkbox-ia

src/client/post/PostPreviewModal/AdvanceSettings.js
chenged: if guest user - disable 'like post'
=> 1594-disable-checkbox

src/client/feed/LetsGetStarted.js, src/client/locales/default.json, src/client/locales/ru-RU.json
=> 1586 fixed get started message

src/client/app/appActions.js, src/client/app/appReducer.js, src/client/components/Navigation/Notifications/Notifications.less, src/client/components/Sidebar/CryptoChart.js, src/client/components/Sidebar/CryptoTrendingCharts-nightmode.less, src/client/components/Sidebar/CryptoTrendingCharts.less, src/client/reducers.js, src/investarena/components/PostSellBuy/PostSellBuy.js, src/investarena/components/PostSellBuy/index.js, src/investarena/platform/umarkets.js, src/waivioApi/ApiClient.js, src/waivioApi/config.json, src/waivioApi/routes.js
=> added wallet charts + 1612 fix double scroll

src/client/components/Navigation/HotNews.js, src/client/components/Navigation/MobileMenu/MobileMenu.js, src/client/components/Navigation/MobileMenu/MobileMenu.less, src/client/components/Navigation/Topnav.js
=> Topnav mobile [in progress]

src/client/components/Navigation/HotNews.js, src/client/components/Navigation/MobileMenu/LoggedMenuMobile/LoggedMenuMobile.js, src/client/components/Navigation/MobileMenu/LoggedMenuMobile/LoggedMenuMobile.less, src/client/components/Navigation/MobileMenu/MenuButtons/MenuButtons.js, src/client/components/Navigation/MobileMenu/MenuButtons/MenuButtons.less, src/client/components/Navigation/MobileMenu/MobileMenu-nightmode.less, src/client/components/Navigation/MobileMenu/MobileMenu.js, src/client/components/Navigation/MobileMenu/MobileMenu.less, src/client/components/Navigation/Topnav-nightmode.less, src/client/components/Navigation/Topnav.less, src/client/object/ObjectProfile.js
=> Topnav mobile

src/investarena/components/CreatePostForecast/CreatePostForecast-nightmode.less
=> 1620-change-style

src/client/object/ObjectProfile.js, src/client/styles/common-nightmode.less, src/investarena/components/CreatePostForecast/CreatePostForecast-nightmode.less
=> 1621-adaptate-datepicker

src/client/components/Avatar.js, src/client/components/AvatarLightbox.js, src/client/components/ObjectAvatar.js, src/client/components/ObjectLightbox.js, src/client/components/UserHeader.js, src/client/components/__tests__/Avatar.js, src/client/discover/Discover.js, src/client/discoverObjects/DiscoverObjects.js, src/client/helpers/image.js, src/client/helpers/postHelpers.js, src/client/object/Wobj.js, src/client/object/const/defaultValues.js, src/client/rewards/Rewards.js, src/client/settings/ProfileSettings.js, src/client/user/User.js, src/client/vendor/embedMedia.js
=> 1514, 1629 fixed images

src/client/components/Navigation/HotNews.js, src/client/components/Navigation/MobileMenu/LoggedMenuMobile/LoggedMenuMobile.js, src/client/components/Navigation/MobileMenu/MenuButtons/MenuButtons.js, src/client/components/Navigation/MobileMenu/MobileMenu.js, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less, src/client/discover/Discover.less, src/client/reducers.js, src/client/statics/ErrorPage.less, src/investarena/components/CreatePostForecast/CreatePostForecast-nightmode.less, src/investarena/redux/reducers/platformReducer.js
=> Topnav mobile 

src/client/object/AppendForm.js, src/client/object/appendActions.js, src/waivioApi/ApiClient.js
Fixed: if user in blacklist dont add it and show notification CIA
=> 1329-fix-blacklist-CIA

src/client/object/AppendForm.js, src/client/object/appendActions.js, src/waivioApi/ApiClient.js
Fixed: if user in blacklist dont add it and show notification
=> Fixed: if user in blacklist dont add it and show notification

src/client/app/Sidebar/ObjectInfo.less
=> 1115-fix-left-sidebar

src/client/rewards/MatchBot/CreateRule/CreateRule.js, src/client/rewards/MatchBot/MatchBot.js, src/client/rewards/MatchBot/MatchBotTable/MatchBotTable.js, src/client/rewards/MatchBot/MatchBotTable/MatchBotTableRow.js
=> 1493 fixed matchbot rules update

src/client/post/PostPreviewModal/AdvanceSettings.js, src/client/settings/Settings.js
=> 1595 disabled main settings checkbox

src/client/components/Sidebar/mostProfitableUsers/mostProfitableUsers.js, src/client/settings/Settings.js
Changed: 
1) If guest then in setting disable checkbox "like post"
2) If in top performers bar more then 5 cards - show button "show more"
=> 1653-show-more

src/client/components/Authorization/ModalSignUp/ModalSignUp.js, src/client/components/Authorization/ModalSignUp/ModalSignUp.less, src/client/components/Authorization/SignUpInfo/SignUpInfo.js, src/client/components/Authorization/SteemSignUpCard/SteemSignUpCard.js, src/client/locales/default.json, src/client/locales/ru-RU.json
=> Changed modal of sign up

src/client/app/Sidebar/UserInfo.js, src/client/components/Story/StoryFull.js
=> 1665-hive-reputation

src/client/app/Sidebar/ObjectInfo.js, src/client/app/Sidebar/ObjectInfo.less, src/client/app/Sidebar/UserInfo.js, src/client/components/Navigation/Topnav.less, src/client/components/StoryFooter/AppendObjButtons.js, src/client/object/AppendCard.js
=> WAIV - [1508, 1673, 1697]

src/client/app/Sidebar/UserInfo.js, src/client/components/Avatar.js, src/client/components/AvatarLightbox.js, src/client/components/ObjectAvatar.js, src/client/components/ObjectLightbox.js, src/client/components/UserHeader.js, src/client/feed/LetsGetStarted.js, src/client/helpers/image.js, src/client/object/const/defaultValues.js, src/client/settings/ProfileSettings.js, src/client/user/User.js, src/common/constants/accountHistory.js, src/waivioApi/ApiClient.js
=> 1514, 1607, 1666 fixed displaying images

src/client/components/Maps/Map.js, src/client/discoverObjects/DiscoverFiltersSidebar/DiscoverFiltersSidebar.js, src/client/discoverObjects/DiscoverObjects.less, src/client/discoverObjects/DiscoverObjectsContent.js, src/client/objectTypes/objectTypeActions.js, src/common/constants/map.js
=> Waiv [1671, 1688, 1703]

src/client/rewards/Details/Details.js
=> fixed 1361

src/client/components/Navigation/MobileMenu/MobileMenu.less, src/client/components/Navigation/Topnav.js, src/client/components/Navigation/Topnav.less
=> drop-down fix

package.json, src/client/components/Navigation/BrokerBalance/BrokerBalanceLoading.js, src/client/components/Navigation/Topnav.js, src/client/components/Sidebar/CryptoChart.js, src/client/components/Sidebar/CryptoTrendingCharts.less, src/client/helpers/cryptosHelper.js, src/investarena/components/InstrumentAvatar/index.js, src/investarena/components/InstrumentsPage/Instrument/CardView/CardView-nightmode.less, src/investarena/components/InstrumentsPage/Instrument/CardView/CardView.js, src/investarena/components/InstrumentsPage/Instrument/CardView/CardView.less, src/investarena/components/InstrumentsPage/Instrument/InstrumentChart/InstrumentChart.js, src/investarena/components/InstrumentsPage/Instrument/InstrumentChart/index.js, src/investarena/platform/platformHelper.js
use react-google-charts for sidebar charts
=> waiv-1681 charts lib changing

src/client/components/Navigation/TopNavigation.js
=> Discover link

src/client/app/Sidebar/ExpandingBlock.js, src/client/app/Sidebar/ObjectInfo.js, src/client/app/Sidebar/ObjectInfo.less, src/client/app/Sidebar/UserInfo.js, src/client/components/Reactions/ReactionsModal.js, src/client/components/StoryFooter/AppendObjButtons.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendCard.js, src/client/object/AppendCard.less, src/client/object/ApprovingCard.js, src/client/object/Wobj.js, src/client/object/WobjHistory.js, src/client/object/wObjectHelper.js, src/client/object/wobjectReducer.js, src/client/object/wobjectsActions.js, src/waivioApi/ApiClient.js
=> WAIV - [1720, 1665, 1718]

src/client/app/Sidebar/ObjectInfo.js, src/client/object/WobjHeader.js
=> 1674 changed sidebarInfo for hashtags

src/client/app/Sidebar/UserInfo.js, src/client/auth/authActions.js, src/client/auth/authReducer.js, src/client/components/Avatar.js, src/client/components/AvatarLightbox.js, src/client/components/ObjectLightbox.js, src/client/components/UserHeader.js, src/client/discover/DiscoverContent.js, src/client/discover/DiscoverUser.js, src/client/feed/LetsGetStarted.js, src/client/helpers/image.js, src/client/helpers/postHelpers.js, src/client/helpers/postingMetadata.js, src/client/object/Wobj.js, src/client/object/const/defaultValues.js, src/client/post/PostModal.js, src/client/settings/ProfileSettings.js, src/client/user/User.js, src/common/constants/accountHistory.js, src/waivioApi/ApiClient.js
=> 1741 added image's, profile's functional from waivio

src/client/app/Sidebar/UserInfo.js, src/client/locales/ru-RU.json, src/client/vendor/steemitHelpers.js, src/common/constants/waivio.js
=> 1701 1745 fixed payout details, notification, google-user info

src/client/auth/authActions.js, src/client/components/Navigation/HotNews.js, src/client/components/Navigation/MobileMenu/MenuButtons/MenuButtons.js, src/client/components/Navigation/Topnav.js, src/investarena/components/PostSellBuy/PostCurrentPrice/PostCurrentPrice.js, src/investarena/components/PostSellBuy/PostSellBuy.js
=> Notify fix

src/client/Wrapper.js
=> Fixed unread count request

src/client/components/Comments/QuickCommentEditor.js, src/client/components/EditorExtended/util/videoHelper.js, src/client/helpers/image.js
=> 1741 proxied images, added video prefixes

src/client/styles/common.less
=> 1751 fixed createPost - custom time

src/client/components/Navigation/Topnav.js, src/client/feed/LetsGetStarted.js, src/client/user/User.js
=> waiv - [1739, 1742,  1746]

src/client/components/Comments/QuickCommentEditor.js, src/client/components/Navigation/HotNews.js, src/client/components/Navigation/NewsOverlay.less, src/client/components/Navigation/Notifications/NotificationsTooltip.js
=> 1759 fixed menu popovers

src/client/app/Sidebar/TopInstruments.js, src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.js, src/client/components/Comments/QuickCommentEditor.js, src/client/post/Write/editorActions.js
=> Instruments fix

src/client/components/Navigation/Topnav.js, src/client/user/User.js, src/investarena/components/TchChart/TchChart.js, src/investarena/components/TchChart/chartHelper.js, src/investarena/components/TchChart/index.js
=> Change chart locale

src/client/components/Navigation/MobileMenu/MenuButtons/MenuButtons.less, src/client/components/Navigation/Notifications/NotificationsTooltip.js, src/client/components/Navigation/Topnav.js, src/client/styles/custom.less, src/client/user/User.js
https://maxiproject.atlassian.net/browse/WAIV-1799
=> Notifications displaying [WAIV-1799]

public/images/icons/send.svg, src/client/app/Sidebar/ObjectInfo.js, src/client/components/Comments/QuickCommentEditor.js, src/client/components/Comments/QuickCommentEditor.less, src/client/components/Sidebar/Rate/RateInfo.js, src/client/object/AppendCard.js, src/client/object/AppendForm.js, src/client/object/ObjectDynamicList.js, src/client/object/WobjHeader.js, src/client/user/UserExpertise.js, src/common/constants/listOfFields.js, src/waivioApi/ApiClient.js, src/waivioApi/config.json
…en we click in updates, add send button in comment editor
Fixes #
* Change 1
* Change 2
=> WAIV - [1754, 1764, 1767, 1774, 1707, 1687, 1791]

src/client/activity/UserActivitySearchLoading.js, src/client/activity/UserActivitySearchLoading.less, src/client/components/Navigation/Topnav.js, src/client/components/Sidebar/ObjectCreation/ObjectCreation.js, src/client/components/Sidebar/ObjectCreation/ObjectCreationLoading.js, src/client/components/Sidebar/ObjectCreation/ObjectCreationLoading.less, src/client/discoverObjects/DiscoverObjectsContent.js, src/client/user/User.js, src/investarena/components/CreatePostForecast/helpers.js, src/investarena/components/InstrumentsPage/Instrument/InstrumentCardView/InstrumentCardLoading.js, src/investarena/components/InstrumentsPage/Instrument/InstrumentCardView/InstrumentCardLoading.less, src/investarena/components/InstrumentsPage/Instrument/InstrumentCardView/instrumentCardView.less
Add 2 loaders and fixed date in "write post"
=> WAIV-1696 , WAIV-1732  

src/client/app/Reblog/reblogActions.js, src/client/app/Reblog/reblogReducers.js, src/client/feed/SubFeed.js, src/client/feed/feedActions.js, src/client/helpers/wObjectHelper.js, src/client/post/postActions.js, src/client/post/postsReducer.js, src/client/reducers.js, src/waivioApi/ApiClient.js
=> WAIV - [1650, 1390, 1397]

src/client/auth/authActions.js
=> Fixed notifications on IA

src/client/auth/authActions.js
=> Notifications fix on waiv

src/client/post/PostPreviewModal/PostPreviewModal.js
fixed button`s enabling/disabling for post
=> fixed post`s bug

src/client/components/UserCard.js, src/client/components/UserHeader.js, src/client/helpers/wObjectHelper.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/WobjExpertise.js, src/client/object/WobjFollowers.js, src/client/object/wObjectHelper.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/user/User.js, src/client/user/UserDynamicList.js, src/client/user/UserFollowing.js, src/client/user/UserHero.js, src/client/user/userActions.js, src/client/user/userReducer.js, src/client/user/usersActions.js, src/client/user/usersReducer.js, src/client/widgets/FollowButton.js, src/waivioApi/ApiClient.js
=> WAIV-[1408, 1324, 1375, 1395]

src/client/components/Navigation/Topnav.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/wallet/UserWalletSummary.js, src/client/wallet/UserWalletSummary.less, src/investarena/components/TradingForm/TradingForm.js, src/investarena/components/TradingForm/TradingForm.less
https://maxiproject.atlassian.net/browse/WAIV-1800
=> Wallet btn [WAIV-1800]

src/client/app/Sidebar/UserInfo.js, src/client/components/Navigation/Topnav.js, src/client/locales/default.json, src/client/locales/ru-RU.json
https://maxiproject.atlassian.net/browse/WAIV-1797
=> Long term message edit [WAIV-1797]

src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.js, src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.less, src/client/components/Authorization/ModalSignIn/ModalSignIn.js
https://maxiproject.atlassian.net/browse/WAIV-1775
=> Modal edit [WAIV-1775]

src/client/components/Navigation/Topnav.js, src/client/post/PostPreviewModal/PostPreviewModal.js
https://maxiproject.atlassian.net/browse/WAIV-1802
=> Edit creating post [WAIV-1802]

src/client/components/Navigation/Notifications/NotificationFillOrder.js, src/client/components/Navigation/Notifications/NotificationPowerDown.js, src/client/helpers/notificationsHelper.js, src/client/notifications/Notifications.js, src/client/styles/common.less
=> WAIV-1616, WAIV-1419

src/client/wallet/UserWalletSummary.js, src/investarena/components/TradingForm/TradingForm.js
=> Changed wallet links

src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm-nightmode.less, src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.less, src/client/post/EditPost/EditPost.js
https://maxiproject.atlassian.net/browse/WAIV-1801
=> Add object in editor [WAIV-1801]

src/client/components/Story/Body.less, src/client/components/Story/BodyShort.js
https://maxiproject.atlassian.net/browse/WAIV-1803
=> Parsed post message [WAIV-1803]

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Sidebar/CryptoChart.js, src/client/components/Story/Body.js, src/client/components/StoryFooter/Buttons.js, src/client/components/StoryFooter/StoryFooter.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendCard.js, src/client/object/ObjectGallery/Album.js, src/client/object/ObjectGallery/ObjectGallery.js, src/client/object/ObjectGallery/ObjectGalleryAlbum.js, src/client/object/wObjectHelper.js, src/client/object/wobjActions.js, src/client/object/wobjectReducer.js
=> WAIV-[1634, 1764, 1827, 1809, 1825]

src/client/activity/UserActivityActionsLoader.js, src/client/components/EditorExtended/util/editorStateToMarkdown.js, src/client/components/Story/Body.js, src/client/components/Story/StoryFull.js
=> Waiv - [1384]

src/client/app/Sidebar/ObjectInfo.js, src/client/auth/authActions.js, src/client/components/Navigation/Topnav.js, src/client/components/StoryFooter/Buttons.js, src/client/helpers/wObjectHelper.js, src/client/object/wobjectReducer.js, src/client/settings/ProfileSettings.js, src/client/settings/Settings.js
=> fix front crash and WAIV - 1864

src/client/post/PostPreviewModal/PostPreviewModal.js
=> Quick fix post create

src/client/components/ImageSetter/ImageSetter.js, src/client/components/ImageSetter/ImageSetter.less
=> 1672 fixed image-preview width

src/client/components/Sidebar/PostRecommendation.js, src/client/feed/LetsGetStarted.js, src/client/locales/default.json, src/client/locales/ru-RU.json
=> 1772 1790 getStarted, recommended posts for guests

src/client/components/Story/Body.js, src/client/helpers/postHelpers.js, src/client/post/PostPreviewModal/PostPreviewModal.js
https://maxiproject.atlassian.net/browse/WAIV-1803
=> Separate guest comments [WAIV-1803]

src/client/post/EditPost/EditPost.js
https://maxiproject.atlassian.net/browse/WAIV-1801
=> Added beaxy obj

src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/post/Write/editorActions.js
=> added notify

src/client/__tests__/reducers/fromAuth.js, src/client/auth/authActions.js, src/client/auth/authReducer.js, src/client/discover/DiscoverContent.js, src/client/discover/DiscoverUser.js, src/client/helpers/apiHelpers.js, src/client/post/Post.js, src/client/post/PostModal.js, src/client/settings/ProfileSettings.js, src/client/user/User.js, src/waivioApi/ApiClient.js
=> 1867 fixed User component + updates from CIA

src/client/feed/LetsGetStarted.js, src/client/locales/default.json, src/client/locales/ru-RU.json
=> 1773 LetsGetStarted for guests

src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.js
https://maxiproject.atlassian.net/browse/WAIV-1885
=> Header fix on auth [WAIV-1885]

src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.js, src/investarena/redux/actions/brokersActions.js
=> On logout fix/On error event fix

src/client/post/EditPost/EditPost.js
=> Removed beaxy object

src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFees.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRow.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRowTotal.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRow.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRowTotal.js, src/client/rewards/Reports/Reports.js, src/client/rewards/Reports/Reports.less, src/client/rewards/Reports/ReportsForm.js
=> Fix reports

src/client/components/Story/StoryPreview.js
=> 1762 fixed SteemPress posts preview

src/client/post/PostPreviewModal/PostPreviewModal.js
https://maxiproject.atlassian.net/browse/WAIV-1921
=> Edit post preview [WAIV-1921]

src/client/components/Comments/Comment.less
https://maxiproject.atlassian.net/browse/WAIV-1936
=> Edit quick comment [WAIV-1936]

src/client/components/HeroBannerSlider.less, src/client/feed/Feed.less
https://maxiproject.atlassian.net/browse/WAIV-1931
=> Fix up btn / banner [WAIV-1931] 

src/client/comments/commentsActions.js
https://maxiproject.atlassian.net/browse/WAIV-1937
=> Edited fake comment [WAIV-1937]

src/client/components/AvatarLightbox.js, src/client/components/UserHeader.js, src/client/user/User.js, src/client/user/UserHero.js
https://maxiproject.atlassian.net/browse/WAIV-1930
=> Guest avatar fix [WAIV-1930]

src/client/app/Sidebar/UserInfo.js, src/client/helpers/postingMetadata.js, src/client/settings/ProfileSettings.js, src/client/user/User.js
=> 1914 fixed lost profile data

src/client/comments/commentsActions.js, src/client/components/Navigation/MobileMenu/LoggedMenuMobile/LoggedMenuMobile.js
https://maxiproject.atlassian.net/browse/WAIV-1939
=> Edit discover page routes [WAIV-1939]

src/client/rewards/Details/Details.js, src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/Report/ReportHeader/ReportHeader.less, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFees.less, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRow.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRowTotal.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.less, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRow.js
=> Fix reopend 1632

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Navigation/Topnav.js, src/client/components/ObjectAvatar.js, src/client/components/ObjectLightbox.js, src/client/components/Sidebar/ObjectCard.js, src/client/components/Sidebar/Rate/RateInfo.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendForm.js, src/client/object/AppendFormFooter.js, src/client/object/LikeSection.js, src/client/object/ObjectGallery/CreateImage.js, src/client/object/TagCategory/CreateTag.js, src/client/object/WobjHeader.js, src/client/object/WobjHistory.js, src/client/object/appendActions.js, src/client/object/wobjActions.js, src/client/object/wobjectReducer.js, src/waivioApi/ApiClient.js
…nt avatar
Fixes #
* Change 1
* Change 2
=> WAIV - [1907, 1891, 1880, 1933]

src/client/app/Sidebar/TopInstruments.js, src/client/components/Navigation/MobileNavigation/MobileNavigation.js, src/client/components/Navigation/MobileNavigation/MobilePerformens/HomeBar/HomeBar.js, src/client/components/Navigation/MobileNavigation/PerformerItem/PerformerItem.js, src/client/components/Navigation/MobileNavigation/PerformerItem/PerformerItem.less, src/client/components/Sidebar/SidebarContentBlock.less, src/client/styles/styles-shortcodes.less
https://maxiproject.atlassian.net/browse/WAIV-1735
=> Edited nav menu [WAIV-1735]

src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js, src/client/object/ApprovingCard.js
=> WAIV - [1699, 1907]

src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRowTotal.js, src/client/rewards/Reports/Reports.js, src/client/rewards/Reports/Reports.less, src/client/rewards/Reports/ReportsForm.js, src/client/styles/common-nightmode.less
=> Fix reopend 1680

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Reactions/ReactionsList.js, src/client/components/StoryFooter/Buttons.js, src/client/object/ApprovingCard.js, src/client/object/ObjectGallery/Album.js, src/client/object/ObjectGallery/ObjectGalleryAlbum.js, src/client/object/WobjHeader.js, src/client/object/wobjectReducer.js
=> WAIV - [1948, 1959, 1634,  1957]

src/client/rewards/rewardsHelper.js
=> fixed 1920

src/client/components/Authorization/BeaxyAuthForm/BeaxyAuthForm.js, src/client/components/Authorization/SignUpButton/SignUpButton.js
=> fixed 1857 1966

src/client/components/Comments/Comment.js
https://maxiproject.atlassian.net/browse/WAIV-1944
=> Edit comment [WAIV-1944]

src/client/components/Reactions/ReactionsList.js, src/client/components/Story/Story.js, src/client/components/Story/StoryFull.js, src/client/object/wobjectReducer.js
=> WAIV - 1959

src/client/components/PayoutDetail.js, src/client/components/StoryFooter/Payout.js, src/client/vendor/steemitHelpers.js
=> 1966 fixed post's payout

src/client/helpers/postHelpers.js, src/client/post/EditPost/EditPost.js, src/client/post/EditPost/EditPost.less, src/client/wallet/walletReducer.js
https://maxiproject.atlassian.net/browse/WAIV-1801
=> Editor fix [WAIV-1801]

src/client/app/Sidebar/RightSidebar.js, src/client/components/Sidebar/ObjectCard.js, src/client/components/Sidebar/ObjectWeightBlock.js, src/client/components/Story/Story.js, src/client/object/ObjectDynamicList.js, src/client/object/WobjHeader.js, src/client/object/wobjActions.js, src/client/object/wobjectReducer.js, src/client/user/UserExpertise.js, src/client/user/UserFollowing.js, src/client/widgets/FollowButton.js, src/waivioApi/ApiClient.js
=> WAIV - [1879, 1861]

src/client/post/PostPreviewModal/BeneficiariesFindUsers.js, src/client/post/PostPreviewModal/BeneficiariesWeights.js, src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/rewardsHelper.js, src/client/user/userActions.js
=> Waiv 1982,1981,1984,1995,2000,2001

src/client/components/Navigation/NewsOverlay-nightmode.less, src/client/components/Navigation/NewsOverlay.less, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/post/PostPreviewModal/PostPreviewModal.js
https://maxiproject.atlassian.net/browse/WAIV-1993
https://maxiproject.atlassian.net/browse/WAIV-1892
=> WAIV-1993, WAIV-1892

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/rewards/Create-Edit/validators.js, src/client/rewards/Debts/Debts.js, src/client/rewards/Details/DetailsBody.js, src/client/rewards/Payment/PaymentTable/PaymentTable.js, src/client/rewards/Payment/PaymentTable/PaymentTable.less, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/rewards/Report/Report.js, src/client/rewards/Report/ReportFooter/ReportFooter.js, src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/Report/ReportHeader/ReportHeader.less, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFees.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.js, src/client/rewards/Reports/Reports.less, src/client/rewards/rewardsHelper.js
=> Waiv 1978,1979,1853,1924,1987

src/client/components/Sidebar/LastDrafts.less, src/client/components/Story/StoryFull.js
=> fixed WV-1730, WV-1769

src/client/components/Editor/EditorToolbar.js, src/client/components/Editor/EditorToolbar.less
https://maxiproject.atlassian.net/browse/WAIV-1956
=> IA toolbar fix [WAIV-1956]

src/client/components/Editor/EditorToolbar.js, src/client/components/Editor/EditorToolbar.less
https://maxiproject.atlassian.net/browse/WAIV-2010
=> Post toolbar fix [WAIV-2010]

src/client/object/Wobj.js
https://maxiproject.atlassian.net/browse/WAIV-1750
=> Edit object [WAIV-1750]

src/client/app/Sidebar/ObjectInfo.js, src/client/components/ObjectAvatar.js, src/client/components/Reactions/ReactionsList.js, src/client/components/Reactions/ReactionsModal.js, src/client/components/Sidebar/Rate/RateInfo.js, src/client/components/StoryFooter/AppendObjButtons.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendCard.js, src/client/object/ApprovingCard.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/ObjectFeed/ObjectFeed.js, src/client/object/ObjectGallery/Album.js, src/client/object/ObjectGallery/GalleryAlbum.js, src/client/object/ObjectGallery/ObjectGallery.js, src/client/object/ObjectGallery/ObjectGalleryAlbum.js, src/client/object/WobjHeader.js, src/client/object/WobjHistory.js, src/client/object/wObjectHelper.js, src/client/object/wobjectReducer.js, src/client/reducers.js, src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/fieldsData.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/wallet/UserWalletTransactions.less
=> WAIV - [1957, 1997, 2015, 1634]

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/post/CheckReviewModal/CheckReviewModal.js, src/client/post/PostPreviewModal/AdvanceSettings.js, src/client/post/PostPreviewModal/AdvanceSettings.less, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/rewardsHelper.js, src/waivioApi/ApiClient.js
=> Waiv 1713,2031,2027,1978,2026

src/client/locales/default.json, src/client/locales/ru-RU.json
=> fixed locales

src/client/rewards/Manage/BalanceTable/BalanceTable.js, src/client/rewards/Rewards.js
=> Waiv 1854,dashboard

src/client/post/CheckReviewModal/CheckReviewModal.js, src/client/post/PostPreviewModal/AdvanceSettings.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Reports/ReportsForm.js, src/client/styles/common.less
=> Waiv fix2031,1713,1605,1680

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Reactions/ReactionsModal.js, src/client/components/Story/Story.js, src/client/components/StoryFooter/AppendObjButtons.js, src/client/helpers/wObjectHelper.js, src/client/settings/ProfileSettings.js
… view, fix redirect after save settings
Fixes #
* Change 1
* Change 2
=> WAIV - [1811, 1879, 1959,  2042]

src/client/feed/feedActions.js, src/client/feed/feedReducer.js, src/client/helpers/stateHelpers.js
=> Fixed inf scroll

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/locales/uk-UA.json, src/client/object/ObjectFeed/ObjectFeed.js, src/client/post/CheckReviewModal/CheckReviewModal.js, src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/fieldsData.js, src/client/rewards/Create-Edit/validators.js, src/client/rewards/Payment/PaymentTable/PaymentTable.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/rewards/Report/ReportFooter/ReportFooter.js, src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFees.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRowTotal.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRowTotal.js, src/client/rewards/Reports/Reports.js, src/client/rewards/Reports/ReportsForm.js
=> Waiv 2049,2050,2052,2068,2075,2056

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Reactions/ReactionsModal.js, src/client/components/StoryFooter/StoryFooter.less, src/client/feed/feedActions.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendForm.js, src/client/object/ApprovingCard.js, src/client/object/ObjectFeed/ObjectFeed.js, src/client/object/WobjHeader.js, src/client/object/wobjectReducer.js, src/client/object/wobjectsActions.js, src/client/settings/settingsReducer.js, src/client/vendor/steemitHelpers.js, src/common/constants/listOfFields.js
=> WAIV - [1378, 1785, 2054, 2065, 2072]

src/client/helpers/postHelpers.js, src/client/helpers/wObjInfluenceHelper.js, src/client/post/EditPost/EditPost.js
https://maxiproject.atlassian.net/browse/WAIV-1801
=> Fixed editor [WAIV-1801]

src/client/components/Navigation/MobileNavigation/MobileNavigation.js, src/client/components/Navigation/Sidenav.less, src/client/components/Sidebar/SidebarContentBlock.less, src/client/discover/Discover.js, src/client/discoverObjects/DiscoverObjects.js
https://maxiproject.atlassian.net/browse/WAIV-2106
=> Discover mobile fix [WAIV-2106]

src/client/object/WobjHistory.js, src/common/constants/listOfFields.js
https://maxiproject.atlassian.net/browse/WAIV-2100
=> Updates fix [WAIV-2100]

src/client/object/WobjHistory.js
https://maxiproject.atlassian.net/browse/WAIV-2100
=> Update fix [WIAV-2100]

src/investarena/redux/actions/brokersActions.js
=> Disconnect broker notification fix

src/client/locales/default.json, src/client/object/appendActions.js, src/client/post/Write/editorActions.js, src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/fieldsData.js, src/client/rewards/Create-Edit/validators.js, src/client/user/userActions.js
=> Waiv 2108,2114,2115

src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/rewards/Report/ReportHeader/ReportHeader-nightmode.less, src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/Report/ReportHeader/ReportHeader.less, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRow.js
=> Waiv 2121,2122,2098

src/client/components/Authorization/GuestSignUpForm/GuestSignUpModalContent.js, src/client/components/Avatar.js, src/client/post/Write/editorActions.js
https://maxiproject.atlassian.net/browse/WAIV-2099
=> Ava fix [WAIV-2099]

src/client/object/Wobj.js, src/client/post/PostContent.js, src/client/user/User.js
https://maxiproject.atlassian.net/browse/WAIV-1855
=> Links preview [WAIV-1855]

src/client/objectTypes/objectTypeActions.js, src/client/objectTypes/objectTypeReducer.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/Payment/Payment.js, src/client/rewards/Payment/PaymentTable/PaymentTable.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/rewards/Report/ReportFooter/ReportFooter.js, src/client/rewards/Report/ReportHeader/ReportHeader.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFees.less, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRow.js, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFeesRowTotal.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.less, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRow.js, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewardsRowTotal.js, src/client/rewards/Reports/ReportsForm.js, src/client/rewards/Rewards.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.js, src/client/rewards/rewardsHelper.js, src/client/user/userActions.js, src/waivioApi/ApiClient.js
=> Waiv 2126,2125,1584

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/settings/ProfileSettings.js
=> 2081 added saving profile settings with posting key

src/client/Wrapper.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/rewards/Create-Edit/CreateFormRenderer.js
=> 895 fixed CreateFormRenderer

src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/rewardsHelper.js
=> Waiv 2129,2132

src/client/app/appReducer.js, src/client/post/Write/editorActions.js, src/client/post/Write/editorReducer.js
https://maxiproject.atlassian.net/browse/WAIV-2111
=> Edited post actions [WAIV-2111]

src/client/object/Catalog/CatalogWrap.js, src/client/rewards/Rewards.js, src/client/user/userActions.js
=> Waiv 2154,2160

src/client/vendor/steemitHelpers.js
=> fixed 2163

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/locales/uk-UA.json, src/client/rewards/Blacklist/BlacklistFooter.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/Manage/BalanceTable/BalanceTable.js, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTable.js, src/client/rewards/Manage/Manage.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/rewards/Rewards.js, src/client/rewards/rewardsActions.js, src/client/rewards/rewardsHelper.js, src/client/steemConnectAPI.js, src/waivioApi/ApiClient.js
=> Waiv 2248,2267,2268,2070

src/client/rewards/Rewards.js
=> fixed 2251

src/client/object/ObjectFeed/ObjectFeed.js, src/client/rewards/FilteredRewardsList.js
=> fixed Object / Reward card

src/client/rewards/CampaignCardHeader/CampaignCardHeader.js
=> fixed 2267

src/client/components/WelcomeModal/WelcomeModal.js
=> WAIV-[2063]

src/client/object/Catalog/CatalogWrap.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/Payment/Payment.js, src/client/rewards/PaymentCard/PaymentCard.js, src/client/rewards/PaymentCard/PaymentCard.less, src/client/rewards/PaymentCard/TransferButton.js, src/client/rewards/Rewards.js, src/client/rewards/rewardsHelper.js
=> Waiv 2308,2305,2295

src/client/object/Wobj.js
=> Fix wobject description

src/client/discoverObjects/DiscoverFiltersSidebar/DiscoverFiltersSidebar.js
=> renamed mapData

src/client/components/StoryFooter/StoryFooter.js, src/client/helpers/metadata.js, src/client/post/EditPost/EditPost.js, src/client/vendor/steemitHelpers.js, src/client/wallet/WithDraw.js, src/waivioApi/ApiClient.js
=> add new formula for vote power, fix user metadata

src/client/Wrapper.js, src/client/auth/authActions.js, src/client/auth/authReducer.js, src/client/helpers/metadata.js, src/client/user/usersActions.js, src/client/wallet/WithDraw.js, src/waivioApi/ApiClient.js
=> fix notification, update email after requers

src/client/rewards/Payables/Payables.js
=> fixed 2380

src/client/locales/ru-RU.json, src/client/wallet/WithDraw.js, src/client/wallet/Withdraw.less, src/client/widgets/ConfirmationModal.js, src/client/widgets/EmailConfirmation.js
=> WAIV - [2377]

package.json, src/client/components/Navigation/Topnav.js
fixed transition when pressing enter
=> fix search by user

src/client/components/StoryFooter/Buttons.js
add icon re-blog with counter on own posts
=> add icon "re-blog" with counter

src/waivioApi/ApiClient.js
=> add icon "add app in headers

src/client/components/Story/Story.js
add Re-blog label to rebloged posts
=> add label Reblog

src/client/components/StoryFooter/Buttons.js
fix counter and pop up in Re-blog
=> fix counter and pop up in Re-blog

src/client/components/StoryFooter/Payout.js, src/client/settings/Settings.js, src/client/wallet/Transfer.js, src/client/wallet/WithDraw.js, src/client/wallet/Withdraw.less, src/client/widgets/ConfirmationModal.js
=> WAIV - [2457, 2409, 2443]

src/client/components/Story/Story.js, src/client/styles/common.less
=> add label Re-bloged

src/client/components/PostPopoverMenu/PostPopoverMenu.less, src/client/discover/DiscoverUser.js, src/client/objectCard/ObjectCardView.js, src/client/post/Post.js, src/client/styles/custom.less, src/client/user/UserReblogModal.js, src/client/user/UserReblogModal.less
=> WAIV - [2317, 2518, 2507]

src/client/rewards/RewardsComponent/RewardsComponent.js
=> fixed urgent

src/client/reducers.js, src/client/user/UserWallet.js, src/client/wallet/UserWalletTransactions.js, src/client/wallet/walletActions.js, src/client/wallet/walletReducer.js
WAIV-2048 actually is finished but not in staging
=> WAIV-2520, WAIV-2048

src/client/post/PostContent.js
=> 2316 FB previews

src/client/components/Navigation/GuestSignUpForm/GuestSignUpFormContent.js
fix registration form , nickname field
=> fix registration form , nickname field

src/client/components/CommentFooter/CommentFooter.js, src/client/components/Slider/Slider.js, src/client/components/StoryFooter/StoryFooter.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/AppendCard.js, src/client/vendor/steemitHelpers.js
=> WAIV - [2179, 2471, 2554, 2252, 2532, 2472]

src/client/components/AvatarLightbox.js
=> 2406 fixed guest lightbox

src/client/components/Sidebar/SidebarContentBlock-nightmode.less, src/client/components/Sidebar/SidebarContentBlock.less, src/client/components/Sidebar/SidebarMenu/SidebarMenu.js, src/client/components/Sidebar/SidebarMenu/SidebarMenu.less, src/client/discoverObjects/DiscoverObjects.less, src/client/styles/mixins.less
=> 2530 menu show more

src/client/locales/default.json, src/client/rewards/Payment/Payment.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/rewards/PaymentCard/TransferButton.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Report/ReportFooter/ReportFooter.js, src/client/rewards/Rewards.js, src/client/rewards/rewardsHelper.js, src/client/user/userActions.js, src/common/constants/rewards.js, src/waivioApi/ApiClient.js
=> Waiv 2487,2488,2553,2539,2563

src/client/rewards/Proposition/Proposition.js
=> fixed getJsonData

src/common/constants/accountHistory.js, src/waivioApi/ApiClient.js
=> 2437 fix user settings

src/client/components/Slider/Slider.js, src/client/components/StoryFooter/Payout.js, src/client/post/PostPreviewModal/AdvanceSettings.js, src/client/post/PostPreviewModal/BeneficiariesWeights.js, src/waivioApi/ApiClient.js
=> WAIV - [2472, 2252]

src/client/components/StoryFooter/Payout.js, src/client/object/AppendCard.js
=> WAIV - [2471, 2252]

src/client/components/PayoutDetail.js
=> Waiv high bugs

src/client/components/CommentFooter/CommentFooter.js, src/client/components/PayoutDetail.js, src/client/wallet/WithDraw.js
=> fix slider for comment

src/client/discoverObjects/DiscoverObjects.less, src/common/constants/accountHistory.js, src/waivioApi/ApiClient.js
=> 2081 fixed guest settings

src/client/wallet/WithDraw.js, src/waivioApi/ApiClient.js
=> fixed payables

src/client/components/StoryFooter/Payout.js, src/client/vendor/steemitHelpers.js, src/client/wallet/WithDraw.js, src/client/widgets/EmailConfirmation.js
=> WAIV - [2508, 2597, 2598, 2599, 2601]

src/client/auth/authReducer.js, src/client/wallet/WithDraw.js, src/client/wallet/Withdraw-nightmode.less, src/client/wallet/Withdraw.less
=> 2600 fixed withdraw modal

src/client/components/Maps/Map.js
=> Waiv deleted extra request for map

src/client/rewards/Payment/Payment.js
=> fixed data for payables request getLenders and title for payables

src/client/rewards/FilteredRewardsList.js, src/client/rewards/History/History.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.js, src/client/user/userActions.js, src/common/constants/rewards.js
=> fixed some bugs

src/client/wallet/UserWalletTransactions.js, src/client/wallet/WithDraw.js, src/client/wallet/Withdraw-nightmode.less, src/client/wallet/Withdraw.less, src/client/widgets/EmailConfirmation.js
=> 2639 fixed transfer

src/client/settings/ProfileSettings.js
=> 2437 fixed notification

src/client/Wrapper.js, src/client/wallet/Transfer.js
=> fixed 2561

src/client/components/PopoverMenu/PopoverMenuItem.less, src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/History/History.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.less, src/client/rewards/rewardsHelper.js, src/common/constants/rewards.js
=> Waiv 2002fix

src/client/components/Navigation/MobileNavigation/MobileNavigation.js, src/client/rewards/FilterModal.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/History/History.js, src/client/rewards/Rewards.js, src/client/rewards/RewardsComponent/RewardsComponent.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.js, src/common/constants/rewards.js
=> Waiv 2565, 2662

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/locales/uk-UA.json, src/client/rewards/Report/Report.js, src/client/rewards/Report/Report.less, src/client/rewards/Report/ReportHeader/ReportHeader.less, src/client/rewards/Report/ReportTable/ReportTableFees/ReportTableFees.less, src/client/rewards/Report/ReportTable/ReportTableRewards/ReportTableRewards.less
=> Waiv 2680, 1999

src/client/rewards/Blacklist/BlacklistContent.js
=> fixed 2566

src/client/components/Navigation/SidenavRewards.js, src/waivioApi/ApiClient.js
=> Waiv 2671, 2765

src/client/rewards/CampaignFooter/CampaignButtons.js
=> fixed function name

src/client/post/CreateObjectModal/CreateObject.js
=> WAIV - 2778

src/client/object/Catalog/CatalogWrap.js, src/client/object/Catalog/CatalogWrap.less, src/client/rewards/Create-Edit/CreateReward.less, src/client/rewards/Reports/Reports.less, src/client/rewards/Rewards.less
=> Waiv 2767, 2785

src/client/rewards/Rewards.js, src/client/rewards/RewardsComponent/RewardsComponent.js
=> fixed filters

src/client/rewards/CampaignFooter/CampaignFooter.js
=> Waiv fix reservation

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/locales/uk-UA.json, src/client/post/EditPost/EditPost.js, src/client/post/PostModal.less
=> Waiv 2825, 2824

src/client/rewards/CampaignFooter/CampaignFooter.js
=> WAIV - [2908]

src/client/rewards/Details/DetailsBody.js, src/client/rewards/Rewards.js
=> fixed 2860

src/client/Wrapper.js, src/client/app/Sidebar/ObjectInfo.js, src/client/app/Sidebar/RightSidebar.js, src/client/components/Maps/CustomMarker/CustomMarker.js, src/client/components/Navigation/Topnav.js, src/client/components/ObjectAvatar.js, src/client/components/Sidebar/ObjectCard.js, src/client/components/Sidebar/ObjectWeightBlock.js, src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js, src/client/components/Story/Story.js, src/client/helpers/wObjectHelper.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/AppendCard.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/WobjHeader.js, src/client/object/WobjHistory.js, src/client/object/wObjectHelper.js, src/client/object/wobjectReducer.js, src/client/object/wobjectsActions.js, src/client/objectCard/ObjectCardView.js, src/client/objectTypes/objectTypesActions.js, src/client/objects/WaivioObject.js, src/client/search/searchActions.js, src/client/user/UserExpertise.js, src/client/user/UserWallet.js, src/client/user/userActions.js, src/client/widgets/ErrorBoundary.js, src/waivioApi/ApiClient.js
=> WAIV - [2713, 2863, 2913]

src/client/components/WeightTag.js
=> fix total payout

src/client/components/ObjectLightbox.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/ObjectFeed/ObjectFeed.js, src/client/object/ObjectFeed/index.js, src/client/object/Wobj.js, src/client/objectCard/ObjectCardView.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js, src/client/rewards/RewardsBreadcrumb/RewardBreadcrumb.js
=> Waiv 2948,2947,2958

src/client/components/Navigation/SidenavRewards.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/locales/uk-UA.json, src/client/post/CheckReviewModal/CheckReviewModal.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/Details/Details.js, src/client/rewards/FilterModal.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.js, src/client/rewards/rewardsHelper.js, src/common/constants/rewards.js
=> Waiv 2956,2990,2981,2991,2996

src/client/rewards/Debts/Debts.js, src/client/rewards/Payment/Payment.js
=> fixed 3026

src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/CampaignCardHeader/CampaignCardHeader.less, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Proposition/Proposition.less, src/client/rewards/Reports/Reports.less
=> Waiv 2570fix

src/client/comments/Comments.js, src/client/comments/commentsActions.js, src/client/components/Comments/Comments.js, src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/common/constants/rewards.js
=> Waiv 2910new, 3006

src/client/Wrapper.js, src/client/components/Navigation/MobileNavigation/MobileNavigation.js, src/client/components/Navigation/TopNavigation.js, src/client/components/Sidebar/InterestingPeople.js, src/client/discover/Discover.js, src/client/discoverObjects/SidenavDiscoverObjects.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Debts/Debts.js, src/client/rewards/FilterModal.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/History/History.js, src/client/rewards/PaymentCard/TransferButton.js, src/client/rewards/Rewards.js, src/client/rewards/RewardsFiltersPanel/RewardsFiltersPanel.js, src/client/rewards/rewardsHelper.js, src/common/constants/rewards.js, src/common/routes.js
=> Waiv 2672fix

src/client/object/ObjectFeed/ObjectFeed.js, src/client/object/PicturesCarousel.js, src/client/post/PostModal.less, src/waivioApi/ApiClient.js
=> Waiv 3051,3050

src/client/auth/authActions.js, src/client/auth/authReducer.js, src/client/reducers.js, src/client/user/UserDynamicList.js, src/client/user/UserDynamicList.less, src/client/user/UserFollowers.js, src/client/user/UserFollowing.js, src/common/constants/waivioFiltres.js, src/waivioApi/ApiClient.js
fix followers, following user list
=> fix followers, following user list

src/client/components/Navigation/ModlaSignIn/ModalSignIn.js, src/client/locales/default.json, src/client/user/UserFollowing.js
fix bag with tabs in following
=> WAIV-2595, WAIV-2976

src/client/rewards/Payment/Payment.js, src/client/rewards/Reports/Reports.less, src/client/wallet/Transfer.js
=> Waiv 2570, 3101

src/client/app/Sidebar/ObjectInfo.js, src/client/comments/Comments.js, src/client/components/Comments/Comments.js, src/client/components/ObjectMenu.js, src/client/object/AppendCard.js, src/client/object/AppendForm.js, src/client/object/ApprovingCard.js, src/client/object/WobjHeader.js, src/client/object/WobjHistory.js, src/client/object/appendActions.js, src/client/object/wobjActions.js, src/client/object/wobjectReducer.js, src/client/object/wobjectsActions.js, src/common/constants/listOfFields.js
=> WAIV - [3068, 3115, 3116]

src/client/comments/commentsActions.js, src/client/components/EditorExtended/components/blocks/image.less, src/client/feed/feedActions.js, src/client/object/ObjectGallery/galleryActions.js, src/client/object/wobjectsActions.js, src/client/objects/ObjectList.js, src/client/search/searchActions.js, src/client/user/UserFollowing.js, src/client/user/userActions.js, src/waivioApi/ApiClient.js
=> add follower in requests

src/client/components/Maps/Map.js, src/client/rewards/Details/DetailsBody.js, src/client/rewards/rewardsHelper.js
=> Waiv 3122,3103,3113

src/client/app/Sidebar/ObjectInfo.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/ObjectGallery/CreateImage.js, src/client/object/ObjectGallery/ObjectGallery.js, src/client/object/ObjectGallery/ObjectGalleryAlbum.js, src/client/objectTypes/objectTypeActions.js, src/common/constants/listOfFields.js
=> fix object menu

src/client/object/AppendForm.less, src/client/object/Catalog/CatalogWrap.js, src/client/object/wObjectHelper.js, src/client/objectCard/ObjectCardView.js, src/client/post/CreateObjectModal/CreateObject.js
fix add object to list
fix modal window adding social links
=> WAIV-3052, WAIV-3129, WAIV-3071

src/client/components/ObjectAvatar.js, src/client/objectCard/ObjectCardView.js
=> WAIV - [3094, 3097, 3099]

src/client/app/Sidebar/ObjectInfo.js, src/client/object/Catalog/CatalogWrap.js
=> WAIV - [3145]

src/client/object/Catalog/CatalogWrap.js, src/client/object/wObjectHelper.js, src/waivioApi/ApiClient.js
fix object with type list, add sorting
=>  WAIV-3117, WAIV-3140

src/client/components/Navigation/Topnav.js, src/client/components/Sidebar/ObjectCard.js, src/client/components/Story/Story.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/Wobj.js, src/client/object/WobjHeader.js, src/client/object/wobjectReducer.js, src/client/objectCard/ObjectCardView.js, src/client/objects/WaivioObject.js, src/client/reducers.js, src/waivioApi/ApiClient.js
=> WAIV - [3061, 3087]

src/client/components/Story/StoryFull.js, src/client/discoverObjects/DiscoverObjectsContent.js, src/client/object/Catalog/CatalogWrap.js, src/client/objectCard/ObjectCardView.js, src/client/post/Post.js, src/client/post/postActions.js, src/client/rewards/Campaign/Campaign.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/Rewards.js, src/client/rewards/rewardsHelper.js, src/common/constants/rewards.js, src/waivioApi/ApiClient.js
=> Waiv 2713,3038,3124,3119,3108

src/client/components/LinkButton/LinkButton.js, src/client/components/Story/StoryPreview.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/Catalog/CategoryItemView/CategoryItemView.js, src/client/objectCard/ObjectCardView.js
=> Waiv 3060, WAIV-3131

src/client/app/Sidebar/ObjectInfo.js, src/client/objectCard/ObjectCardView.js, src/common/constants/listOfFields.js
=> add website, fix menu button

src/client/components/Story/StoryFull.js
=> Waiv fix proposition posts

src/client/object/WobjHeader.js
=> delete backgrount for hashtag

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Sidebar/ObjectCard.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendForm.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/WobjHeader.js, src/client/objectCard/ObjectCardView.js
=> Waiv cust sort

src/client/comments/commentsActions.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/CampaignFooter/CommentsMessages.js
=> Waiv 3118, 3164

src/client/rewards/Proposition/Proposition.js
=> fixed 3138

src/client/bookmarks/Bookmarks.js, src/client/components/Story/StoryFull.js, src/client/post/postsReducer.js
=> WAIV - [3149, 3171]

src/client/object/ObjectFeed/ObjectFeed.js, src/client/objectCard/ObjectCardView.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/Rewards.js
=> Waiv 3167,3166

src/client/Wrapper.js, src/client/bookmarks/Bookmarks.js, src/client/components/Story/Story.js, src/client/object/ApprovingCard.js, src/client/post/postActions.js, src/client/post/postsReducer.js
=> WAIV - [2856]

src/client/app/Sidebar/RightSidebar.js, src/client/components/Navigation/TopNavigation.js, src/client/components/Reactions/ReactionsList.js, src/client/feed/feedActions.js, src/client/feed/feedReducer.js, src/client/object/ObjectFeed/ObjectFeed.js, src/client/post/postsReducer.js, src/client/vendor/ReduxInfiniteScroll.js
=> WAIV - [3038, 3149, 3177, 3149]

src/client/components/Sidebar/PostRecommendation.less, src/client/components/Sidebar/PostRecommendationLink.js, src/client/discoverObjects/SidenavDiscoverObjects.js, src/client/objectTypes/objectTypeReducer.js
=> WAIV - [3173, 3174]

src/client/post/Post.js, src/client/post/postsReducer.js
=> WAIV - [3176]

src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Proposition/Proposition.js
=> Waiv 3184,3185,3186

src/client/components/Sidebar/PostRecommendationLink.js, src/client/discoverObjects/SidenavDiscoverObjects.js
=> fix img in recomend post and discover sidebar

src/client/components/Story/StoryFull.js, src/client/discoverObjects/DiscoverObjectsContent.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/ObjectFeed/ObjectFeed.js, src/client/rewards/CampaignFooter/CampaignFooter.less, src/client/rewards/CampaignFooter/CommentsMessages.js, src/client/rewards/Payment/Payment.js, src/client/rewards/Payment/PaymentTable/PaymentTableRow.js, src/client/wallet/Transfer.js
=> Waiv 3199,3198,3191,3205,3000

src/client/rewards/CampaignFooter/CampaignFooter.less, src/client/rewards/Rewards.js, src/client/steemConnectAPI.js, src/waivioApi/ApiClient.js
=> Waiv 3166,3205

src/client/discoverObjects/DiscoverFiltersSidebar/FilterItem.js, src/client/discoverObjects/helper.js, src/client/objectCard/ObjectCardView.js, src/client/post/Write/editorActions.js
=> WAIV - [3232, 3182, 2861]

src/client/Wrapper.js, src/client/auth/authActions.js, src/client/auth/authReducer.js, src/client/settings/settingsReducer.js
=> WAIV - [2038]

src/client/post/PostPreviewModal/AdvanceSettings.js, src/client/post/Write/editorActions.js
=> fix hive present

src/client/components/PostPopoverMenu/PostPopoverMenu.js
=> fix WAIV-3225

src/client/feed/Feed.js, src/client/object/ObjectFeed/ObjectFeed.js, src/client/rewards/Payment/Payment.js, src/client/user/UserWallet.js, src/client/wallet/PowerUpOrDown.js, src/client/wallet/Transfer/Transfer-nightmode.less, src/client/wallet/Transfer/Transfer.js, src/client/wallet/Transfer/Transfer.less
=> Waiv - 3253

src/client/object/Catalog/CatalogWrap.js, src/client/user/UserWallet.js, src/client/wallet/BlocktraidsTransactionModal.js, src/client/wallet/UserWalletTransactions.js, src/client/wallet/Withdraw/WithDraw.js, src/client/wallet/Withdraw/Withdraw-nightmode.less, src/client/wallet/Withdraw/Withdraw.less, src/waivioApi/ApiClient.js
=> Waiv - [2715]

src/client/post/CheckReviewModal/CheckReviewModal.js
=> WAIV - [3296]

src/client/helpers/regexHelpers.js, src/client/object/AppendForm.js, src/client/post/CheckReviewModal/CheckReviewModal.js, src/client/post/EditPost/EditPost.js, src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/post/Write/editorActions.js, src/client/reducers.js, src/client/rewards/Details/Details.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/rewardsActions.js, src/client/rewards/rewardsHelper.js, src/client/rewards/rewardsReducer.js
=> finish work

src/client/helpers/regexHelpers.js, src/client/object/Catalog/AddItemModal/AddItemModal.js, src/client/object/Catalog/CatalogWrap.js, src/client/post/CheckReviewModal/CheckReviewModal.js, src/client/post/EditPost/EditPost.js, src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/reducers.js, src/client/rewards/Details/Details.js, src/client/rewards/Proposition/Proposition.js, src/client/rewards/rewardsActions.js, src/client/rewards/rewardsHelper.js, src/client/rewards/rewardsReducer.js
=> Waiv review

src/client/components/EditorExtended/EditorExtended.js, src/client/objectCard/ObjectCardView.js, src/client/post/EditPost/EditPost.js, src/client/rewards/Details/Details.js, src/client/rewards/Details/DetailsPostRequirments.js, src/client/rewards/rewardsHelper.js, src/client/user/userActions.js
=> Waiv 3000, 3262, 3399

src/client/helpers/wObjectHelper.js
=> Waiv fix avatar

src/client/rewards/Rewards.js
=> fixed 3240

src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/client/rewards/Manage/CampaignRewardsTable/CampaignRewardsTableBodyRow.js, src/client/rewards/Rewards.js, src/common/constants/rewards.js
=> Waiv 3413, 3412, 3425

src/client/helpers/wObjectHelper.js
=> fixed getObjectName

src/client/objectCard/ObjectCardView.js, src/client/rewards/CampaignFooter/CampaignFooter.js, src/client/rewards/rewardsReducer.js
=> Waiv 3439,3448,3462

src/client/rewards/CampaignFooter/CampaignFooter.js
=> fixed 3469

src/client/components/Sidebar/PostRecommendation.js, src/client/helpers/wObjectHelper.js, src/client/object/Catalog/CatalogWrap.js
=> Waiv 3447,3429,3272

src/client/object/wObjectHelper.js, src/client/post/postActions.js, src/client/rewards/Report/ReportHeader/ReportHeader.less, src/client/rewards/Rewards.js, src/client/rewards/RewardsList/RewardsList.js, src/client/rewards/rewardsActions.js, src/client/rewards/rewardsReducer.js, src/waivioApi/ApiClient.js
=> Waiv 3452,3448,3255,3306,3451

src/client/discover/Discover.less
=> fix left sidebar[BR-14]

src/client/helpers/wObjectHelper.js, src/client/object/WobjHeader.js, src/client/object/wobjActions.js, src/client/object/wobjectReducer.js, src/client/object/wobjectsActions.js, src/client/steemConnectAPI.js, src/client/widgets/FollowButton.js, src/investarena/etc/client-config.json, src/server/index.js, src/waivioApi/ApiClient.js, webpack/configUtils.js
=> Crypto fix

src/client/components/EditorExtended/EditorExtended.js, src/client/components/EditorExtended/components/sides/ImageSideButton.js, src/client/components/EditorExtended/components/sides/ImageSideButton/ImageSideButton.js, src/client/components/EditorExtended/components/sides/ImageSideButton/ImageSideButton.less, src/client/components/EditorExtended/editor.js, src/client/components/EditorExtended/index.js, src/client/components/ImageSetter/ImageSetter.js, src/client/components/ImageSetter/ImageSetter.less, src/client/components/StoryFooter/Buttons.js, src/client/components/StoryFooter/Buttons.less, src/client/locales/default.json, src/client/locales/ru-RU.json
=> [BEAXY] BR-15

src/client/components/Authorization/SocialButtons/SocialButtons.js
=> [BEAXY] BR-1

src/client/rewards/CampaignCardHeader/CampaignCardHeader.js, src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/user/userActions.js
=> Waiv 3473,3226

src/client/settings/ProfileSettings.js
=> BEAXY [BR-16]

src/client/components/EditorExtended/components/sides/VideoSideButton.js, src/client/locales/default.json, src/client/locales/ru-RU.json, src/investarena/constants/selectData.js
=> BEAXY [BR-34]

src/client/object/AppendModal/AppendForm.js
fix post about adding list and page to the object
=> WAIV-3417, WAIV-3312

src/client/components/EditorObject/SearchObjectsAutocomplete.js
=> [BEAXY] BR-59

src/client/components/Sidebar/PostRecommendationLink.js
=> [BEAXY] BR-11

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/vendor/steemitHelpers.js, src/investarena/components/Modals/ModalComparePerformance/ModalComparePerformance.js
=> [BEAXY] BR-61, BR-34

src/client/app/Sidebar/UserInfo.js, src/client/components/CommentFooter/CommentFooter.js, src/client/components/Navigation/BurgerMenu.js, src/client/components/Slider/Slider.js, src/client/components/StoryFooter/StoryFooter.js, src/client/helpers/user.js, src/client/object/LikeSection.js, src/client/vendor/steemitHelpers.js
=> [BEAXY] BR-32, BR-28

src/client/object/WobjFollowers.js
=> [BEAXY] BR-37

src/client/object/AppendModal/AppendForm.js, src/client/object/WobjHistory.js, src/client/object/__tests__/AppendForm.test.js, src/client/object/__tests__/__snapshots__/AppendForm.test.js.snap
=> WAIV-3400, WAIV-3072

src/client/components/Navigation/Topnav.js, src/client/discoverObjects/DiscoverObjectsContent.js, src/client/discoverObjects/helper.js, src/client/object/Catalog/CatalogWrap.js, src/client/rewards/Proposition/PropositionList/PropositionListContainer.js, src/client/settings/GuestsSettings.js
=> Waiv - [3397, 3435]

src/client/statics/ExitPage.js
=> finish with WAIV-3392

src/client/styles/common.less
=> finish with WAIV-3415

src/client/object/wobjActions.js, src/client/steemConnectAPI.js
=> change approve method for hive users

src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/CreateRewardForm.js, src/waivioApi/ApiClient.js
=> WAIV-3574, WAIV-3488

src/client/object/Catalog/CatalogBreadcrumb/CatalogBreadcrumb.js, src/client/object/Catalog/CatalogWrap.js, src/client/rewards/Proposition/PropositionList/PropositionListFromCatalog.js
=> fix CatalogBreadcrumb

src/client/object/Catalog/CatalogWrap.js, src/client/objectCard/ObjectCardView.js, src/client/objectCard/__tests__/ObjectCardView.tests.js, src/client/objectCard/__tests__/__snapshots__/ObjectCardView.tests.js.snap
fix object permlink on card, fix UI in Catalog Wrap
=> WAIV-3573, WAIV-3589

src/client/Wrapper.js, src/client/components/Navigation/Topnav.js, src/client/components/PopoverMenu/PopoverMenu.less, src/client/components/PopoverMenu/PopoverMenuItem.less, src/client/components/__tests__/PopoverMenu.test.js, src/client/components/__tests__/PopoverMenuItem.test.js, src/client/components/__tests__/__snapshots__/PopoverMenu.test.js.snap, src/client/components/__tests__/__snapshots__/PopoverMenuItem.test.js.snap, src/client/locales/default.json, src/client/locales/ru-RU.json
fix topnav popover list and UI
=> WAIV-3597, WAIV-3598

src/client/rewards/Proposition/PropositionList/PropositionListFromCatalog.js
=> WAIV-3591, WAIV-3604

src/client/components/Sidebar/SidebarMenu/SidebarMenu.js
=> fix left sidebar

src/client/rewards/Proposition/PropositionList/PropositionList.js, src/client/rewards/Proposition/PropositionList/PropositionListContainer.js, src/client/rewards/Proposition/PropositionList/PropositionListFromCatalog.js
=> WAIV-3556, WAIV-3629

src/client/components/Editor/withEditor.js
=> fix images

src/client/components/SortSelector/SortSelector.js, src/client/rewards/FilteredRewardsList.js, src/client/rewards/Proposition/PropositionList/PropositionList.js, src/client/rewards/rewardsHelper.js
=> WAIV-3654, WAIV-3652

src/client/components/EditorExtended/EditorExtended.js, src/client/components/EditorExtended/util/editorHelper.js
=> Waiv 3664 links

src/client/feed/feedActions.js
=> fix WAIV-3644

src/client/helpers/wObjectHelper.js, src/client/object/AppendModal/AppendForm.js, src/client/object/ObjectGallery/CreateImage.js
=> added default album

src/client/components/Navigation/ModlaSignIn/ModalSignIn.js
=> WAIV-3675 hot fix

src/client/components/Navigation/SettingsSidenav/SettingsSidenav.js, src/client/invite/Invite.js, src/client/post/Write/Drafts.js, src/client/settings/GuestsSettings.js, src/client/settings/NotificationSettings.js, src/client/settings/ProfileSettings.js, src/client/settings/Settings.js, src/client/settings/SettingsMain.js, src/client/settings/WebsiteSettings.js, src/client/settings/common/helpers.js, src/client/websites/WebsiteTools/Administrators/Administrators.js, src/client/websites/WebsiteTools/Administrators/Administrators.less, src/client/websites/WebsiteTools/Authorities/WebsitesAuthorities.less, src/client/websites/WebsiteTools/Configuration/WebsitesConfigurations.js, src/client/websites/WebsiteTools/Create/CreateWebsite.js, src/client/websites/WebsiteTools/Manage/ManageWebsite.js, src/client/websites/WebsiteTools/Moderators/WebsiteModerators.js, src/client/websites/WebsiteTools/Moderators/WebsiteModerators.less, src/client/websites/WebsiteTools/Reports/ReportsWebsite.js, src/client/websites/WebsiteTools/Settings/WebsitesSettings.js, src/client/websites/websiteActions.js, src/common/routes/components.js, src/common/routes/routes.js
=> Waiv website

src/client/components/Navigation/SettingsSidenav/SettingsSidenav.js, src/client/websites/WebsiteTools/Create/CreateWebsite.js, src/client/websites/websiteActions.js, src/client/websites/websiteReducer.js, src/waivioApi/ApiClient.js
=> waiv - [3670]

src/client/components/Tools/DynamicTable/__tests__/__snapshots__/DynamicTable.test.js.snap, src/client/wallet/Transfer/Transfer.js, src/client/websites/WebsiteTools/Manage/__test__/__snapshots__/ManageWebsite.test.js.snap
=> add default currency

src/client/app/Sidebar/ObjectInfo.js, src/client/components/DnDList/DnDList.js, src/client/helpers/wObjectHelper.js, src/client/object/AppendModal/AppendForm.js, src/client/object/Catalog/CatalogWrap.js, src/client/object/wObjectHelper.js
=> WAIV-3183, WAIV-3575, WAIV-3387

src/client/helpers/wObjectHelper.js, src/client/object/Catalog/CatalogBreadcrumb/CatalogBreadcrumb.js, src/client/object/ObjectOfTypePage/ObjectOfTypePage.js, src/client/objectCard/ObjectCardView.js, src/client/rewards/Proposition/PropositionList/PropositionList.js
=> Waiv nest page

src/client/websites/WebsiteTools/Create/CreateWebsite.js
Fixes #
* Change 1
* Change 2
Finished task 3757
=> delete loader in button [3757]

src/client/websites/WebsiteTools/Configuration/WebsitesConfigurations.js
Fixes #
* Change 1
* Change 2
*** Finish Task https://maxiproject.atlassian.net/browse/WAIV-3728 ***
=> make changes tabs for tab is Configuration [3728]

src/client/components/Navigation/SettingsSidenav/SettingsSidenav.js, src/client/locales/default.json, src/client/websites/WebsiteTools/Administrators/Administrators.js, src/client/websites/WebsiteTools/Authorities/WebsitesAuthorities.js, src/client/websites/WebsiteTools/Moderators/WebsiteModerators.js, src/client/websites/WebsiteTools/ObjectsFilters/WebsiteObjectFilters.js, src/client/websites/WebsiteTools/Settings/WebsitesSettings.js, src/client/websites/websiteActions.js
Fixes #
* Change 1
* Change 2
*** Finish task https://maxiproject.atlassian.net/browse/WAIV-3676 ***
https://maxiproject.atlassian.net/browse/WAIV-3725
v                      https://maxiproject.atlassian.net/browse/WAIV-3768
=> hide configuration webSite for google user [3676]

src/client/components/EditorUser/SearchUsersAutocomplete.js, src/client/locales/default.json, src/client/websites/WebsiteTools/Manage/ManageWebsite.js, src/client/websites/WebsiteTools/Manage/ManageWebsite.less, src/client/websites/WebsiteTools/Manage/__test__/__snapshots__/ManageWebsite.test.js.snap
fix clear fields in the tab is Authorities [3725]
fix style button [3703]
Fixes #
* Change 1
* Change 2
*** https://maxiproject.atlassian.net/browse/WAIV-3703 ***
*** https://maxiproject.atlassian.net/browse/WAIV-3725 ***
*** https://maxiproject.atlassian.net/browse/WAIV-3768  ***
=> fix Changes tabs [3768]

src/client/locales/default.json, src/client/websites/WebsiteTools/Configuration/WebsitesConfigurations.js, src/client/websites/WebsiteTools/Reports/ReportsWebsite.less
Fixes #
* Change 1
* Change 2
*** Finish https://maxiproject.atlassian.net/browse/WAIV-3777 ***
*** Finish https://maxiproject.atlassian.net/browse/WAIV-3779 ***
=> fix style [3379]

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/object/AppendModal/AppendForm.js
=> WAIV-3734, WAIV-3733

src/client/Wrapper.js, src/client/feed/Page.js, src/client/feed/SubFeed.js
=> WAIV-3248, WAIV-3718, WAIV-3686

src/client/Wrapper.js, src/client/components/LayoutComponents/MainBody.js
=> add current page in mainbody

src/client/search/SearchAllResult/SearchAllResult.js, src/client/search/SearchAllResult/SearchAllResult.less, src/client/search/searchReducer.js
=> fix users search

src/client/app/appReducer.js, src/client/reducers.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.less
=> Add logo map

src/client/auth/authReducer.js, src/client/comments/Comments.js, src/client/comments/commentsActions.js, src/client/comments/commentsReducer.js, src/client/components/CommentFooter/Buttons.js, src/client/components/CommentFooter/CommentFooter.js, src/client/components/CommentFooter/CommentFooter.less, src/client/components/CommentFooter/Popover/CommentPopover.js, src/client/components/Comments/Comment.js, src/client/components/Comments/Comments.js, src/client/post/postActions.js, src/client/steemConnectAPI.js, src/waivioApi/ApiClient.js
=> add hide comment

src/client/websites/WebsiteTools/Objects/WebsiteObjects.js
=> changes in map

src/client/search/SearchAllResult/SearchAllResult.js
=> fixed search

src/client/components/Maps/Map.js, src/client/reducers.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js, src/client/websites/websiteActions.js, src/client/websites/websiteReducer.js, src/waivioApi/ApiClient.js
=> added points to map

src/client/styles/common.less, src/client/websites/WebsiteTools/Configuration/WebsitesConfigurations.js
=> added adaptation in mobile map

src/client/styles/modules/topnav-layout.less, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.less
=> Sites changes

src/client/helpers/postHelpers.js, src/client/post/EditPost/EditPost.js, src/client/rewards/Details/DetailsPostRequirments.js
=> (YAMMER-1155) - fix fall front

src/client/websites/websiteReducer.js
=> clean unused points

src/client/rewards/Rewards.js, src/client/styles/modules/feed-layout.less, src/client/styles/modules/grid.less
=> changes in widget

src/client/search/SearchAllResult/SearchAllResult.js, src/client/search/helpers.js, src/client/search/searchActions.js, src/client/search/searchReducer.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js, src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.js
=> fix follow button

src/client/app/appActions.js, src/client/components/Maps/mapHelper.js, src/client/post/Write/editorActions.js, src/client/reducers.js, src/client/search/SearchAllResult/SearchAllResult.js, src/client/search/SearchAllResult/SearchAllResult.less, src/client/search/WebsitesSearch/WebsiteSearch.js, src/client/search/searchActions.js, src/client/search/searchReducer.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js, src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.js, src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.less, src/client/websites/helper.js, src/client/websites/websiteActions.js, src/client/websites/websiteReducer.js, src/common/routes/switchRoutes.js, src/server/renderers/ampRenderer.js
=> search done

src/client/components/EditorExtended/components/toolbar.less
=> WAIV-2170, WAIV-2169

src/client/components/EditorExtended/EditorExtended.js, src/client/components/EditorExtended/editor.js, src/client/components/EditorExtended/index.less, src/client/components/Story/Body.less, src/client/components/Story/PostFeedEmbed.js, src/client/components/Story/PostFeedEmbed.less, src/client/components/Story/Story.less
=> WAIV-2304,2116

src/client/object/ObjectDynamicList.less, src/client/rewards/Debts/Debts.js, src/client/rewards/Payables/Payables.js, src/client/rewards/Payment/PaymentList.js, src/client/rewards/Receivables/Receivables.js, src/client/user/usersReducer.js, src/common/routes/switchRoutes.js, src/waivioApi/ApiClient.js
=> WAIV - [2350, 2163]

src/client/locales/default.json, src/client/locales/ru-RU.json, src/client/rewards/Debts/Debts.js, src/client/rewards/Payables/Payables.js, src/client/rewards/Payment/PaymentList.js, src/client/rewards/PaymentCard/PaymentCard.js, src/client/rewards/Receivables/Receivables.js, src/client/statics/EmptyPayables.js
=> Payments scroll

src/common/constants/rewards.js
=> fix translate

.eslintrc.js, package.json, scripts/eslint/index.js
=> Update eslint and add import sorting

src/client/store/appStore/appSelectors.js, src/client/store/editorStore/editorActions.js
=> Fix notification on creating post

.eslintrc.js, src/client/components/EditorExtended/EditorExtended.js, src/client/helpers/editorHelper.js, src/client/helpers/postHelpers.js, src/client/post/EditPost/EditPost.js
=> Fix bugs on editor [WAIV-2372]

src/client/post/EditPost/EditPost.js
=> Add object_type to post [WAIV-2445]

src/client/components/EditorExtended/EditorExtended.js, src/client/post/EditPost/EditPost.js, src/client/post/PostPreviewModal/PostPreviewModal.js
=> Fix changing title and remove requirements check on editing [WAIV-2483, WAIV-2479, WAIV-2493]

src/client/user/UserFollowers.js
=> Fixing bug when change sorting user Followers

src/client/components/Story/PostFeedEmbed.less, src/client/components/Story/Story.less
=> Fixing indentation in post with video from vimeo in mobile

src/client/components/Story/PostFeedEmbed.less, src/client/components/Story/Story.less
=> fix vimeo video 

src/client/search/SearchAllResult/SearchAllResult.js, src/client/search/WebsitesSearch/WebsiteSearch.js, src/client/store/commentsStore/commentsActions.js, src/client/websites/WebsiteLayoutComponents/Body/WebsiteBody.js, src/common/routes/switchRoutes.js
=> Waiv scroll

src/client/app/Sidebar/ObjectInfo.js
=> fix position of the number  if there is no heading

src/client/locales/de-DE.json, src/client/locales/default.json, src/client/locales/es-ES.json, src/client/locales/fr-FR.json, src/client/locales/hi-IN.json, src/client/locales/it-IT.json, src/client/locales/ja-JP.json, src/client/locales/pl-PL.json, src/client/locales/ru-RU.json, src/client/locales/uk-UA.json, src/client/locales/zh-CN.json
=> fix min post number

src/client/app/Sidebar/ObjectInfo.js, src/client/object/PicturesCarousel.less
=> Add related photos after gallery photos [WAIV-2589]

src/client/object/ObjectGallery/ObjectGallery.js, src/client/object/ObjectGallery/ObjectGalleryAlbum.js
=> Fix loading related photos [WAIV-2591]

src/client/components/UserCard.less
=> Fix padding of list items on sites [WAIV-2566]

src/client/components/ObjectHeader.less
=> Fix markup on object header [WAIV-2605]

src/client/components/Story/Body.js, src/client/components/Story/PostFeedEmbed.js, src/client/components/Story/PostFeedEmbed.less
=> Make video responsive [WAIV-2438]

src/client/app/Sidebar/ObjectInfo.js
=> Add sorting and fix phone show more [WAIV-2602]

src/client/object/LikeSection.js, src/client/object/LikeSection.less
=> Fix text error overlay [WAIV-2525]

src/client/rewards/ReferralProgram/Instructions/ReferralInstructionsView.js, src/client/rewards/ReferralProgram/Instructions/ReferralsInstructions.less
=> Hide checkbox if user in blacklist [WAIV-2423]

src/client/app/Sidebar/ObjectInfo.js, src/client/components/Story/PostFeedEmbed.less
=> Fix front error object page

src/client/components/Story/Story.js, src/client/post/CreateObjectModal/CreateObject.js, src/client/post/EditPost/EditPost.js, src/client/post/EditPost/index.js, src/client/store/editorStore/editorActions.js
=> Fix bugs on editor

src/client/components/EditorExtended/index.less, src/client/components/Story/StoryFull.js, src/client/post/EditPost/EditPost.js, src/client/post/PostContent.js, src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/store/editorStore/editorActions.js
=> Fix Bugs on Editor [WAIV-2449]

src/client/helpers/postHelpers.js, src/client/post/EditPost/EditPost.js, src/client/store/editorStore/editorActions.js
=> Fix Updating Post

src/client/helpers/postHelpers.js
=> Fix review post

src/client/helpers/postHelpers.js
=> Fix review modal on simple post

src/client/app/Sidebar/ObjectInfoExperts/ObjectInfoExperts.js, src/client/app/Sidebar/ObjectInfoExperts/ObjectInfoExperts.less, src/client/app/Sidebar/ObjectInfoExperts/WobjectSidebarFollowers/WobjectSidebarFollowers.js, src/client/app/Sidebar/ObjectInfoExperts/WobjectSidebarFollowers/WobjectSidebarFollowers.less, src/client/app/Sidebar/ObjectInfoExperts/WobjectSidebarFollowers/index.js, src/client/components/Sidebar/ObjectExpertise/ObjectExpertise.js, src/client/components/Sidebar/ObjectExpertise/index.js, src/client/components/UserCard.js, src/client/components/UserCard.less, src/client/object/Wobj/Wobj.js, src/client/object/Wobj/WobjectContainer.js, src/client/object/WobjFollowers.js, src/client/store/userStore/userActions.js, src/client/store/usersStore/usersActions.js, src/client/store/wObjectStore/wObjectSelectors.js, src/client/store/wObjectStore/wobjectReducer.js, src/client/store/wObjectStore/wobjectsActions.js, src/waivioApi/ApiClient.js
=> Make followers block in sidebar and center bar [WAIV-2578]

src/client/components/Sidebar/PostRecommendation.js
=> Fix display sidebar

src/waivioApi/ApiClient.js
=> Fix comments

src/client/store/editorStore/editorActions.js
=> Fix display objects name in editor [WAIV-2667]

src/client/helpers/postHelpers.js, src/client/post/EditPost/EditPost.js, src/client/post/EditPost/index.js, src/client/store/editorStore/editorActions.js
=> Fix cursor replace from object input to editor [WAIV-2674]

src/client/components/EditorExtended/util/markdownToEditorState.js
=> Remove image text when delete image [WAIV-2672]

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js
=> Fix front error [WAIV-2711]

src/client/helpers/postHelpers.js, src/client/post/EditPost/EditPost.js
=> Fix write a new review [WAIV-2660]

src/client/vendor/steemitHtmlReady.js
=> Image not display in preview if insert link in editor [WAIV-2162]

src/client/helpers/postHelpers.js
=> Hot fix review title

src/client/object/ObjectFeed/index.js
=> Fix display objects sequence [WAIV-2660]

src/client/components/EditorExtended/editor.js, src/client/components/EditorExtended/model/index.js, src/client/components/ImageSetter/ImageSetter.js, src/client/helpers/editorHelper.js
=> Fix paste images [WAIV-2671]

src/client/components/ImageSetter/ImageSetter.js
=> Fix images order

src/client/object/wObjectHelper.js
=> Make default sorting in custom sorting [WAIV-2761]

src/client/components/DnDList/DnDList.js, src/client/components/DnDList/DnDListItem.js, src/client/components/DnDList/DnDListItem.less, src/client/object/AppendModal/AppendForm.js
=> Fix truncate on DnD [WAIV-2760]

src/client/store/commentsStore/commentsActions.js
=> Fix edit comment [WAIV-2747]

src/client/object/AppendModal/AppendForm.js, src/client/object/wObjectHelper.js
=> Fix sorting, remove sorting by date [WAIV-2761]

src/client/objectCard/ObjectCardView.js
=> Fix redirect to object page from editor when create it [WAIV-2780]

src/client/post/PostModal.js
=> Fix redirect on modal [WAIV-2725]

src/client/helpers/voteHelpers.js
=> try to fix error

src/client/app/Sidebar/ObjectInfo.js
=> Fix display of gallery slider [WAIV-2724]

src/client/helpers/postHelpers.js, src/client/rewards/Details/Details.js
=> Fix gettings objects from url [WAIV-2474]

src/client/helpers/postHelpers.js, src/store/appStore/appSelectors.js
=> Fix undefined on host in json_metadata [WAIV-2842]

src/client/components/Navigation/Topnav.js
=> Fix front crash in search [WAIV-2841]

src/client/components/EditorExtended/util/markdownToEditorState.js, src/client/components/EditorExtended/util/videoHelper.js, src/client/helpers/regexHelpers.js
=> Add bitchute and rumble video [WAIV-2164]

src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.js, src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.less, src/client/components/EditorExtended/components/EditorSearchObjects/SearchItemObject/SearchItemObject.js, src/client/components/EditorExtended/components/EditorSearchObjects/SearchItemObject/SearchItemObject.less, src/client/components/ObjectSearchCard/ObjectSearchCard.less
=> Fix position of search block and add type of object [WAIV-2858]

src/client/vendor/embedMedia.js
=> Fix video rumble display [WAIV-2164]

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js, src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.js, src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.less, src/client/components/EditorExtended/components/EditorSearchObjects/SearchItemObject/SearchItemObject.js, src/client/components/EditorExtended/components/EditorSearchObjects/SearchItemObject/SearchItemObject.less, src/client/components/EditorExtended/editor.js, src/client/helpers/editorHelper.js, src/store/editorStore/editorActions.js
=> Fix bugs on search(#) [WAIV-2165]

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js, src/client/components/EditorExtended/EditorExtendedComponent/index.js
=> Fix search by hashtag [WAIV-2859]

src/client/rewards/Details/Details.less, src/client/rewards/Details/DetailsBody.js
=> Make eligible requirements red [WAIV-2872]

src/client/rewards/Details/Details.js
=> Fix display obj name in review [WAIV-2837]

src/store/editorStore/editorActions.js
=> Fix front crash [WAIV-2814]

src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.js
=> Fix count coordinates of search block

src/client/components/EditorExtended/EditorExtendedComponent/EditorExtended.js, src/client/components/EditorExtended/EditorExtendedComponent/index.js, src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.js, src/client/components/EditorExtended/editor.js, src/client/components/EditorExtended/util/constants.js, src/client/helpers/editorHelper.js, src/store/editorStore/editorActions.js, src/store/editorStore/editorReducer.js, src/waivioApi/ApiClient.js
=> Fix hashtags in preview post and fix bugs with cursor [WAIV-2814]

src/client/components/EditorExtended/editor.js, src/client/components/EditorExtended/util/editorStateToMarkdown.js, src/client/components/EditorExtended/util/keybinding.js
=> Fix front crash [WAIV-2904]

src/client/app/Sidebar/ObjectInfo.js, src/client/app/Sidebar/ObjectInfoExperts/ObjectInfoExperts.js, src/client/app/Sidebar/ObjectInfoExperts/WobjectNearby/WobjectNearby.js, src/client/app/Sidebar/ObjectInfoExperts/WobjectNearby/index.js, src/client/app/Sidebar/ObjectInfoExperts/WobjectSidebarFollowers/WobjectSidebarFollowers.js, src/client/app/Sidebar/ObjectInfoExperts/WobjectSidebarFollowers/index.js, src/client/components/Sidebar/ObjectExpertise/ObjectExpertise.js, src/client/components/Sidebar/ObjectExpertise/index.js, src/client/components/Sidebar/ObjectsRelated/ObjectsRelated.js, src/client/components/Sidebar/ObjectsRelated/ObjectsRelatedContent/ObjectsRelatedContent.js, src/client/components/Sidebar/ObjectsRelated/ObjectsRelatedContent/index.js, src/client/components/Sidebar/ObjectsRelated/index.js, src/client/object/Wobj/Wobj.js, src/client/object/Wobj/WobjectContainer.js, src/store/wObjectStore/wObjectSelectors.js, src/store/wObjectStore/wobjActions.js, src/store/wObjectStore/wobjectReducer.js
=> Remove unnecessary request on Wobj page [WAIV-2909]

src/client/discoverObjects/DiscoverFiltersSidebar/DiscoverFiltersSidebar.js
=> Fix loading map on page discover [WAIV-2914]

src/client/object/AppendModal/AppendForm.js
=> Fix map display object location [WAIV-2863]

src/store/wObjectStore/wobjActions.js
=> Remove last request child_objects on related block [WAIV-2909]

src/client/components/EditorExtended/components/EditorSearchObjects/EditorSearchObjects.js
=> Fix coordinates of search result block [WAIV-2858]

src/store/appendStore/appendActions.js, src/store/wObjectStore/wobjActions.js
=> Fix subscribe on block [WAIV-2930]

src/store/commentsStore/commentsActions.js, src/store/postsStore/postActions.js, src/store/usersStore/usersActions.js, src/store/wObjectStore/wobjActions.js
=> Add setTimeouts to subscribe on block [WAIV-2941]

package.json, src/store/appendStore/appendActions.js, src/store/commentsStore/commentsActions.js, src/store/postsStore/postActions.js, src/store/usersStore/usersActions.js, src/store/wObjectStore/wobjActions.js, src/waivioApi/config.json
=> Fix getting last block [WAIV-2941]

src/client/vendor/steemitHelpers.js, src/client/websites/WebsiteTools/Moderators/WebsiteModerators.js, src/client/websites/helper.js, src/store/appStore/appActions.js, src/store/commentsStore/commentsActions.js, src/store/postsStore/postActions.js, src/store/usersStore/usersActions.js, src/store/wObjectStore/wobjActions.js, src/store/websiteStore/websiteActions.js, src/store/websiteStore/websiteReducer.js, src/waivioApi/ApiClient.js, src/waivioApi/config.json
=> Fix getting last block number on websites [WAIV-2946]

src/client/locales/default.json
=> delete addition dot

src/client/post/CreateObjectModal/CreateObject.js, src/store/editorStore/editorActions.js
=> Fix creating of cards in editor [WAIV-2977]

src/client/rewards/MatchBots/MatchBotsModals/ModalsCurators/ModalsCurators.js
=> Fix message on delete curator [WAIV-2282]

src/client/app/Sidebar/ObjectInfoExperts/WobjectNearby/WobjectNearby.js, src/client/app/Sidebar/ObjectInfoExperts/WobjectNearby/index.js, src/client/rewards/rewardsHelper.js
=> Fix redirect from object [WAIV-2922]

src/client/components/EditorExtended/components/addbutton.less
=> Fix appear button on desktop [WAIV-2168]

src/store/appendStore/appendActions.js, src/store/wObjectStore/wobjActions.js
=> Change request on updates [WAIV-2986]

src/client/components/HeaderButton/HeaderButton.js
Fixes #
fixed route bug from tools to notsettings
=> Fixed route bug from tools to notificationsettings

src/client/components/Sidebar/ObjectCard.less, src/client/object/AppendCard/AppendCard.js
Fixes #
fixed objectCard styles and appendcard issues
=> fixed Objectcard styles  and appendcard issues

src/client/locales/default.json, src/client/object/AppendCard/AppendCard.js, src/client/websites/constants/validateRules.js
Fixes #
made alert human readable
=> made alert human readable

src/client/vendor/steemitHelpers.js, src/client/websites/WebsiteTools/ObjectsFilters/WebsiteObjectFilters.js
Fixes #
fixed  rating  on object card from "B" to M
=> Waiv  3044

src/client/components/Navigation/Notifications/NotificationCampaignReservation.js, src/client/locales/default.json
Updated  notification as has 'deactivated the campaign for'
=> Updated notification

src/client/websites/WebsiteTools/Administrators/Administrators-nightmode.less, src/client/websites/WebsiteTools/Administrators/Administrators.js, src/client/websites/WebsiteTools/Administrators/Administrators.less, src/client/websites/WebsiteTools/Authorities/WebsitesAuthorities-nightmode.less, src/client/websites/WebsiteTools/Authorities/WebsitesAuthorities.js, src/client/websites/WebsiteTools/Authorities/WebsitesAuthorities.less, src/client/websites/WebsiteTools/Moderators/WebsiteModerators-nightmode.less, src/client/websites/WebsiteTools/Moderators/WebsiteModerators.js, src/client/websites/WebsiteTools/Moderators/WebsiteModerators.less, src/client/widgets/SelectUserForAutocomplete.js, src/client/widgets/widgetsStyle-nightmode.less, src/client/widgets/widgetsStyle.less
fixed Administrators dark theme on : Website Administrators, Webside Moderators, Authorities,  and  find users aftersearch.
=> dark themein Adms, Moderators  auths and setts fix

src/client/rewards/Create-Edit/CreateFormRenderer.js, src/client/rewards/Create-Edit/CreateReward-nightmode.less, src/client/rewards/Create-Edit/CreateReward.less, src/client/rewards/Create-Edit/validators.js
In rewards campaign create form  fixed exceed notfc and also added styles
* CreateRewardForm > CreateFormRenderer
* dependant components: Validators and fieldsData
=> fixed exceed notfc. added styles

src/client/post/EditPost/EditPost.js
Fixed not dissapearing objects
EditPost > PostObjectCard
=> removed bug with dissapearing object

src/client/activity/CustomJSONMessage.js
changed "Ignore" to "Muted" in Activity
=> in Activity  - changed ignore to mute

src/client/objectCard/RatingsWrap/RatingsWrap.js, src/client/objectCard/RatingsWrap/RatingsWrap.less
fixed objectCard responsiveness
=> fixed objectCard  responsivness

src/client/vendor/ReduxInfiniteScroll.js
removed bug in activity scroll error
=> removed bug in activity scroll error

src/store/editorStore/editorActions.js
changed : 
IN postHelpers > editorActions> host
+removed http from json metadata
=> removed http from json

src/client/objectCard/RatingsWrap/RatingsWrap.less, src/client/rewards/Proposition/Proposition.less
fixed bug in dining gift  responsiveness
=> finally fixed bugs in dining gifts

src/client/rewards/Campaign/Campaign.js
=> changed earn up to to "earn"

src/client/components/Navigation/Notifications/NotificationDeactivationCampaign.js
=> now it goes to  author object

src/client/components/Navigation/Notifications/NotificationWithdrawRoute.js
=> added transfers link

src/client/components/TagsSelector/TagsSelector.js, src/client/locales/default.json, src/client/post/PostPreviewModal/PostPreviewModal.js, src/client/post/PostPreviewModal/PostPreviewModal.less
=> added  waivio hashtag in case user dont + notif

src/client/wallet/ConvertHiveCompleted.js, src/client/wallet/ConvertHiveRequest.js, src/client/wallet/UserWalletTransactions.less, src/client/wallet/WalletTransaction.js, src/common/constants/accountHistory.js
added notif, transaction, and some styles
=> added notif, transaction, and some styles

src/client/post/PostPreviewModal/PostPreviewModal.less
=> added color

src/client/object/Catalog/CatalogWrap.less
=> added styles to empty list case

src/client/wallet/ConvertHbdCompleted.js, src/client/wallet/ConvertHbdRequest.js, src/client/wallet/ConvertHiveCompleted.js, src/client/wallet/ConvertHiveRequest.js, src/client/wallet/UserWalletTransactions.less
=> final version

src/client/wallet/ConvertHiveCompleted.js, src/client/wallet/WalletTransaction.js
=> renamed notif

src/client/rewards/Rewards.less
=> fixed bug with overflows

src/client/rewards/Details/Details.less, src/client/rewards/Details/DetailsPostRequirments.js
=> fixed bugs in modal

src/client/object/ObjectOfTypePage/ObjectOfTypePage.less
=> added styles

src/client/object/AppendModal/AppendForm.js
=> changed validation

src/client/rewards/CampaignFooter/CampaignButtons.js, src/client/rewards/CampaignFooter/CampaignFooter.less
=> changed border-radius

src/client/rewards/Details/Details.less, src/client/rewards/Details/DetailsPostRequirments.js
=> added breaks and nowraps

src/client/components/TagsSelector/TagsSelector.js
removed hashtag waivio from object filters
=> removed hashtag waivio from object filters

src/client/components/Navigation/Notifications/Notification.less
=> fixed bug in styles

src/client/components/Navigation/Notifications/Notification.less, src/client/components/Navigation/Notifications/NotificationWebsiteBalance.js, src/client/locales/default.json
added formattedmessage for notification
=> added translation type to  notification

src/client/locales/af-ZA.json, src/client/locales/ar-SA.json, src/client/locales/ca-ES.json, src/client/locales/cs-CZ.json, src/client/locales/da-DK.json, src/client/locales/default.json, src/client/locales/es-ES.json, src/client/locales/et-EE.json, src/client/locales/fil-PH.json, src/client/locales/fr-FR.json, src/client/locales/hi-IN.json, src/client/locales/hr-HR.json, src/client/locales/hu-HU.json, src/client/locales/id-ID.json, src/client/locales/it-IT.json, src/client/locales/ja-JP.json, src/client/locales/ko-KR.json, src/client/locales/ms-MY.json, src/client/locales/pl-PL.json, src/client/locales/pt-BR.json, src/client/locales/uk-UA.json, src/client/locales/zh-CN.json
=> change SP to HP for curation message in Activity

src/client/rewards/MatchBots/MatchBots.less
=> fixed the bug

src/client/components/EditorExtended/editor.js
=> fixed bug onUpArrow

src/client/wallet/WalletTable/WalletTable.js, src/waivioApi/ApiClient.js
1) Now unauthorized users can view advanced reports  
2) Only authorized users can edit it
3) only authorized user header is sent to back
=> added functionalities to advanced reports

src/client/rewards/Rewards.js
=> fixed the bug with rewards

src/client/rewards/Rewards.js
removed  duplicate request, show time reduced.
=> removed  duplicate request, show time reduced.

src/client/wallet/TransfersCards/TokenBoughtCard.js/TokenBoughtCard-nightmode.less, src/client/wallet/TransfersCards/TokenBoughtCard.js/TokenBoughtCard.less, src/client/wallet/UserWalletTransactions-nightmode.less, src/client/wallet/WAIVwallet/components/WAIVWalletTransferList/WAIVWalletTransferList-nightmode.less, src/client/wallet/WAIVwallet/components/WAIVWalletTransferList/WAIVWalletTransferList.less, src/client/wallet/WalletSummaryInfo/WalletSummaryInfo-nightmode.less, src/client/wallet/WalletSummaryInfo/WalletSummaryInfo.less
added nightmode to waiv wallet
=> added nightmode to waiv wallet

src/client/rewards/Rewards.js
=> added non authenticated  request

src/client/rewards/QiuckRewardsModal/QuickRewardsModal.less, src/client/rewards/QiuckRewardsModal/components/FirstScreen/FirstScreen.js, src/client/rewards/QiuckRewardsModal/components/FirstScreen/FirstScreen.less, src/client/rewards/QiuckRewardsModal/components/SecondScreen/SecondScreen.less
=> updated styles on modal

src/client/styles/custom.less, src/client/websites/WebsiteLayoutComponents/Header/MainPageHeader.js, src/client/websites/WebsiteLayoutComponents/Header/WebsiteHeader.less
=> updated header

src/client/wallet/TransfersCards/DelegatedTo.js, src/client/wallet/TransfersCards/MarketBuyCard.js, src/client/wallet/UserWalletTransactions.less
=> updated wallet history

src/client/wallet/WAIVwallet/components/WAIVWalletSummaryInfo.js, src/store/userStore/userActions.js
=> add stopped add for stop campaing

src/client/wallet/TransfersCards/TransactionCardContainer.js, src/client/wallet/WalletHelper.js
=> now it doenst display integer
